### ISSUE TITLE
RTSP Stream without Video Audio only

### ISSUE THREAD

**Issue by schaelrippe** [roleoroleo/yi-hack-Allwinner#102]
HI! Thanks for this great Project i really appreciate the work wich was going  done here!

Sadly i got a little Problem. I Trying to solve it for hours already.

When i open rtsp://admin:admin@192.168.178.34:554/ch0_0.h264
in VLC Player it doenst show a picture. Just the Sound with arround 2-3 secounds delay.

I tried resetting the cam
looked at the network
put the same link in Synology Survailance station (here i see a video)

info attachment 

![RTSP](https://user-images.githubusercontent.com/68955613/88812388-f356e500-d1b7-11ea-82ba-52c608718d32.JPG)

![RTSP 2](https://user-images.githubusercontent.com/68955613/88812548-226d5680-d1b8-11ea-8ba2-1e4bd030c2d2.JPG)

please help if you can
Thanks!

**Comment by roleoroleo** [comment]
Low res works?

**Comment by schaelrippe** [comment]
sadly no. in VLC in cant see any video HIres LOWres.

**Comment by roleoroleo** [comment]
Try the last version, I fixed a problem.
