### ISSUE TITLE
9FCN config step

### ISSUE THREAD

**Issue by YanchiHuang** [roleoroleo/yi-hack-Allwinner#103]
First of all, thank you for publishing this tool

I buy YI camera chinese version(9FCNY31DAI)
I try yi-hack MStar is not work,until find [yi-hack-Allwinner](https://github.com/roleoroleo/yi-hack-Allwinner/) fireware

I follow [yi-hack-MStar Wiki Use proxychains ng to connect your app (thanks to @x571) ](https://github.com/roleoroleo/yi-hack-MStar/wiki/Use-proxychains-ng-to-connect-your-app-(thanks-to-@x571)) Setup by Setup,

But....7th step I can't find  and create `/etc/proxychains.conf`

I find path `/home/yi-hack-v4/etc/proxychains.conf` have effective

![image](https://user-images.githubusercontent.com/4203468/89117603-a9c90b80-d4d1-11ea-9d11-11c73cc45871.png)

I follow  [Dump-your-backup-firmware-(SD-card)](https://github.com/roleoroleo/yi-hack-Allwinner/wiki/Dump-your-backup-firmware-(SD-card)) dump the [file](https://www.dropbox.com/s/zcv6dl3nn8tpw67/dump.zip)

camera chip module is `QG2101A`
![image](https://user-images.githubusercontent.com/4203468/89117287-2f978780-d4cf-11ea-9512-58aa49e15c9b.png)

Hope it helps. 

Tips: 
To use this camera, you need to be able to connect to the Chinese network when it is turned on before it can be used

**Comment by roleoroleo** [comment]
Edit the file /home/app/cloudAPI and change this line
```
$YI_HACK_PREFIX/bin/proxychains4 ./cloudAPI_real "$@"
```
with
```
$YI_HACK_PREFIX/bin/proxychains4 -f /home/yi-hack/etc/proxychains.conf ./cloudAPI_real "$@"
```
