### ISSUE TITLE
Yi Dome Guard support

### ISSUE THREAD

**Issue by artemy** [roleoroleo/yi-hack-Allwinner#105]
Camera seems to be Allwinner-based, although markings on the chip state "QG2101B", which is ambiguous to me.

I tried adapting this firmware (with compiling custom images for camera's firmware code (which is r30gb), but that approach didn't work since mtdblock3 partition (home) is not writable.

What would be the steps to try to make the hacks in this repo work for that model?

Attached are mtd table and boot log.
[mtd.txt](https://github.com/roleoroleo/yi-hack-Allwinner/files/5021861/mtd.txt)
[boot.log](https://github.com/roleoroleo/yi-hack-Allwinner/files/5021841/boot.log)

I also have dumped stock firmware, can upload it if needed.

**Comment by NURIHAKIM** [comment]
Yep I'm at the same spot!

**Comment by roleoroleo** [comment]
The cam is Allwinner based but the structure is different.
The size of the flash is only 8 MB (the y20ga is 16 MB) and the partition schema is different.
I could try to study it if you can share the dump (rootfs and home are enough).

**Comment by artemy** [comment]
Both partitions should be in this zip archive: [r30gb_fw.zip](https://github.com/roleoroleo/yi-hack-Allwinner/files/5022810/r30gb_fw.zip)

**Comment by roleoroleo** [comment]
Ok, I'll look into this.

**Comment by roleoroleo** [comment]
As I already noticed, the flash structure is very different.
home is not a jffs2 partition, it's a read only squashfs.
And the size of the flash is too small to add other programs.
Probably it's possible to create a new hack based on SD card but it's a new project.
No chances to integrate this cam in the current project.

**Comment by roleoroleo** [comment]
Probably it's possible to save:

- toolchain
- sources
- build environment (partially)

**Comment by NURIHAKIM** [comment]
Thanks for looking into it. Going to send some coffee to you!

**Comment by roleoroleo** [comment]
Thank you for your contrubution.

**Comment by roleoroleo** [comment]
@artemy 
Could you send me your mtdblock4?
Probably I'm able to create a new hack for your cam, the flash content is pretty the same.
See this issue:
https://github.com/roleoroleo/yi-hack-Allwinner/issues/157

**Comment by artemy** [comment]
@roleoroleo right I'll try to find time this week

**Comment by artemy** [comment]
There it is
[Uploading mtdblock4.bin.zip…]()

**Comment by roleoroleo** [comment]
Thanks.

**Comment by roleoroleo** [comment]
Yes, your cam is r30gb suffix and the hack will be the same as y21ga model:
https://github.com/roleoroleo/yi-hack-Allwinner-v2

**Comment by roleoroleo** [comment]
If you want to try this beta, please visit this issue:
https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/3

Version 0.0.6 contains beta support for r30gb.

**Comment by janowakps** [comment]
@roleoroleo what is the situation now? does YI Dome Guard YRS.3019 have alternative firmware?
