### ISSUE TITLE
anyone tried 8.2.0.0A_202007211802 yet?

### ISSUE THREAD

**Issue by divadiow** [roleoroleo/yi-hack-Allwinner#107]
8.2.0.0A_202007211802 has just been released. the release note in the app is "increase the image quality".

Has anyone tried updating a hacked camera and or hacking an already-updated camera?

**Comment by divadiow** [comment]
well, saying yes to the update in the app just shows the 2019 version still after a reboot.

I had to remove the hack, update firmware and re-apply the hack. seems OK, though I haven't tested anything but uploading to ftp/yi app and clicking around the yihack pages.

image looks more saturated now perhaps

![Capture](https://user-images.githubusercontent.com/62958974/89453438-2ae50480-d757-11ea-9d2b-b4441169437f.PNG)

**Comment by spamsool** [comment]
Have you check the stream bitrate on the new fw? The image bitrate on Allwinner version 2019 it is way lower (like even 3-4 times lower) than in the Mstar version. Mstar model has a way more details shown. You can check the current HD bitrate in the App.

**Comment by divadiow** [comment]
my app hovers around 90-160kbps.

I have noticed the file sizes for my ftp uploads are bigger.

bitrate info for 60s vids before and after the firmware update:

![Capture](https://user-images.githubusercontent.com/62958974/89517953-39243680-d7d2-11ea-854f-00160a2e6fad.PNG)

**Comment by roleoroleo** [comment]
I will check the new version.
I downloaded it and it's about 4 MB. The previous version was 3.1 MB.
A lot of code...

**Comment by roleoroleo** [comment]
I tried it and it seems to work correctly with the hack.
If you update a hacked camera you need to apply again the hack.
Otherwise, you can remove the hack, upgrade the cam and apply again the hack.

**Comment by spamsool** [comment]
I updated the fw but rtsp server is not working now. I cannot connect to the stream. How could I check whether is is working fine?
When I try to run it manually:
 root@yi-88fb:/tmp/sd# /bin/sh /home/yi-hack/script/wd_rtsp.sh
/home/yi-hack/script/wd_rtsp.sh: line 90: tail: not found
/home/yi-hack/script/wd_rtsp.sh: line 90: rRTSPServer: not found

**Comment by roleoroleo** [comment]
You have to souce the env when you start it manually.
`. /home/yi-hack/script/env.sh`

**Comment by spamsool** [comment]
I reset hack to default and reboot the camera - it started to work. Sorry for that, I should have done it first ;)

**Comment by roleoroleo** [comment]
No problem.

**Comment by Dragon0501** [comment]
Everytime I select the update the camera reboots with the former firmware. How can the firmware be updated? And if it is necessary to remove the hack for it how can the hack be removed?

**Comment by roleoroleo** [comment]
When the camera restarts with the same version the reason is "out of memory" during upgrade procedure.

Two possible solution:
1. Unhack the cam before upgrade (see the wiki).
2. Enable swap file.

**Comment by pbanj** [comment]
updated my cameras, they seem to be working well.

**Comment by divadiow** [comment]
any juicy discoveries about what's changed with the new firmware?

**Comment by EnricoFerro** [comment]
For the "Switch on/off the camera" continue the discussion in #120 

For the problem "Baby crying detect". I must continue the test, but I suppose that the problem ( if any ) is in `ipc_cmd' or in mqtt...

**Comment by roleoroleo** [comment]
> For the problem "Baby crying detect". I must continue the test, but I suppose that the problem ( if any ) is in `ipc_cmd' or in mqtt...

With ipc_sniff you can check if the system (yi system) detects the event.

**Comment by EnricoFerro** [comment]
Ok the ipc_sniff give this result:
```
root@yi-camera:/tmp/sd# ./ipc_sniff
IPC message. Len: 16. Status: No error information!
Parsing message.
04 00 00 00 02 00 00 00 04 60 04 60 00 00 00 00
GOT UNRECOGNIZED MESSAGE
IPC message. Len: 16. Status: No error information!
Parsing message.
01 00 00 00 10 00 00 00 e7 00 e7 00 00 00 00 00
GOT UNRECOGNIZED MESSAGE
```

I'm trying changing the header flag and recompile:
```
#define IPC_BABY_CRYING         "\x04\x00\x00\x00\x02\x00\x00\x00\x04\x60\x04\x60\x00\x00\x00\x00"
```

**Comment by EnricoFerro** [comment]
Update: 

with this modify, the specific device with :
BSUS*
8.2.0.0A_202007211802

The "baby crying" work correctly.

I've created an artifact: https://github.com/EnricoFerro/yi-hack-Allwinner/suites/1090707352/artifacts/15118350

**Comment by roleoroleo** [comment]
But with the old fw 8.2.0.0A_2019* does it work?
If yes, I could add a second define and leave the old one.

**Comment by EnricoFerro** [comment]
With another model with 8.2.0.0A_2019* for me work correctly the current value:
```
IPC message. Len: 16. Status: No error information!
Parsing message.
04 00 00 00 02 00 00 00 02 60 02 60 00 00 00 00
```

I've never created a pull request because i suppose that a second define is better.

**Comment by roleoroleo** [comment]
Maybe the message is variable?
Maybe it embeds other parameters like intensity, duration, probability...

**Comment by Aqua-Ye** [comment]
> When the camera restarts with the same version the reason is "out of memory" during upgrade procedure.
> 
> Two possible solutions:
> 
> 1. Unhack the cam before upgrade (see the wiki).
> 2. Enable swap file.

- could you explain how to enable swap file?
- in case of an unhack, is it possible to save the config in order to restore the hack after upgrading?

**Comment by pbanj** [comment]
Yes you can back your config up via the web interface. The swap file toggle is under the configuration tab. I suggest you actually poke around the firmware

**Comment by noelmom** [comment]
I can't get my 9FUSY31 running 8.2.0.0A_202007211802 to flash.  The blue light just keeps flashing camera doesn't boot.  Any ideas?

**Comment by nbendall34** [comment]
has anyone been able to hack the new fw because I can't get the hack to work on my 9FUS. I just get a flashing blue light constantly.

**Comment by nbendall34** [comment]
#165

**Comment by nbendall34** [comment]
I have opened a separate issue here for my problem #165
