### ISSUE TITLE
2 way audio?

### ISSUE THREAD

**Issue by BenjaminFaal** [roleoroleo/yi-hack-Allwinner#109]
Is 2 way audio possible? Or is there a command to play audio files?

**Comment by roleoroleo** [comment]
The sound device is busy.
The rmm process locks it.
If you don't kill rmm you can't run a program to play a sound.

**Comment by BenjaminFaal** [comment]
Okay and what program/command would you use, i saw some .aac files in the stock firmware but how are they played?
