### ISSUE TITLE
Return to stock firmware?

### ISSUE THREAD

**Issue by Mick2011** [roleoroleo/yi-hack-Allwinner#110]
Could you please advise how this can be done and if you have a link to the stock firmware?

I would like to return to it as I can't rewind on my recordings while on this firmware. It did work for me while on stock.

**Comment by divadiow** [comment]
https://github.com/roleoroleo/yi-hack-Allwinner/wiki/Remove-the-hack

**Comment by Mick2011** [comment]
Thank you. Just what I was looking for.

**Comment by sermayoral** [comment]
@Mick2011  Please, close the issue if it have been resolved!!
