### ISSUE TITLE
fix IP-address

### ISSUE THREAD

**Issue by JohGrei** [roleoroleo/yi-hack-Allwinner#111]
is it possible to set a fixed ip-address on this device

**Comment by roleoroleo** [comment]
Try to create a script:
/tmp/sd/yi-hack/startup.sh

With ifconfig and route commands.

**Comment by JohGrei** [comment]
Thanks, it works

**Comment by sermayoral** [comment]
I have tried this, but after a time (maybe a couple os days) the cam lost the IP. Anyone is experimenting this as well??

**Comment by SeriousPat** [comment]
I Have the same problem: https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/347
