### ISSUE TITLE
0.1.9 > thumbnail for videos recorded

### ISSUE THREAD

**Issue by murigny** [roleoroleo/yi-hack-Allwinner#116]
Hello all.

I compile new build 0.1.9 and it work fine, thanks !! :)

Can you add thumbnail on http webpage for videos ?

Thx again for your good work ;)

**Comment by roleoroleo** [comment]
I think it's too hard without ffmpeg.

**Comment by murigny** [comment]
Thx, I forgot that ffmpeg is not embedded ;)
