### ISSUE TITLE
BFUS YIcam randomly reboot

### ISSUE THREAD

**Issue by sajikur** [roleoroleo/yi-hack-Allwinner#118]
on 1.8 firmware, cams (I've 4 BFUS) lose connection and I must to reboot manually to reconnect
Any ideas to solve?
Thanx

**Comment by roleoroleo** [comment]
Do you have this problem only with 1.8?

**Comment by sajikur** [comment]
Hi, thanx for your answer. No, same problem with 1.7

In data 18 agosto 2020 18:26:31 roleo <notifications@github.com> ha scritto:

**Comment by bonuzzz** [comment]
weak wifi signal for example

**Comment by sajikur** [comment]
No, 4 cams 1 router 2 apn. WiFi signal is good in every rooms

In data 18 agosto 2020 23:08:12 bonuzzz <notifications@github.com> ha scritto:

**Comment by sajikur** [comment]
News! Searching in configuration Web page of every cam, I see that every 
cam reboots randomly. So, my first report was wrong. They don't loose WiFi 
but reboot randomly. On 1.8 and 1.7 firmware

In data 18 agosto 2020 18:26:31 roleo <notifications@github.com> ha scritto:

**Comment by roleoroleo** [comment]
Probably the cams are out of memory.
Try to remove unneded services.
Or enable swap file.

**Comment by sajikur** [comment]
Could you tell me how to enable swap file?
Unneded services are already disabled.
Thank you for your answer
Mario
In data 19 agosto 2020 12:06:58 roleo <notifications@github.com> ha scritto:

**Comment by sajikur** [comment]
oops, found the swap file trigger.
I'll let you know if this solved my issue

**Comment by sajikur** [comment]
ok, your solution (swap file) seems solve my issue. THANK YOU FOR YOUR SUPPORT!!!
