### ISSUE TITLE
Restore stock firmware

### ISSUE THREAD

**Issue by TimDowker** [roleoroleo/yi-hack-Allwinner#12]
Is there a procedure outlined anywhere on how to return to stock firmware?

Thanks

**Comment by roleoroleo** [comment]
Edit the last lines of the file /home/app/init.sh:
```
./rmm &
sleep 2
#./mp4record &
#./cloud &
#./p2p_tnp &
#./oss &
#./watch_process &

/usr/sbin/telnetd &
/home/yi-hack/script/system.sh
```

Remove the comment sign '#' and remove the commands telnetd and system.sh:
```
./rmm &
sleep 2
./mp4record &
./cloud &
./p2p_tnp &
./oss &
./watch_process &
```

Finally, remove the /home/yi-hack directory and its contents.

**Comment by digitalchou** [comment]
conecting thru ssh ?

**Comment by roleoroleo** [comment]
ssh or telnet.

**Comment by roleoroleo** [comment]
See the wiki for the correct procedure.
