### ISSUE TITLE
y20gam_0.1.8.tgz vs y20ga_0.1.8.tgz

### ISSUE THREAD

**Issue by divadiow** [roleoroleo/yi-hack-Allwinner#120]
Hello

What's the difference between these two packages? I haven't found any previous question or mention of it in the wiki.

**Comment by roleoroleo** [comment]
It's the same file copied twice.
At first I used the wrong model name, so I changed it to correct the issue.
To maintain the compatibility in the ota update, I'm also uploading the fw with the old name (for the next 2 or 3 versions).

**Comment by divadiow** [comment]
ah ok cool. I shall redo hack with correct y20gam so all is correct for the future

thanks

**Comment by roleoroleo** [comment]
The correct name is y20ga

**Comment by divadiow** [comment]
thanks
