### ISSUE TITLE
Snapshot URL without credentials box appearing

### ISSUE THREAD

**Issue by rt400** [roleoroleo/yi-hack-Allwinner#121]
Hi,
i try to set snapshot url with username and password but with no success.
can you help me with this ?

**Comment by roleoroleo** [comment]
You have to configure authentication in "Configuration page" and use basic auth.

e.g.
http://user:password@IP-CAM:8080/cgi-bin/snapshot.sh

**Comment by rt400** [comment]
thanks.. somehow in EDGE its won't work...
