### ISSUE TITLE
how to grab recordings via ssh?

### ISSUE THREAD

**Issue by tatoosh** [roleoroleo/yi-hack-Allwinner#123]
Where can i find the mp4 files in the filesystem by connection with ssh?

Thx a lot

**Comment by roleoroleo** [comment]
/tmp/sd/record

**Comment by tatoosh** [comment]
Thanks alot!
Is there a possibility also get the screenshots taken by web? `http://<IP>:8080/cgi-bin/snapshot.sh?res=low&watermark=yes`
I want to trigger my doorbell to take a screenshot and send it by push to my mobile.

**Comment by roleoroleo** [comment]
imggrabber -r high -w > /tmp/image.jpg

**Comment by tatoosh** [comment]
great thanks!! - i changed it a bit, so i can grab it by url `/home/yi-hack/bin/imggrabber -r low -w > /tmp/sd/record/door.jpg`

**Comment by tatoosh** [comment]
Can i call a script by URL to renew my file `/tmp/sd/record/door.jpg` ? so this is always my newest jpg?

**Comment by roleoroleo** [comment]
It should work.
Call it with the address `http://IP_CAM:8080/cgi-bin/door.sh`

**Comment by tatoosh** [comment]
I forgot to add shebang `#!/bin/bash` - now it's working thanks!

**Comment by tatoosh** [comment]
Can u please  put this script in the release version?

/home/yi-hack/www/cgi-bin/door.sh
```
#!/bin/bash
/home/yi-hack/bin/imggrabber -r low -w > /tmp/sd/record/door.jpg
```
chmod +x  /home/yi-hack/www/cgi-bin/door.sh

**Comment by roleoroleo** [comment]
I don't remember.
Why didn't you use the snapshot web service?
`http://<IP>:8080/cgi-bin/snapshot.sh?res=low&watermark=yes`

**Comment by tatoosh** [comment]
With my script i always can write the image screenshot to the same filename `/tmp/sd/record/door.jpg`.
I use this image for my doorbell over home assistant. By a ring a telegram bot sends me the image ;)

**Comment by roleoroleo** [comment]
The web service does the same, without saving the image.
It returns directly from the http call.

**Comment by tatoosh** [comment]
I need a saved image for my script

**Comment by tatoosh** [comment]
Reminder for my question: _Can u please put this script in the release version?_ is that possible for u?

Thx

**Comment by roleoroleo** [comment]
Sorry, I forgot.

**Comment by roleoroleo** [comment]
I added your feature to the current web service as an option.
The option file create a new image in /tmp/sd/record
So your syntax will be:
```
http://192.168.7.32:8080/cgi-bin/snapshot.sh?res=low&watermark=yes&file=door.jpg
```

https://github.com/roleoroleo/yi-hack-Allwinner/commit/6fdfd0c01bad9bbc6ffea04fff35c2f380abc01f

**Comment by tatoosh** [comment]
Thanks a lot, so i can use it with the next release or?

**Comment by roleoroleo** [comment]
You can edit this file now copying the commit.
And when I will release the new version you will not lose the changes made.
