### ISSUE TITLE
show WLAN signal strength 

### ISSUE THREAD

**Issue by tatoosh** [roleoroleo/yi-hack-Allwinner#129]
It would be nice to see the WLAN signal strength on the WebGui

**Comment by elraro** [comment]
Working on this!

**Comment by elraro** [comment]
I would like to know your opinion,

Do you like an icon? text? or both at once?

The text would be: strong, medium, weak and no signal

At the moment it works only with icon

![Screenshot_14](https://user-images.githubusercontent.com/1223299/91647784-0e3ea280-ea5f-11ea-8a6e-3dfa84585e55.png)

Best regards

**Comment by tatoosh** [comment]
Thanks for asking. I would like to see percentage to optimize the place for the cam or repeater. Image is farly better than nothing ;)
What do you think about placing to the Top Menu?
![image](https://user-images.githubusercontent.com/3670907/91659565-c7899080-ead0-11ea-88d5-98175e152202.png)

**Comment by elraro** [comment]
Uhm, I think it's a strange place to set the strength of the wifi signal, when you have a page dedicated to the status of the camera.

@roleoroleo what do you think?

I like the percentage, i will aggregate it

Regards,

**Comment by roleoroleo** [comment]
The free space in the top menu is low.
I prefer in the status page, but both icon and percentage if possible.

**Comment by elraro** [comment]
![captura](https://user-images.githubusercontent.com/1223299/93721998-eb9e3600-fb93-11ea-9d55-21dd679eb34a.png)

Done!

**Comment by roleoroleo** [comment]
@elraro
I have an issue with the value:
https://github.com/roleoroleo/yi-hack-Allwinner/pull/150#issuecomment-699508964

**Comment by tatoosh** [comment]
Not working, WLAN is connected but the Status is wrong

![image](https://user-images.githubusercontent.com/3670907/95120569-0fde4300-074e-11eb-97da-b6db202ec761.png)

**Comment by elraro** [comment]
> 
> 
> Not working, WLAN is connected but the Status is wrong
> 
> ![image](https://user-images.githubusercontent.com/3670907/95120569-0fde4300-074e-11eb-97da-b6db202ec761.png)

Can you paste the output of /proc/net/wireless ?

**Comment by tatoosh** [comment]
After reboot it's fine - here are the results if that helps. Thx

![image](https://user-images.githubusercontent.com/3670907/95193299-e49e3700-07d3-11eb-9c3c-645944ff623b.png)
![image](https://user-images.githubusercontent.com/3670907/95193314-ec5ddb80-07d3-11eb-85f5-2ecf7a10c0b6.png)

**Comment by elraro** [comment]
@tatoosh please, if you detect again the problem, run the command before restart. ty!!!
