### ISSUE TITLE
Video Record duration

### ISSUE THREAD

**Issue by scmanjarrez** [roleoroleo/yi-hack-Allwinner#136]
Hi, thank you very much for your work. It works really well.

Is it possible to modify the video record duration? I haven't found any parameter related to that in the web interface.

Thanks.

**Comment by roleoroleo** [comment]
No sorry.
This feature is implemented by yi.
It's not under my control.

**Comment by scmanjarrez** [comment]
Ok, thank you!

**Comment by ricardojlrufino** [comment]
Its possible to start a record video like 

root@xiaoyi:/home/yi-hack/bin# ./h264grabber -r HIGH -d > video.mp4

- Ajust VLC Codec for H.264
https://www.youtube.com/watch?v=Vk5viMViSXk

**Comment by ricardojlrufino** [comment]
One options is change source of h264grabber, to set a timer ...

**Comment by ricardojlrufino** [comment]
You can use:
./h264grabber -r HIGH -d > /tmp/sd/record/VIDEO_1.MP4  & sleep 30 ; kill $!

**Comment by roleoroleo** [comment]
The output format is not exactly an MP4 file.
It's a h264 raw stream, but you can read or convert it easily.
And with this method, audio is not available.

**Comment by ricardojlrufino** [comment]
truth I realized this now ...
How do I get the audio and video ?

**Comment by roleoroleo** [comment]
Sorry, is not possible.
