### ISSUE TITLE
Missing rsync dependency

### ISSUE THREAD

**Issue by elraro** [roleoroleo/yi-hack-Allwinner#137]
Hello,

https://github.com/roleoroleo/yi-hack-Allwinner/wiki/Build-your-own-firmware-(thanks-to-@Xandrios)

In the dependencies, it is necessary to add rsync. It is needed during the alsa compilation process.

Regards,

**Comment by roleoroleo** [comment]
Ok, thanks.

**Comment by elraro** [comment]
You're welcome
