### ISSUE TITLE
9FUSY31 running 8.2.0.0A_202007211802 not flashing.

### ISSUE THREAD

**Issue by noelmom** [roleoroleo/yi-hack-Allwinner#141]
Can't seem to flash a 9FUSY31 running 8.2.0.0A_202007211802 when I power on the camera it goes from amber to then flashing blue constantly.  What can I do to further troubleshoot?

**Comment by scruff-01** [comment]
Try formatting the 16GB or less SD card in the camera first.

**Comment by noelmom** [comment]
Thanks for the tip, however, that didn't resolve the issue.  I was able to enable telnet and tried running the script but getting a syntax error (screenshot below).  Will try running a previous release.

![image](https://user-images.githubusercontent.com/62074865/92328809-5ea29b00-f031-11ea-945d-3dbe040bccf6.png)

**Comment by scruff-01** [comment]
Have you tried both flashing the tar.gz and flashing with the tar.gz extracted? Maybe try an older version 15 or 16 first

**Comment by noelmom** [comment]
My issue was the SD card...  Purchased a Sandisk 16GB and worked without any issues.  Thanks for the help.

**Comment by scruff-01** [comment]
Ah yes. That seems to be a recurring problem with cams these days.
