### ISSUE TITLE
Hostname is not working

### ISSUE THREAD

**Issue by sermayoral** [roleoroleo/yi-hack-Allwinner#144]
I have provided a hostname, but I can't access the control web using the hostname, nor do I see the device's hostname on the router:

![DHCP Leases](https://user-images.githubusercontent.com/30116095/92478194-1a0a3180-f1e2-11ea-8c29-5a904898ebe5.jpg)

**Comment by roleoroleo** [comment]
Setting the hostname does not imply registering this hostname on the dhcp server.
See here:
https://github.com/roleoroleo/yi-hack-MStar/issues/199

**Comment by sermayoral** [comment]
Thanks @roleoroleo. I thought it was the hostname on the dhcp server. I will try to register it editing the wifidhcp.sh. Thanks
