### ISSUE TITLE
FTP Upload Path

### ISSUE THREAD

**Issue by mpuff** [roleoroleo/yi-hack-Allwinner#145]
Hello,

is it possible to add a upload directory path for ftp upload?

Kind regards

**Comment by roleoroleo** [comment]
See this commit:
https://github.com/roleoroleo/yi-hack-Allwinner/commit/318db69195255cd496360c8e2c480a48064cea7a

**Comment by mpuff** [comment]
I'm looking forward to the next release

**Comment by danielk117** [comment]
@roleoroleo Is there an ETA for the next release?

**Comment by mpuff** [comment]
that would be great with the ftp upload path

**Comment by roleoroleo** [comment]
No ETA at the moment.
I have to find the time to test the new image.

**Comment by danielk117** [comment]
Do you have a built image with the latest changes? I can help you with testing.

**Comment by roleoroleo** [comment]
Yes:
[y20ga_0.2.0.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner/files/5278673/y20ga_0.2.0.tar.gz)
Rename it from tar.gz to .tgz

**Comment by mpuff** [comment]
i have try now to add a FTP-Directory, i have add **/Kamera/yi-home/**, than i click on save and reboot the camera, than the FTP-Directory box is emty.

**Comment by danielk117** [comment]
the new mqtt messages does work. 👍 
what about #150 ?
next i will have a look at the new ftp directory.

**Comment by roleoroleo** [comment]
> if mqtt "AI Human Detection" is enabled, `motion_detection=motion_start` and `ai_human_detection=human_start` or `ai_human_detection=human_stop` doesnt work.
> if mqtt "Baby crying detect" is enabled, `motion_detection=motion_start` and `baby_crying=crying` does work again.

This is a know issue of the yi firmware.

> video recording does not work for me. neither on sd-card nor ftp.
> cloud is disabled. "Recording without Cloud" and "Save video when a motion is detected" are enabled...
> where can i find log files? /var/log is empty...

If "AI Human Detection" is enabled, probably it doesn't work.
Otherwise it must work.

> what about #150 ?

Merged and ready for next release.

**Comment by danielk117** [comment]
I didn‘t know if the human_detection was enabled when ftp fails. 
I will give a new try the next days.

**Comment by mpuff** [comment]
ftp upload is working, but only when i chage i set the path in the system.conf.
FTP_DIR=/Kamera/yi-home

when i set it up in the gui, the FTP_DIR is emty, also in the file.

**Comment by Catfriend1** [comment]
@mpuff please try to clear the browser cache.

**Comment by mpuff** [comment]
thank you for this info, i have now opened it with another browser and the ftp path is in the box.
