### ISSUE TITLE
Camera cannot connect to Wifi

### ISSUE THREAD

**Issue by sermayoral** [roleoroleo/yi-hack-Allwinner#147]
I hope anyone can help me.

My camera was working well, when today, suddently, when i have tried to connect to my camera, it was not connected to Wifi.

After reboot it, the camera still cannot connect to wifi. I had the yi home app disable, so i decided to remove the hack in order to reset the camera to start the process again. When I turn on the camera, it says "waiting to connect", but after following the process, the camera give me a "Wifi password Error" and it cannot connect to Wifi. Credentials are OK. Nothing change, Same AP that works well with the cam a week ago

The last thing i did was https://github.com/roleoroleo/yi-hack-Allwinner/issues/144. Maybe i made a mistake, maybe i have another problem, Im not sure, but a couple of days of changing the hostname, the camera lost the wifi access.

Please, could someone give me an advice of how to proceed to solve this problem? Thanks!!

EDIT: I have observed this logs in the SDCard:

[log_pwd_wrong_file.txt](https://github.com/roleoroleo/yi-hack-Allwinner/files/5221435/log_pwd_wrong_file.txt)
[log_pwd_wrong_log.txt](https://github.com/roleoroleo/yi-hack-Allwinner/files/5221436/log_pwd_wrong_log.txt)
[log_pwd_wrong_lsmod.txt](https://github.com/roleoroleo/yi-hack-Allwinner/files/5221437/log_pwd_wrong_lsmod.txt)
[log_pwd_wrong_ps1.txt](https://github.com/roleoroleo/yi-hack-Allwinner/files/5221438/log_pwd_wrong_ps1.txt)
[log_pwd_wrong_wpa_supplicant.txt](https://github.com/roleoroleo/yi-hack-Allwinner/files/5221439/log_pwd_wrong_wpa_supplicant.txt)
[log_pwd_wrong_df.txt](https://github.com/roleoroleo/yi-hack-Allwinner/files/5221440/log_pwd_wrong_df.txt)

[log_start_reset_file.txt](https://github.com/roleoroleo/yi-hack-Allwinner/files/5221408/log_start_reset_file.txt)
[log_start_reset_log.txt](https://github.com/roleoroleo/yi-hack-Allwinner/files/5221409/log_start_reset_log.txt)
[log_start_reset_lsmod.txt](https://github.com/roleoroleo/yi-hack-Allwinner/files/5221410/log_start_reset_lsmod.txt)
[log_start_reset_ps1.txt](https://github.com/roleoroleo/yi-hack-Allwinner/files/5221411/log_start_reset_ps1.txt)
[log_start_reset_wpa_supplicant.txt](https://github.com/roleoroleo/yi-hack-Allwinner/files/5221415/log_start_reset_wpa_supplicant.txt)
[log_start_reset_df.txt](https://github.com/roleoroleo/yi-hack-Allwinner/files/5221416/log_start_reset_df.txt)

**Comment by roleoroleo** [comment]
Probably there is something wrong in the file:
/home/app/script/wifidhcp.sh 

And actually the unhack procedure doesn't restore the original wifidhcp.sh (because it's not released yet).

**Comment by sermayoral** [comment]
It works @roleoroleo 

Thank you very much :-)
