### ISSUE TITLE
Feature-Request: Setting RTSP Frame Rate 

### ISSUE THREAD

**Issue by jexem** [roleoroleo/yi-hack-Allwinner#149]
It would be really nice to set the frame rate for the rtsp stream. 
If the camera is used with Zoneminder it would be a great feature to save resources and maybe the stream got less artifacts.
Would this be possible? I see some comments in the code section about frame rate, but dont understand the machanism.
Setting from 1 to 25 frames would be fantastic.

Thank you for this fantastic piece of software.

**Comment by roleoroleo** [comment]
Sorry but it's not possible.
The h264 coding is made by the yi software and I cannot change it.
