### ISSUE TITLE
NTP server via web admin interface?

### ISSUE THREAD

**Issue by emeins** [roleoroleo/yi-hack-Allwinner#15]
I like to run my cam without any internet connection. Regarding time service I'd like to use an internal ntp server. I can set this manually in the /home/yi-hack/etc/system.conf
_NTP_SERVER={local ip address}_

Could this be added to the web admin interface for a later version?

**Comment by roleoroleo** [comment]
Ok, I will add it to the next release.

**Comment by crdnl** [comment]
Added in efce19fbf7d84ae055225e8855407534232477ed, closing issue.
