### ISSUE TITLE
Building kernel module for Yi home 1080p camera

### ISSUE THREAD

**Issue by JohCn** [roleoroleo/yi-hack-Allwinner#153]
Hi All,

I am trying to build my own custom kernel module for Yi home 1080p camera (Allwinner version) and having problems with it.

From UART boot logs, I see that the kernel is: OpenWrt Linux-4.9.118
Also running 'cat /proc/version' on the camera throws this -

Linux version 4.9.118 (caizhaolong@XY-201) (gcc version 6.4.1 (OpenWrt/Linaro GCC 6.4-2017.11 2017-11) ) #55 PREEMPT Fri Dec 13 10:12:16 UTC 2019

Based on this I went here and downloaded Linux kernel version 4.9.118 -
https://sources.openwrt.org/

Also, I got the toolchain "lindenis-v536-prebuilt-master" from this (Yi hack Allwinner) project.

I cross compiled above kernel on an Ubuntu machine. 
I first created kernel configs using:
make ARCH="arm" CROSS_COMPILE=/home/user1/lindenis-v536-prebuilt-master/gcc/linux-x86/arm/toolchain-sunxi-musl/toolchain/bin/arm-openwrt-linux-  defconfig

Later I build my custom kernel module against this kernel. When I load it to the camera kernel using insmod, the kernel module causes kernel panic. I have played around with configurations for a week but no luck.

Writing to Yi customer care requesting GPL code has not helped.

My question is has anybody here built the Linux kernel for this camera? Specifically a working kernel module? If yes, could you help me with configurations? 
Any general ideas on generating the correct kernel configurations or building a working kernel module for this camera are also welcome.

Thanks,

**Comment by roleoroleo** [comment]
We miss both kernel sources and .config.
If Yi doesn't release them, I think it's not possible.
