### ISSUE TITLE
Add to YiHome after Yi hack

### ISSUE THREAD

**Issue by colethegamer123** [roleoroleo/yi-hack-Allwinner#154]
Hello Mr.
I have Yi Home 1080p Cameras, one I added to Yi Home and after installed Yi-hack firmware, this can be viewed by Yi Home app and HomeAssistant too but 

the other what I did in the other way and installed firmware first and after tried to add to Yi Home, but I cannot. There is any solution to add to Yi Home AFTER Yi-hack firmware? 

Thank you!

**Comment by ferinelo** [comment]
Have you tried:
- un-hack: https://github.com/roleoroleo/yi-hack-Allwinner/wiki/Remove-the-hack
- add the camera to the app
- hack again?

**Comment by colethegamer123** [comment]
I made many custom settings inside the hack this is why I didnt wanted to rehack. The easiest method from user perspective would be a button what enables QR code scanning for 60 sec for example to scan the code from the app.

**Comment by roleoroleo** [comment]
Swutitch off "Disable cloud" and pair the app.

**Comment by colethegamer123** [comment]
I tried to enable, save, restart, start the app and try to pair. Nothing.

I tried to disable, save, restart, start the app and try to pair.
Nothing.

It should say something but nothing and it should scan tbe QR but nothing happens.

Any Idea or maybe only possible to unhack it and do reset everything? 
( would be bad for me )

Thank you :)

**Comment by roleoroleo** [comment]
After switching off "Disable cloud" reset the cam using the back button.

**Comment by colethegamer123** [comment]
After reseting all my settings will be lost what I changed on the files witth SSH right?

**Comment by roleoroleo** [comment]
It depends on the files you are changed.
The reset operation restore only the default of the yi configuration.

**Comment by colethegamer123** [comment]
In the new updates all things was added what I did manually, so I reseted the camera, added to yihome and online updated the hack firmware. Thank you
