### ISSUE TITLE
NO card detected

### ISSUE THREAD

**Issue by sajikur** [roleoroleo/yi-hack-Allwinner#159]
Hi, on upgrade from 0.1.9 I receive the message "No card detected". Same from 0.1.8 last time. 4 cams, 4 micro sd. 
So I must to reflash new firmware manually. Have you a solution for this problem? Thank you

**Comment by roleoroleo** [comment]
```
    FREE_SD=$(df /tmp/sd/ | grep mmc | awk '{print $4}')
    if [ -z "$FREE_SD" ]; then
        printf "Content-type: text/html\r\n\r\n"
        printf "No SD detected."
        exit
    fi
```
The upgrade procedure can't detect the card.
Please run `df` command and post the output.
