### ISSUE TITLE
Changing the WLAn being used

### ISSUE THREAD

**Issue by zgadgeter** [roleoroleo/yi-hack-Allwinner#16]
Hello, thanks for this wonderful project. I'm wondering though how do I change the wireless network being used by the camera? I need to change the location of the camera and there is a different network there.
thanks.

**Comment by roleoroleo** [comment]
You must use the original Yi app.
1. Enable cloud.
2. Reboot the cam.
3. Reset the cam with the button.
4. Resync with the original app.
