### ISSUE TITLE
MQTT motion msg

### ISSUE THREAD

**Issue by Ant1q** [roleoroleo/yi-hack-Allwinner#161]
Hello! Im using domoticz as home automation server. Domoticz is listening for `domoitcz/in` on mqtt and waiting for something like that
`{"command": "switchlight", "idx": 2450, "switchcmd": "On" }`
but if i try change Motion Message in MQTT tab on webUI to this then after saving i get only `switchlight` saved.
Is it possible generate mqtt messages in json?

**Comment by roleoroleo** [comment]
Sorry, at the moment it's not possible.

**Comment by Ant1q** [comment]
@roleoroleo 
Maybe you can give any advise, how i can solve my case, because domoticz integration from wiki is for controlling camera options, not for receiving events =(
