### ISSUE TITLE
help thanks

### ISSUE THREAD

**Issue by formatta2003** [roleoroleo/yi-hack-Allwinner#164]
Hello. I have a yi 9fusy25fs0 ... the yellow led keeps flashing for 8 hours ... I have tried many times with all 2 files.
where am I wrong ??
thank you

**Comment by roleoroleo** [comment]
What's the yi fw version?

**Comment by formatta2003** [comment]
> 
> 
> What's the yi fw version?

thank you

4.2.0.0h_201909041620
