### ISSUE TITLE
video option on sd AND in ftp

### ISSUE THREAD

**Issue by UlfgarIlFabbro** [roleoroleo/yi-hack-Allwinner#166]
is it possible to add the option to keep the files both on the cam's SD and in FTP without deleting them when they are uploaded to local FTP?

**Comment by roleoroleo** [comment]
Yes, it's possible.
At the moment you can change the parameter inside the file ftppush.sh

**Comment by UlfgarIlFabbro** [comment]
you could add the setting so that you can change it without changing manually the parameter inside the file ftppush.sh?

**Comment by roleoroleo** [comment]
Yes, but at the moment I don't have time to spend on the project.

**Comment by UlfgarIlFabbro** [comment]
Thanks, I post it in the requests so that when possible there is a reminder.
Thanks again
