### ISSUE TITLE
reverse NPU inviting

### ISSUE THREAD

**Issue by Zepan** [roleoroleo/yi-hack-Allwinner#168]
hi, your project is great!
but all hack is in user space, we are now reversing NPU register and driver, to make an opensource AI toolchain, are you interested in it?

**Comment by roleoroleo** [comment]
Yes, I'm interested.
But my know-how about kernel space is not good.

**Comment by Zepan** [comment]
fortunately, the V831's NPU driver is simple cdev, they just mmap register to user space, and you can operate and debug NPU in user space. we have some demo code and reverse some lib, but not work yet.
If you are interested in it, please send email to zepan@sipeed.com, and I will share some NPU data for you
