### ISSUE TITLE
RTSP audio and watermark

### ISSUE THREAD

**Issue by JakobStadlhuber** [roleoroleo/yi-hack-Allwinner#17]
Is there a way to get audio and a timestamp watermark for a RTSP stream?

**Comment by roleoroleo** [comment]
Timestamp only in the snapshot.
Audio if someone is able to extract it from alsa.

**Comment by JakobStadlhuber** [comment]
Would be nice future features if you need some ideas :)

Keep up the good work and thanks you for this project.

**Comment by roleoroleo** [comment]
I copied the @PieVo idea and patched alsalib to duplicate the audio stream on a temporary pipe.
This way I can send the audio stream to the RTSP server.
I am testing the solution because I have encountered the same problems described here:
https://github.com/PieVo/yi-hack-MStar/issues/3

**Comment by KorbinianP** [comment]
Do I understand correctly that I need to decide for the moment if I want Auto or Video? Not both at the same time? Will this change in the future?

**Comment by roleoroleo** [comment]
You can choose video and audio or only video.
Not only audio.

**Comment by KorbinianP** [comment]
OK, tnx for the clarification. After another restart of the camera the Video and Audio both showed up.
