### ISSUE TITLE
Question about Camera Setting on always record?

### ISSUE THREAD

**Issue by chilman408** [roleoroleo/yi-hack-Allwinner#173]
Hello,

I'm not sure what this means under camera settings?

If enabled, video will be saved only when a motion is detected.
If disabled, video will be always saved.
(It takes effect only if recording is enabled)
--

Does this mean if I disable this setting, the camera will record 24/7?  Also where is the setting to enable recording?

**Comment by roleoroleo** [comment]
> Does this mean if I disable this setting, the camera will record 24/7?

Yes, 24/7.

> Also where is the setting to enable recording?

First page.

**Comment by chilman408** [comment]
Thx.  By first page, do you mean the "Recording wihtout Cloud" feature?  What if you have cloud enabled, is it still a 24/7 recording?

**Comment by roleoroleo** [comment]
Yes, 24/7.

**Comment by chilman408** [comment]
thx
