### ISSUE TITLE
i´m stupid ?...

### ISSUE THREAD

**Issue by afrojaner** [roleoroleo/yi-hack-Allwinner#174]
Modell BFUS

FW :8.2.0.0A_202007211802

I Copy y20ga_0.2.0.tgz to my SD card 

i plug it in my camera and start, but nothing happend after 30 seconds the blue light is lightning permanent. 

please help me what should i have to do ...

i want donate something but it does´t work 

![image](https://user-images.githubusercontent.com/63167743/97107104-077e8580-16c6-11eb-91ac-141f5c651213.png)

**Comment by artemy** [comment]
You want to copy the contents of this archive to the SD card, not the archive itself.
No need to call yourself stupid of course.

**Comment by afrojaner** [comment]
omg )= so sorry ... 

it works ... donation for beer is safe
