### ISSUE TITLE
Feature request: Remove YI Logo in lower left corner of video / foto

### ISSUE THREAD

**Issue by dennisheitmann** [roleoroleo/yi-hack-Allwinner#175]
I would like to have an option to disable the "YI" logo / watermark in lower left corner of the video / foto.

Many thanks for the great software,

Dennis

**Comment by roleoroleo** [comment]
See this: https://github.com/roleoroleo/yi-hack-Allwinner/issues/34

**Comment by dennisheitmann** [comment]
Thanks for the link, I used the white image from: https://github.com/roleoroleo/yi-hack-Allwinner/issues/34#issuecomment-629753507
I hope there will be an option to completely remove this watermark soon.

**Comment by roleoroleo** [comment]
I think it will not be possible.
