### ISSUE TITLE
YI outdoor support

### ISSUE THREAD

**Issue by JakobStadlhuber** [roleoroleo/yi-hack-Allwinner#18]
Do you have plans to support the YI outdoor cameras?

**Comment by roleoroleo** [comment]
If based on the same platform  why not.
To start I need a log of the boot.

**Comment by JakobStadlhuber** [comment]
> If based on the same platform why not.
> To start I need a log of the boot.

At the moment i do not have an Yi outdoor because your projects don't support it. Maybe someone else can help.

**Comment by JakobStadlhuber** [comment]
You also implemented the feature for the yi dome to pan the camera, but only the Yi 1080p Home are listed as supported cameras, which haven't a pan feature, is it possible to flash a YI dome camera?

**Comment by roleoroleo** [comment]
No.
This fw derives from MStar which is availabe for dome models too.
I didn't remove the code.

**Comment by bytesex** [comment]
Hi! I have a "Yi Outdoor Camera 1080P" model YHS.3017
Current firmware version 3.0.0.0D_201809111054
Looks very solid and sturdy. I was going to make a dump from it, but it looks non-separable.
Are there chances of success if try to upload the firmware on it?

![photo_2020-05-03_15-42-21](https://user-images.githubusercontent.com/63019342/80914524-bf088f80-8d54-11ea-97d4-7d82f15c8bff.jpg)
![photo_2020-05-03_15-42-24](https://user-images.githubusercontent.com/63019342/80914526-c039bc80-8d54-11ea-8b42-7c26255d3799.jpg)
![photo_2020-05-03_15-42-27](https://user-images.githubusercontent.com/63019342/80914527-c039bc80-8d54-11ea-87ea-5739211d5512.jpg)

**Comment by roleoroleo** [comment]
Before to try the hack we need to know which platform is.

**Comment by bytesex** [comment]
It seems https://github.com/TheCrypt0/yi-hack-v4 worked for this :)
it seems thats a Hi3518e

**Comment by JakobStadlhuber** [comment]
> well https://github.com/TheCrypt0/yi-hack-v4 worked for this :)
> it seems thats a Hi3518e

But you will have to pay/support for RTSP support. And the RTSP implementation is also not open source.

**Comment by crdnl** [comment]
Considering the fact that it's covered by the yi-hack-v4 project, it's non applicable to this. If you want the license for that other project, go donate.

**Comment by matteopiccioni** [comment]
The main problem with TheCritpt0 firmware is the miss mqtt and webservices support
I hope you will support YI outdoor too :)

**Comment by roleoroleo** [comment]
The problem is not indoor or outdoor but the platform.

Hisilicon?
MStar?
Allwinner?

**Comment by UlfgarIlFabbro** [comment]
> 
> 
> The problem is not indoor or outdoor but the platform.
> 
> Hisilicon?
> MStar?
> Allwinner?

how do i see which platform the cam is using
