### ISSUE TITLE
BFUS - Onvif black screen until view rtsp

### ISSUE THREAD

**Issue by casacsm** [roleoroleo/yi-hack-Allwinner#186]
Hello.

Thank you so much for your work.

I note that my onvif dvr have black screen for camera, until I open 
at least one time vlc on pc and enter via rtsp.
After that onvif video was perfect!
Why? Can you help, please?

I cannot start - every time I reboot the camera - vlc on pc to activate onvif stream!!! ;)

My model is YI1080p home camera - YY.2016 - fw 8.2.0.* - hack y20ga ver. 0.2.1

**Comment by roleoroleo** [comment]
Onvif is only a protocol descriptor.
When the cam provides the stream it uses rtsp.
So, if it works with vlc, the problem is probably the rtsp client on your dvr.

**Comment by casacsm** [comment]
Thank you for your reply.

My dvr works with 4 different cameras using onvif protocol.
Now I want to add the yi camera.

I try to use rtsp on dvr to connect the yi camera, but I obtain black screen every time.

If I use onvif protocol on dvr, I obtain black screen. 
As soon as I connect to yi camera using rtsp on vlc, I see image on dvr.
I don't understand why.

**Comment by roleoroleo** [comment]
What model is your dvr?
