### ISSUE TITLE
Motion_detection_image topic suffix: no messages

### ISSUE THREAD

**Issue by Giulianini** [roleoroleo/yi-hack-Allwinner#187]
When I subscribe to the topic: "yicam-1/motion_detection_image" no message is sent.
If I subscribe to the topic:  "yicam-1/motion_detection" start and stop message are sent.

**Comment by roleoroleo** [comment]
Are you using the last version?
Do you have human detection enabled?
I tested again now and it works.

**Comment by Giulianini** [comment]
Yes I'm using the latest version. I tested it with human detection enabled and disabled and I listen to all topics looking for the message but no message containing the image is present: only motion_start/stop online are printed. I will investigate more and see if a message containing the image will arrive. Thanks for the quick response @roleoroleo

**Comment by roleoroleo** [comment]
I'm using this command with mosquitto:
`mosquitto_sub -v -h 127.0.0.1 -t home-assistant/yi-cam/#`

**Comment by Giulianini** [comment]
<img width="1028" alt="Schermata 2020-11-08 alle 13 53 55" src="https://user-images.githubusercontent.com/39558398/98465548-ee97c900-21c9-11eb-9c66-c9983d3392cf.png">

Logging with MQTT-FX is working. In my application I'm using Paho-Mqtt python library. I will investigate why it doesn't receive the message.

**Comment by Giulianini** [comment]
I close the issue because now is working in Paho-mqtt.
