### ISSUE TITLE
FTP Delete (after upload) - NOT WORKING

### ISSUE THREAD

**Issue by cej0t4** [roleoroleo/yi-hack-Allwinner#188]
In version 0.2.0 the deletion of videos worked perfectly ... since 0.2.1 it does not delete the videos when uploading them to FTP.

**Comment by roleoroleo** [comment]
Did you add the option in the web page?

**Comment by cej0t4** [comment]
Yes, select the option in motion events. I have returned to 0.2.0 and everything works as before.

**Comment by roleoroleo** [comment]
This is the only commit involving ftppush.sh:
https://github.com/roleoroleo/yi-hack-Allwinner/commit/282ec309f96a29e50b47be397cd1d508961e8ecb

**Comment by cej0t4** [comment]
If you can try it with your hand with a camera ... in my two cameras the deletion of videos does not work after sending it by FTP

**Comment by divadiow** [comment]
Same here :(

I've turned the feature on and off and rebooted several times.
I've yet to reset the cam to test

**Comment by roleoroleo** [comment]
Fixed: https://github.com/roleoroleo/yi-hack-Allwinner/commit/7b590f02f02c635469f94b3a00789a803f9e0ecc
Try the new ftppush.sh

**Comment by divadiow** [comment]
Thank you! I will try when I get the compiling prerequisites sorted.

**Comment by isbkch** [comment]
Had the same issue. Tried the suggested commit and confirm it's working now
