### ISSUE TITLE
FTP upload and encryption

### ISSUE THREAD

**Issue by gauthier12** [roleoroleo/yi-hack-Allwinner#190]
Hi, 
I'm trying to use the FTP upload option but it doesn't work.
I tried to login and test directly the ftpput command from ssh 
ftpput --username yicam --password ****** 192.168.0.253 /tmp/sd/record/2020Y11M17D08H/11M00S60.mp4
and I get the following error :
 ftpput: unexpected server response to USER: 530 Non-anonymous sessions must use encryption.

Indeed, for security reason, only encrypted sessions are authorized and I would prefer not lower the security of the server for the camera.
Do you have any idea how to enable encrypted FTP upload ?
Cheers
Gauthier

**Comment by roleoroleo** [comment]
Probably we should use FTPS but ftpput doesn't support it.
