### ISSUE TITLE
Feature request: zerotier support

### ISSUE THREAD

**Issue by nielscil** [roleoroleo/yi-hack-Allwinner#192]
Hi, would it be possible to add zerotier support for the cam(s)? I would like to use an external placed (other network and location) yi home camera in my synology surveillance station.

**Comment by roleoroleo** [comment]
I don't know zerotier but if you want to try i compiled it.
[zerotier.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner/files/5579696/zerotier.tar.gz)

**Comment by nielscil** [comment]
Thank you, I've tried the package you provided.  I've got the following error message when running:

` ERROR: unable to configure virtual network port: could not open TUN/TAP device: No such file or directory`

I think that tun isn't enabled/intergrated on the Yi home cam's, am I right? Would it be posssible to add tun?

**Comment by roleoroleo** [comment]
If I'm not wrong, tun/tap device is a kernel feature and it's not available in yi cam.
Unfortunately we cannot build a new kernel.

**Comment by nielscil** [comment]
Yeah, I believe it is a kernel module. It isn't possible to compile the kernel module and just enabling it?

**Comment by roleoroleo** [comment]
I could try to build it but without a .config probably it doesn't work.

**Comment by roleoroleo** [comment]
No luck, I build it but when I insmod the module the cam goes in kernel panic.

**Comment by nielscil** [comment]
Alright, tnx for trying!
