### ISSUE TITLE
Feature request: Nightvision toggle

### ISSUE THREAD

**Issue by okuzlu** [roleoroleo/yi-hack-Allwinner#194]
Is it possible to toggle the nightvision on a custom time to activate / disable it?

Reason it, that sensitivity is too high and it always changes from nightvision to normal and back so when the room is getting a little dark it makes a annoying "click" sound.

**Comment by roleoroleo** [comment]
You can only switch off ir leds.

**Comment by EvgenPavlyuchek** [comment]
i thought if switch off ir leds then it must be in daynormal  but it continue change and do "click" sound
switch off ir leds dont work ?

**Comment by roleoroleo** [comment]
Try using yi app and check if it works.

**Comment by okuzlu** [comment]
I can confirm. I disabled ir led in yi app but it still make the "click" sound

**Comment by tachyon142** [comment]
The click occurs when the camera engages or disengages the IR cut filter built into the lens housing. You can eliminate the clicking noise by electrically disabling this toggle. To do this, open the case, and carefully unplug the 2-pin connector which connects the lens housing to the pcb.

Note that the camera will still shift to black and white mode when it decides the environment is too dark for color, and may be less willing to switch back to color mode than before.

If a software enhancement is developed for this, individual control of the filter and B&W processing in ffmpeg would be ideal, but it is my understanding that changes from the default ffmpeg parameters isn't possible.

Regards
