### ISSUE TITLE
Yi 1080p Home 9FUS FTP upload problem

### ISSUE THREAD

**Issue by WInetu007** [roleoroleo/yi-hack-Allwinner#196]
I try to upload motion video to FTP server. I have written coretly FTP configuration in Motion Events Sheet and nothing happends, the video is still only on camera sd card

**Comment by Catfriend1** [comment]
Did you restart the camera to apply the new settings?

**Comment by WInetu007** [comment]
Yes of course

**Comment by roleoroleo** [comment]
Try to run the command manually.
1. Login with ssh.
2. Source the env: `. /home/yi-hack/script/env.sh`
3. Start fttpush `/home/yi-hack/script/ftppush.sh start`

And check the output.
