### ISSUE TITLE
Feature Request: Auto Reboot

### ISSUE THREAD

**Issue by cyraxnet** [roleoroleo/yi-hack-Allwinner#197]
It would be useful to add an auto-reboot option, such that you can set the camera to restart itself at a scheduled time.
This, to clear any memory leaks or connection issues with external devices, like an NVR.

I'm a part time OO-dev so if I can, I will try to implement it myself, but it might be a quick feature for someone already working with the project.

**Comment by roleoroleo** [comment]
The last version contains crontab.
You can schedule reboot command.

**Comment by cyraxnet** [comment]
For anyone that comes across this and needs the same, syntax is
`* * * * *  /sbin/reboot`

Obviously with the desired crontab schedule for preceding characters to /sbin/reboot
