### ISSUE TITLE
Baby crying detection is not working

### ISSUE THREAD

**Issue by berzezo** [roleoroleo/yi-hack-Allwinner#198]
Hello,

I wanted to use baby crying detection with MQTT and Hassio.
Motion detection is working fine with the configuration.

Firmware Version | 0.2.1
Base Version | 8.2.0.0A_202007211802
Model Suffix | y20ga
Serial Number | BFUSY31GUV...
Local Time | Fri Nov 27 20:37:47 CET 2020
Uptime | 0h 19m 54s
Load Average | 1.51 1.17 0.78
Free/Total Memory | 26440/61164 KB
Free SD Space | 100%

Do you have any idea what can be the problem?

Thank you in advance.

**Comment by WInetu007** [comment]
> Hello,
> 
> I wanted to use baby crying detection with MQTT and Hassio.
> Motion detection is working fine with the configuration.
> 
> Firmware Version | 0.2.1
> Base Version | 8.2.0.0A_202007211802
> Model Suffix | y20ga
> Serial Number | BFUSY31GUV...
> Local Time | Fri Nov 27 20:37:47 CET 2020
> Uptime | 0h 19m 54s
> Load Average | 1.51 1.17 0.78
> Free/Total Memory | 26440/61164 KB
> Free SD Space | 100%
> 
> Do you have any idea what can be the problem?
> 
> Thank you in advance.

Can You show me your configuration Motion detection in configuration.yaml and in camera motion events tab?
I try do this but this but binary_sensor.yihack_v4_motion_sensor is always off

**Comment by berzezo** [comment]
Hello,

Hassio config:


binary_sensor:
    - platform: mqtt
      name: "Kamera mozgás Luca"
      state_topic: "babycam_luca/motion_detection"
      payload_on: "ON"
      payload_off: "OFF"
      availability:
       - topic: "babycam_luca/status"
         payload_available: "ONLINE"
         payload_not_available: "OFFLINE"
      qos: 1
      device_class: motion

![130301458_753818711876175_5680415908627872646_n](https://user-images.githubusercontent.com/60827325/101343633-94e7f480-3884-11eb-8dd8-5eb606d375cd.jpg)
![130408991_774171523174811_6339684377783860979_n](https://user-images.githubusercontent.com/60827325/101343635-96192180-3884-11eb-996f-1b3392ee1234.jpg)

**Comment by berzezo** [comment]
Hi @roleoroleo ,

Do you have any idea what can be the problem with baby crying detection?
Thanks in advance.

**Comment by roleoroleo** [comment]
No, I need to investigate.

**Comment by roleoroleo** [comment]
Baby crying option disapperead from yi app.
Maybe yi removed this feature?

**Comment by roleoroleo** [comment]
The last software changes the baby crying feature. Now it's a sound detection.
Ipc codes are changed also.
I will update the code.

**Comment by berzezo** [comment]
Thanks for your work.

**Comment by roleoroleo** [comment]
I updated the code.
Next release...

**Comment by berzezo** [comment]
Sorry but, still not working.
