### ISSUE TITLE
y25ga (releases 0.2.1 and 0.2.2) Snapshot script crashes camera

### ISSUE THREAD

**Issue by 74ls04** [roleoroleo/yi-hack-Allwinner#206]
![image](https://user-images.githubusercontent.com/1887003/101269043-3150b080-3738-11eb-8b31-9430e553d260.png)

**Replicated on Release 0.2.1 and 0.2.2**

It seems that the snapshot script crashes the camera. I first observed this when setting up MQTT on Release 0.2.2 -- I noticed it crashed right after sending a motion event. I checked the configuration and noticed that one of the MQTT fields sends a raw jpeg image, which isn't present on my y20ga cameras, and that pointed me to the true issue. I flashed Release 0.2.1 and observed the same issue. 

Steps to replicate (method 1):
- Visit the snapshot url http://#.#.#.#:8080/cgi-bin/snapshot.sh?res=high&watermark=yes
- Refresh the browser to call script again
- The camera crashes

Steps to replicate (method 2):
- Configure MQTT motion event
- Trigger motion event
- The event gets sent but camera crashes

I looked in the sd/logs directory but didn't see anything related -- not sure if that's where to look for logs.

**Comment by 74ls04** [comment]
I was able to get it to crash by calling the imggrabber program directly. In the screenshot below I called it three times in a row and it crashed after the third call. 

![image](https://user-images.githubusercontent.com/1887003/101269596-855e9380-373e-11eb-9f0f-7d9eafecbbed.png)

**Comment by roleoroleo** [comment]
https://github.com/roleoroleo/yi-hack-Allwinner/issues/5

**Comment by 74ls04** [comment]
Thanks, not sure how I missed that! Enabling swap does stop the crashing. Looks like this newer camera firmware uses up a few more resources.
