### ISSUE TITLE
0.2.2 via online upgrade - crontab not present.

### ISSUE THREAD

**Issue by flixxx** [roleoroleo/yi-hack-Allwinner#208]
Did an online update from 0.2.1 to 0.2.2 - crontab not present.

I check in /home/yi-hack/sbin/ <--- crontab not present.

**Comment by roleoroleo** [comment]
Check in /home/yi-hack/usr/bin

**Comment by flixxx** [comment]
good, I see it there. Command is not found though - is there a special requirement to activate it, install it, etc..?

**Comment by flixxx** [comment]
nevermind ./busybox crontab works

**Comment by flixxx** [comment]
./busybox crontab enables crontab
