### ISSUE TITLE
crontab can't change to director /crontabs

### ISSUE THREAD

**Issue by flixxx** [roleoroleo/yi-hack-Allwinner#209]
crontab -e invoked the following error;

crontab: can't change directory to '/crontabs': No such file or directory
unable to manually create it as it's expecting it at the root

**Comment by roleoroleo** [comment]
You don't need to use crontab command.
Simply use the web interface to fill your crontab file.

But if you want to use crontab, add -c option:
`crontab -l -c /var/spool/cron/crontabs`
