### ISSUE TITLE
RTSP performance

### ISSUE THREAD

**Issue by alexmc1510** [roleoroleo/yi-hack-Allwinner#21]
After configuration, enabling only ONVIF and RTSP (both with low Q) I loose camera connection randomly and camera reboots also from time to time. It seems a lack of performance. Are you aware about it? Do your know what can be done to improve it?

**Comment by roleoroleo** [comment]
Cloud is enabled? Because cloud wastes a lot of memory.
If cloud is disabled and you choose only low quality, it's not a memory/cpu problem.
There is probably another problem.
Wait for the next release, I made a lot of changes on RTSP.

**Comment by alexmc1510** [comment]
Yes, cloud is disabled.

**Comment by crdnl** [comment]
@alexmc1510 

Can you provide some additional context on this issue:
- Camera Model
- yi-hack Version:
- Camera Version:

Can you export your settings from the web UI or give a quick overview of any changes that you've made?

**Comment by crdnl** [comment]
Closing without response from issue filer for >14 days.
