### ISSUE TITLE
9CUSY Firmware available?

### ISSUE THREAD

**Issue by lordmathew** [roleoroleo/yi-hack-Allwinner#210]
Hello,
My camera has the serial started with 9CUSY. 
I've try all the firmwares and none of them works.
Is there any alternative or do i need to wait for a new firmare release?

TIA,
Nuno

**Comment by roleoroleo** [comment]
The serial is not enough to know if there is an hack.
Firmware version?
Home, dome, ,...?

**Comment by lordmathew** [comment]
Sorry.
Outdoor 1080p
Model: YHS.3017
Serial: 9CUSY36MGW
FW: 3.0.0D_201809111054
Thx

**Comment by roleoroleo** [comment]
Your cam is not supported from my hack: MStar, Allwinner and Allwinner-v2.
And I don't know what platform it's based on.

**Comment by lordmathew** [comment]
How can i help to identify the platform based on?
Pictures from the camera:  
https://prnt.sc/vyw74w
https://prnt.sc/vyw9mb

**Comment by roleoroleo** [comment]
I need a picture of the internal board.
