### ISSUE TITLE
0.2.2 y20ga rtsp on ha - delay about 4-5 sec

### ISSUE THREAD

**Issue by EvgenPavlyuchek** [roleoroleo/yi-hack-Allwinner#217]
0.2.2 y20ga rtsp on ha - delay about 4-5 sec
is it normal ?

ps in yi home app - less 1 sec
disabled ftp and onvif

**Comment by roleoroleo** [comment]
yi app doesn't use rtsp to send the stream.
It is h264 encoded but within a proprietary protocol.
Normally delay is about 2 seconds.
