### ISSUE TITLE
When using the UI to reboot a Camera, it redirects before shutdown

### ISSUE THREAD

**Issue by crdnl** [roleoroleo/yi-hack-Allwinner#22]
Camera: 9FUS Allwinner
Hack Version: 0.1.4

When using the UI to reboot the camera, the UI retries the connection before the webserver has successfully shutdown, leading it to redirect and it to drop the connection.

Maybe we can wait 10s, or some other defined value that we know, to wait before checking.

**Comment by roleoroleo** [comment]
Fixed here: https://github.com/roleoroleo/yi-hack-Allwinner/commit/094ab86902162d8bda9d654384f9cdaeab8730ae
