### ISSUE TITLE
Feature Request: week scheduler for motion event 

### ISSUE THREAD

**Issue by antlomb** [roleoroleo/yi-hack-Allwinner#224]
First of all thank a lot for all the work on this alternative firmware. Functionalities are awesome!
That said, it would be great if it were possible to configure when (what day of the week and what time of day) activate the motion detection, in a way similar to what Synology surveillance station is doing. So, for example, it would be possible to record movements only at night or during the weekend. Same functionalities for http messages.
What do you think ?

**Comment by roleoroleo** [comment]
Sorry but I don't know what command is needed to enable/disable motion detection.
I tried several times to sniff the system but no luck.
