### ISSUE TITLE
Install yi new with yi app?

### ISSUE THREAD

**Issue by pinguinpfleger** [roleoroleo/yi-hack-Allwinner#226]
Cam: Yi 1080p Home 9FUS
Installed FW 8.2.0.0A_202007211802 
with yi-hack: y20ga_0.2.2

Yi App suggest to install 
new ver 8.2.0.0A_202012041528

Is it safe to update? 
Do I need to reinstall yi-hack?

**Comment by roleoroleo** [comment]
I installed the new version and it works.
It's safe but it's better to uninstall the hack, upgrade and reinstall the hack.

**Comment by mykolal** [comment]
I wasn't able to upgrade the base firmware w/o uninstalling the hack.

**Comment by Draggon** [comment]
How to uninstall hack? ;)
Without SD card it's still there.

**Comment by roleoroleo** [comment]
See the wiki.

**Comment by Draggon** [comment]
Lol - as the first page of wiki is almost empty i though is dead missing right menu.
Thanks :)

**Comment by roleoroleo** [comment]
?!?
