### ISSUE TITLE
new 8.2.0.0A_202012041528 firmware for BFUSY31

### ISSUE THREAD

**Issue by divadiow** [roleoroleo/yi-hack-Allwinner#227]
as with the previous update, I've had to remove yihack first, update to the new version and then re-apply yihack.

![image](https://user-images.githubusercontent.com/62958974/103943909-ce817900-512a-11eb-92cf-b4b8c40bfcae.png)

All seems OK, though I've not tested anything.

The app says the changes are "fix and optimisation on several features"

**Comment by divadiow** [comment]
oh. there's this https://github.com/roleoroleo/yi-hack-Allwinner/issues/226

the post title didn't make it obvious

**Comment by MB-Finski** [comment]
Tested FTP, RTSP, MQTT, ONVIF. Sound detection and motion detection ok. Everything working as before.
