### ISSUE TITLE
MQTT: missing START/STOP messages for ai human detection

### ISSUE THREAD

**Issue by MB-Finski** [roleoroleo/yi-hack-Allwinner#231]
Yi-hack ver: 0.2.2
Platform: BFUSY31xxxxxxxxxxxxx
Firmware: 8.2.0.0A_202012041528 (also had the issue with the factory supplied firmware)
SD-card: Samsung SDXC Evo+ 64gb

Issue description:

~90% of the time only "human_stop" is published when motion is detected. Moreover, it is published immediately when detecting motion, before a recording has been completed. "human_start" is published only randomly and even then it's not usually followed by "human_stop". Therefore, it's difficult to write a usable sensor intergration or an automation for homeassistant using MQTT.

**Comment by roleoroleo** [comment]
See this issue: https://github.com/roleoroleo/yi-hack-Allwinner/issues/89
