### ISSUE TITLE
reboot after clicking snapshot url

### ISSUE THREAD

**Issue by mk386** [roleoroleo/yi-hack-Allwinner#232]
> # cat /proc/kmsg
> <4>[    1.830323] jffs2: Empty flash at 0x005bdffc ends at 0x005be000
> <5>[    1.830330] jffs2: CLEANMARKER node found at 0x005be000, not first node in block (0x005b0000)
> <4>[    1.830850] jffs2: Empty flash at 0x005beffc ends at 0x005bf000
> <5>[    1.830857] jffs2: CLEANMARKER node found at 0x005bf000, not first node in block (0x005b0000)
> <4>[    1.832007] jffs2: Empty flash at 0x005c0ffc ends at 0x005c1000
> <5>[    1.832015] jffs2: CLEANMARKER node found at 0x005c1000, not first node in block (0x005c0000)
> <4>[    1.832557] jffs2: Empty flash at 0x005c1ffc ends at 0x005c2000
> <5>[    1.832564] jffs2: CLEANMARKER node found at 0x005c2000, not first node in block (0x005c0000)
> <4>[    1.833094] jffs2: Empty flash at 0x005c2ffc ends at 0x005c3000
> <5>[    1.833102] jffs2: CLEANMARKER node found at 0x005c3000, not first node in block (0x005c0000)
> <4>[    1.833625] jffs2: Empty flash at 0x005c3ffc ends at 0x005c4000
> <5>[    1.833632] jffs2: CLEANMARKER node found at 0x005c4000, not first node in block (0x005c0000)
> <4>[    1.834160] jffs2: Empty flash at 0x005c4ffc ends at 0x005c5000
> <5>[    1.834168] jffs2: CLEANMARKER node found at 0x005c5000, not first node in block (0x005c0000)
> <5>[    1.834690] jffs2: CLEANMARKER node found at 0x005c6000, not first node in block (0x005c0000)
> <4>[    1.835209] jffs2: Empty flash at 0x005c6ffc ends at 0x005c7000
> <5>[    1.835216] jffs2: CLEANMARKER node found at 0x005c7000, not first node in block (0x005c0000)
> <4>[    1.835743] jffs2: Empty flash at 0x005c7ffc ends at 0x005c8000
> <5>[    1.835751] jffs2: CLEANMARKER node found at 0x005c8000, not first node in block (0x005c0000)
> <4>[    1.836269] jffs2: Empty flash at 0x005c8ffc ends at 0x005c9000
> <5>[    1.836276] jffs2: CLEANMARKER node found at 0x005c9000, not first node in block (0x005c0000)
> <4>[    1.836803] jffs2: Empty flash at 0x005c9ffc ends at 0x005ca000
> <5>[    1.836810] jffs2: CLEANMARKER node found at 0x005ca000, not first node in block (0x005c0000)
> <4>[    1.837340] jffs2: Empty flash at 0x005caffc ends at 0x005cb000
> <5>[    1.837347] jffs2: CLEANMARKER node found at 0x005cb000, not first node in block (0x005c0000)
> <4>[    1.837866] jffs2: Empty flash at 0x005cbffc ends at 0x005cc000
> <5>[    1.837873] jffs2: CLEANMARKER node found at 0x005cc000, not first node in block (0x005c0000)
> <4>[    1.838396] jffs2: Empty flash at 0x005ccffc ends at 0x005cd000
> <5>[    1.838403] jffs2: CLEANMARKER node found at 0x005cd000, not first node in block (0x005c0000)
> <4>[    1.838929] jffs2: Empty flash at 0x005cd17c ends at 0x005ce000
> <4>[    3.521252] FAT-fs (mmcblk0p1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
> <5>[    3.582149] random: crng init done
> <4>[    3.758194] FAT-fs (mmcblk0p1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
> <4>[    3.780747] snd_soc_sunxi: loading out-of-tree module taints kernel.
> <3>[    3.796191] --->sunxi_daudio_dev_probe<--- strat.
> <4>[    3.805609] sunxi-daudio daudio0: regulator missing or invalid
> <3>[    3.805758] --->sunxi_daudio_dev_probe<--- end.
> <6>[    3.828834] digital_vol:0, lineout_vol:31, main_gain:23, pa_msleep:160, pa_level:1
> <6>[    3.828850] adcdrc_cfg:0, adchpf_cfg:1, dacdrc_cfg:1, dachpf:0
> <4>[    3.828932] sunxi-internal-codec codec: [sunxi_internal_codec_probe] codec probe finished.
> <4>[    3.838956] [sunxi_card_init] card init finished.
> <6>[    3.839296] sunxi-codec-machine sndcodec: sun8iw19codec <-> codec mapping ok
> <4>[    3.921945] sunxi-codec-machine sndcodec: [sunxi_card_dev_probe] register card finished.
> <6>[    3.932403] snddaudio snddaudio0: codec: snd-soc-dummy, codec_dai: snd-soc-dummy-dai.
> <6>[    3.932862] snddaudio snddaudio0: snd-soc-dummy-dai <-> daudio0 mapping ok
> <4>[    3.996352] [sensor_power_warn] sensor_power_probe: cannot get sensor0_iovdd supply, setting it to NULL!
> <4>[    3.996368] [sensor_power_warn] sensor_power_probe: cannot get sensor0_avdd supply, setting it to NULL!
> <4>[    3.996378] [sensor_power_warn] sensor_power_probe: cannot get sensor0_dvdd supply, setting it to NULL!
> <6>[    4.340118] sunxi-wlan wlan: bus_index: 1
> <6>[    4.450468] sunxi-mmc sdc1: sdc set ios:clk 0Hz bm PP pm UP vdd 21 width 1 timing LEGACY(SDR12) dt B
> <6>[    4.469052] sunxi-mmc sdc1: sdc set ios:clk 400000Hz bm PP pm ON vdd 21 width 1 timing LEGACY(SDR12) dt B
> <6>[    4.489734] sunxi-mmc sdc1: sdc set ios:clk 400000Hz bm PP pm ON vdd 21 width 1 timing LEGACY(SDR12) dt B
> <6>[    4.492189] sunxi-mmc sdc1: sdc set ios:clk 400000Hz bm PP pm ON vdd 21 width 1 timing LEGACY(SDR12) dt B
> <3>[    4.494061] sunxi-mmc sdc1: smc 1 p1 err, cmd 8, RTO !!
> <4>[    4.500301] sunxi-mmc sdc1: card claims to support voltages below defined range
> <6>[    4.509973] sunxi-mmc sdc1: sdc set ios:clk 400000Hz bm PP pm ON vdd 21 width 1 timing SD-HS(SDR25) dt B
> <6>[    4.510069] sunxi-mmc sdc1: sdc set ios:clk 50000000Hz bm PP pm ON vdd 21 width 1 timing SD-HS(SDR25) dt B
> <6>[    4.510231] sunxi-mmc sdc1: sdc set ios:clk 50000000Hz bm PP pm ON vdd 21 width 4 timing SD-HS(SDR25) dt B
> <6>[    4.511073] mmc1: new high speed SDIO card at address 0001
> <4>[    6.110239]
> <4>[    6.110239] [CPLD_PERIPH] cpld_init ok, [ ver=Dec 27 2019, 17:08:21 ]
> <4>[    6.110681] [CPLD_PERIPH] pwm init ok.
> <4>[    6.110692] [CPLD_PERIPH] timer init ok.
> <6>[    6.110697] timer resolution:4 MHZ
> <4>[    6.110701] [CPLD_PERIPH] HZ = 250
> <4>[    8.809535] [sensor_power_warn] sensor_power_probe: cannot get sensor0_iovdd supply, setting it to NULL!
> <4>[    8.809552] [sensor_power_warn] sensor_power_probe: cannot get sensor0_avdd supply, setting it to NULL!
> <4>[    8.809562] [sensor_power_warn] sensor_power_probe: cannot get sensor0_dvdd supply, setting it to NULL!
> <4>[    9.133221] cedar_ve: VE real_fre=300000000
> <4>[    9.341677] snddaudio snddaudio0: codec_dai set sysclk failed
> <4>[    9.341689] snddaudio snddaudio0: codec_dai set set_pll failed.
> <4>[    9.341697] snddaudio snddaudio0: codec dai set fmt failed
> <4>[    9.341719] snddaudio snddaudio0: codec_dai set clkdiv failed
> <4>[    9.417934] s_fmt set width = 1936, height = 1096
> <4>[    9.513132] into set sensor hfilp the value:0
> <6>[    9.515153] [VIN]sensor_flip_option:isp0 reset!!!
> <4>[    9.515478] into set sensor hfilp the value:0
> <6>[    9.517157] [VIN]sensor_flip_option:isp0 reset!!!
> <4>[    9.526132] cedar_ve: VE real_fre=300000000
> <4>[    9.528194] cedar_ve: VE real_fre=300000000
> <4>[    9.544001] cedar_ve: VE real_fre=300000000
> <4>[    9.672496] [CPLD_PERIPH] Timer closed.
> <4>[    9.672508] [CPLD_PERIPH] Timer opened.
> <4>[   17.663023] [CPLD_PERIPH] Timer closed.
> <4>[   18.580264] cedar_ve: VE real_fre=300000000
> <4>[   18.610639] cedar_ve: VE real_fre=300000000
> <4>[   18.947805] cedar_ve: VE real_fre=300000000
> <4>[   18.953775] cedar_ve: VE real_fre=300000000
> <4>[   19.449935] snddaudio snddaudio0: codec_dai set sysclk failed
> <4>[   19.449950] snddaudio snddaudio0: codec_dai set set_pll failed.
> <4>[   19.449959] snddaudio snddaudio0: codec dai set fmt failed
> <4>[   19.449984] snddaudio snddaudio0: codec_dai set clkdiv failed
> <4>[   20.229852]
> <4>[   20.229852] [PID_LIST] pid_list_init ok, [ ver=Dec 27 2019, 17:08:18 ]
> <4>[ 7659.206930] rRTSPServer invoked oom-killer: gfp_mask=0x24201ca(GFP_HIGHUSER_MOVABLE|__GFP_COLD), nodemask=0, order=0, oom_score_adj=0
> <4>[ 7659.206951] CPU: 0 PID: 1416 Comm: rRTSPServer Tainted: G           O    4.9.118 #58
> <4>[ 7659.206956] Hardware name: sun8iw19
> <4>[ 7659.206994] [<c00118cd>] (unwind_backtrace) from [<c000fdeb>] (show_stack+0xb/0xc)
> <4>[ 7659.207015] [<c000fdeb>] (show_stack) from [<c007db35>] (dump_header.constprop.4+0x45/0x134)
> <4>[ 7659.207035] [<c007db35>] (dump_header.constprop.4) from [<c0055059>] (oom_kill_process+0xa1/0x370)
> <4>[ 7659.207052] [<c0055059>] (oom_kill_process) from [<c005560d>] (out_of_memory+0x201/0x284)
> <4>[ 7659.207068] [<c005560d>] (out_of_memory) from [<c0057cff>] (__alloc_pages_nodemask+0x4c3/0x644)
> <4>[ 7659.207084] [<c0057cff>] (__alloc_pages_nodemask) from [<c0054133>] (filemap_fault+0x2a5/0x426)
> <4>[ 7659.207101] [<c0054133>] (filemap_fault) from [<c0069d95>] (__do_fault+0x39/0xa8)
> <4>[ 7659.207117] [<c0069d95>] (__do_fault) from [<c006c665>] (handle_mm_fault+0x2e1/0x7a0)
> <4>[ 7659.207135] [<c006c665>] (handle_mm_fault) from [<c00141ed>] (do_page_fault+0x171/0x20c)
> <4>[ 7659.207149] [<c00141ed>] (do_page_fault) from [<c0009275>] (do_PrefetchAbort+0x25/0x60)
> <4>[ 7659.207162] [<c0009275>] (do_PrefetchAbort) from [<c0010abb>] (__pabt_usr+0x5b/0x5c)
> <4>[ 7659.207168] Exception stack(0xc3747fb0 to 0xc3747ff8)
> <4>[ 7659.207177] 7fa0:                                     00000000 b6d37c98 00000000 00000000
> <4>[ 7659.207189] 7fc0: b6c5a665 000071f9 00000000 000738e4 b6b6d000 b6c5b4e4 00000000 00000168
> <4>[ 7659.207199] 7fe0: b6d37c58 b6d37c80 b6ee245c b6ee6b1c 60000010 ffffffff
> <4>[ 7659.207203] Mem-Info:
> <4>[ 7659.207225] active_anon:4331 inactive_anon:462 isolated_anon:0
> <4>[ 7659.207225]  active_file:21 inactive_file:25 isolated_file:17
> <4>[ 7659.207225]  unevictable:0 dirty:0 writeback:0 unstable:0
> <4>[ 7659.207225]  slab_reclaimable:214 slab_unreclaimable:1344
> <4>[ 7659.207225]  mapped:5952 shmem:472 pagetables:167 bounce:0
> <4>[ 7659.207225]  free:511 free_pcp:3 free_cma:0
> <4>[ 7659.207242] Node 0 active_anon:17324kB inactive_anon:1848kB active_file:84kB inactive_file:100kB unevictable:0kB isolated(anon):0kB isolated(file):68kB > mapped:23808kB dirty:0kB writeback:0kB shmem:1888kB writeback_tmp:0kB unstable:0kB pages_scanned:57 all_unreclaimable? no
> <4>[ 7659.207265] Normal free:2044kB min:2048kB low:2560kB high:3072kB active_anon:17324kB inactive_anon:1848kB active_file:84kB inactive_file:100kB unevictable:0kB > writepending:0kB present:65536kB managed:61164kB mlocked:0kB slab_reclaimable:856kB slab_unreclaimable:5376kB kernel_stack:1096kB pagetables:668kB bounce:0kB > free_pcp:12kB local_pcp:12kB free_cma:0kB
> <4>[ 7659.207268] lowmem_reserve[]: 0 0
> <4>[ 7659.207279] Normal: 43*4kB (UE) 52*8kB (UME) 33*16kB (UME) 19*32kB (ME) 5*64kB (UME) 0*128kB 0*256kB 0*512kB 0*1024kB 0*2048kB 0*4096kB = 2044kB
> <4>[ 7659.207334] 534 total pagecache pages
> <4>[ 7659.207341] 0 pages in swap cache
> <4>[ 7659.207347] Swap cache stats: add 0, delete 0, find 0/0
> <4>[ 7659.207350] Free swap  = 0kB
> <4>[ 7659.207353] Total swap = 0kB
> <4>[ 7659.207357] 16384 pages RAM
> <4>[ 7659.207360] 0 pages HighMem/MovableOnly
> <4>[ 7659.207363] 1093 pages reserved
> <6>[ 7659.207368] [ pid ]   uid  tgid total_vm      rss nr_ptes nr_pmds swapents oom_score_adj name
> <6>[ 7659.207391] [  489]     0   489      245       14       3       0        0             0 sh
> <6>[ 7659.207403] [  534]     0   534      268       31       3       0        0             0 dispatch
> <6>[ 7659.207414] [ 1010]     0  1010    10853     7751      24       0        0             0 rmm
> <6>[ 7659.207424] [ 1090]     0  1090      350       27       4       0        0             0 wpa_supplicant
> <6>[ 7659.207434] [ 1123]     0  1123      245       13       3       0        0             0 udhcpc
> <6>[ 7659.207444] [ 1211]     0  1211      758      533       5       0        0             0 mp4record
> <6>[ 7659.207454] [ 1212]     0  1212      287       33       3       0        0             0 cloud
> <6>[ 7659.207466] [ 1213]     0  1213      879       93       5       0        0             0 p2p_tnp
> <6>[ 7659.207476] [ 1214]     0  1214      977       35       5       0        0             0 oss
> <6>[ 7659.207487] [ 1215]     0  1215      169       15       3       0        0             0 watch_process
> <6>[ 7659.207497] [ 1229]     0  1229      211       11       3       0        0             0 httpd
> <6>[ 7659.207508] [ 1255]     0  1255      211       17       3       0        0             0 pure-ftpd
> <6>[ 7659.207518] [ 1278]     0  1278      219       13       3       0        0             0 dropbear
> <6>[ 7659.207528] [ 1281]     0  1281      167       12       3       0        0             0 ipc_multiplexer
> <6>[ 7659.207538] [ 1363]     0  1363      211       12       3       0        0             0 ntpd
> <6>[ 7659.207548] [ 1380]     0  1380     1124      548       6       0        0             0 rRTSPServer
> <6>[ 7659.207559] [ 1396]     0  1396      246       15       4       0        0             0 wd_rtsp.sh
> <6>[ 7659.207569] [ 1427]     0  1427     2011       68       7       0        0             0 onvif_srvd
> <6>[ 7659.207579] [ 1440]     0  1440      518       37       4       0        0             0 wsdd
> <6>[ 7659.207590] [ 1441]     0  1441      605      449       4       0        0             0 framefinder
> <6>[ 7659.207600] [20484]     0 20484      237       30       4       0        0             0 dropbear
> <6>[ 7659.207610] [20624]     0 20624      246       15       4       0        0             0 ash
> <6>[ 7659.207622] [  943]     0   943      245       14       3       0        0             0 cat
> <6>[ 7659.207632] [ 2947]     0  2947      214       14       4       0        0             0 httpd
> <6>[ 7659.207643] [ 2948]     0  2948      214       14       4       0        0             0 httpd
> <6>[ 7659.207654] [ 2949]     0  2949      214       14       4       0        0             0 httpd
> <6>[ 7659.207665] [ 2950]     0  2950      245       14       3       0        0             0 snapshot.sh
> <6>[ 7659.207676] [ 2981]     0  2981     3258     1852       9       0        0             0 imggrabber
> <6>[ 7659.207686] [ 2982]     0  2982      245       14       3       0        0             0 status.json
> <6>[ 7659.207696] [ 2991]     0  2991      245       14       3       0        0             0 status.json
> <6>[ 7659.207706] [ 2992]     0  2992      219       11       3       0        0             0 cat
> <6>[ 7659.207717] [ 2993]     0  2993      219       10       3       0        0             0 cut
> <6>[ 7659.207727] [ 2994]     0  2994      246       15       4       0        0             0 wd_rtsp.sh
> <6>[ 7659.207737] [ 2995]     0  2995      211       10       3       0        0             0 netstat
> <6>[ 7659.207748] [ 2996]     0  2996      219       10       3       0        0             0 grep
> <6>[ 7659.207758] [ 2998]     0  2998      219       11       3       0        0             0 grep
> <6>[ 7659.207769] [ 2999]     0  2999      219       11       3       0        0             0 grep
> <6>[ 7659.207780] [ 3002]     0  3002      219       10       3       0        0             0 sh
> <3>[ 7659.207787] Out of memory: Kill process 1010 (rmm) score 493 or sacrifice child
> <3>[ 7659.286816] Killed process 1010 (rmm) total-vm:43412kB, anon-rss:7248kB, file-rss:21988kB, shmem-rss:1768kB
> <6>[ 7659.477660] oom_reaper: reaped process 1010 (rmm), now anon-rss:12kB, file-rss:5700kB, shmem-rss:1764kB
> <2>[ 7661.354326] watchdog: watchdog0: watchdog did not stop!

> # cat /proc/kmsg
> <4>[ 7530.032030] adec_send_aacst invoked oom-killer: gfp_mask=0x24201ca(GFP_HIGHUSER_MOVABLE|__GFP_COLD), nodemask=0, order=0, oom_score_adj=0
> <4>[ 7530.032050] CPU: 0 PID: 1212 Comm: adec_send_aacst Tainted: G           O    4.9.118 #58
> <4>[ 7530.032054] Hardware name: sun8iw19
> <4>[ 7530.032089] [<c00118cd>] (unwind_backtrace) from [<c000fdeb>] (show_stack+0xb/0xc)
> <4>[ 7530.032109] [<c000fdeb>] (show_stack) from [<c007db35>] (dump_header.constprop.4+0x45/0x134)
> <4>[ 7530.032128] [<c007db35>] (dump_header.constprop.4) from [<c0055059>] (oom_kill_process+0xa1/0x370)
> <4>[ 7530.032145] [<c0055059>] (oom_kill_process) from [<c005560d>] (out_of_memory+0x201/0x284)
> <4>[ 7530.032162] [<c005560d>] (out_of_memory) from [<c0057cff>] (__alloc_pages_nodemask+0x4c3/0x644)
> <4>[ 7530.032177] [<c0057cff>] (__alloc_pages_nodemask) from [<c0054133>] (filemap_fault+0x2a5/0x426)
> <4>[ 7530.032194] [<c0054133>] (filemap_fault) from [<c0069d95>] (__do_fault+0x39/0xa8)
> <4>[ 7530.032210] [<c0069d95>] (__do_fault) from [<c006c665>] (handle_mm_fault+0x2e1/0x7a0)
> <4>[ 7530.032227] [<c006c665>] (handle_mm_fault) from [<c00141ed>] (do_page_fault+0x171/0x20c)
> <6>[ 7530.046496] [ 1589]     0  1589      245        8       3       0        0             0 sleep
> <6>[ 7530.046506] [ 1622]     0  1622      214        9       4       0        0             0 httpd
> <6>[ 7530.046533] [ 1623]     0  1623      245        9       3       0        0             0 snapshot.sh
> <6>[ 7530.046775] [ 1648]     0  1648     3247     1750      10       0        0             0 imggrabber
> <6>[ 7530.046787] [ 1649]     0  1649      211        6       3       0        0             0 base64
> <6>[ 7530.046798] [ 1652]     0  1652      245        8       3       0        0             0 sh
> <6>[ 7530.046809] [ 1653]     0  1653      245        8       3       0        0             0 sh
> <6>[ 7530.046818] [ 1654]     0  1654      219        6       3       0        0             0 cat
> <6>[ 7530.047067] [ 1655]     0  1655      219        6       3       0        0             0 grep
> <6>[ 7530.047079] [ 1656]     0  1656      219        6       3       0        0             0 awk
> <6>[ 7530.047090] [ 1657]     0  1657      184        9       3       0        0             0 wpa_cli
> <3>[ 7530.047100] Out of memory: Kill process 1012 (rmm) score 493 or sacrifice child
> <3>[ 7530.088354] Killed process 1653 (sh) total-vm:980kB, anon-rss:32kB, file-rss:0kB, shmem-rss:0kB
> <4>[ 7530.160431] dispatch invoked oom-killer: gfp_mask=0x24201ca(GFP_HIGHUSER_MOVABLE|__GFP_COLD), nodemask=0, order=0, oom_score_adj=0
> <4>[ 7530.160449] CPU: 0 PID: 1024 Comm: dispatch Tainted: G           O    4.9.118 #58
> <4>[ 7530.160454] Hardware name: sun8iw19
> <4>[ 7530.160492] [<c00118cd>] (unwind_backtrace) from [<c000fdeb>] (show_stack+0xb/0xc)
> <4>[ 7530.160512] [<c000fdeb>] (show_stack) from [<c007db35>] (dump_header.constprop.4+0x45/0x134)
> <4>[ 7530.160532] [<c007db35>] (dump_header.constprop.4) from [<c0055059>] (oom_kill_process+0xa1/0x370)
> <4>[ 7530.160549] [<c0055059>] (oom_kill_process) from [<c005560d>] (out_of_memory+0x201/0x284)
> <4>[ 7530.160567] [<c005560d>] (out_of_memory) from [<c0057cff>] (__alloc_pages_nodemask+0x4c3/0x644)
> <4>[ 7530.160582] [<c0057cff>] (__alloc_pages_nodemask) from [<c0054133>] (filemap_fault+0x2a5/0x426)
> <4>[ 7530.160599] [<c0054133>] (filemap_fault) from [<c0069d95>] (__do_fault+0x39/0xa8)
> <4>[ 7530.160614] [<c0069d95>] (__do_fault) from [<c006c665>] (handle_mm_fault+0x2e1/0x7a0)
> <4>[ 7530.160631] [<c006c665>] (handle_mm_fault) from [<c00141ed>] (do_page_fault+0x171/0x20c)
> <4>[ 7530.160647] [<c00141ed>] (do_page_fault) from [<c0009275>] (do_PrefetchAbort+0x25/0x60)
> <4>[ 7530.160660] [<c0009275>] (do_PrefetchAbort) from [<c0010abb>] (__pabt_usr+0x5b/0x5c)
> <4>[ 7530.160666] Exception stack(0xc3209fb0 to 0xc3209ff8)
> <4>[ 7530.160675] 9fa0:                                     00000000 00000000 00000000 00000000
> <4>[ 7530.160686] 9fc0: b6e5dc20 00000000 00000000 0000008e 00012373 0002d25c 00000001 00000000
> <4>[ 7530.160696] 9fe0: b6e5dbd8 b6e5dbc4 b6ef245c b6ef1968 60000010 ffffffff
> <4>[ 7530.160700] Mem-Info:
> <4>[ 7530.160722] active_anon:4209 inactive_anon:463 isolated_anon:0
> <4>[ 7530.160722]  active_file:24 inactive_file:29 isolated_file:0
> <4>[ 7530.160722]  unevictable:0 dirty:0 writeback:0 unstable:0
> <4>[ 7530.160722]  slab_reclaimable:212 slab_unreclaimable:1341
> <4>[ 7530.160722]  mapped:5937 shmem:472 pagetables:153 bounce:0
> <4>[ 7530.160722]  free:508 free_pcp:15 free_cma:0
> <4>[ 7530.160739] Node 0 active_anon:16836kB inactive_anon:1852kB active_file:96kB inactive_file:116kB unevictable:0kB isolated(anon):0kB isolated(file):0kB > mapped:23748kB dirty:0kB writeback:0kB shmem:1888kB writeback_tmp:0kB unstable:0kB pages_scanned:0 all_unreclaimable? yes
> <4>[ 7530.160762] Normal free:2032kB min:2048kB low:2560kB high:3072kB active_anon:16836kB inactive_anon:1852kB active_file:96kB inactive_file:116kB unevictable:0kB > writepending:0kB present:65536kB managed:61164kB mlocked:0kB slab_reclaimable:848kB slab_unreclaimable:5364kB kernel_stack:1064kB pagetables:612kB bounce:0kB > free_pcp:60kB local_pcp:60kB free_cma:0kB
> <4>[ 7530.160765] lowmem_reserve[]: 0 0
> <4>[ 7530.160775] Normal: 56*4kB (UM) 54*8kB (UME) 28*16kB (UME) 23*32kB (UME) 3*64kB (UM) 0*128kB 0*256kB 0*512kB 0*1024kB 0*2048kB 0*4096kB = 2032kB
> <4>[ 7530.160831] 525 total pagecache pages
> <4>[ 7530.160838] 0 pages in swap cache
> <4>[ 7530.160843] Swap cache stats: add 0, delete 0, find 0/0
> <4>[ 7530.160847] Free swap  = 0kB
> <4>[ 7530.160850] Total swap = 0kB
> <4>[ 7530.160854] 16384 pages RAM
> <4>[ 7530.160857] 0 pages HighMem/MovableOnly
> <4>[ 7530.160860] 1093 pages reserved
> <6>[ 7530.160864] [ pid ]   uid  tgid total_vm      rss nr_ptes nr_pmds swapents oom_score_adj name
> <6>[ 7530.160887] [  487]     0   487      245        9       3       0        0             0 sh
> <6>[ 7530.160898] [  536]     0   536      268       20       3       0        0             0 dispatch
> <6>[ 7530.160909] [ 1012]     0  1012    10854     7745      26       0        0             0 rmm
> <6>[ 7530.160919] [ 1096]     0  1096      350       22       4       0        0             0 wpa_supplicant
> <6>[ 7530.160928] [ 1129]     0  1129      245        8       3       0        0             0 udhcpc
> <6>[ 7530.160938] [ 1217]     0  1217      744      516       4       0        0             0 mp4record
> <6>[ 7530.160949] [ 1218]     0  1218      287       28       3       0        0             0 cloud
> <6>[ 7530.160958] [ 1219]     0  1219      879       85       5       0        0             0 p2p_tnp
> <6>[ 7530.160969] [ 1220]     0  1220      977       30       6       0        0             0 oss
> <6>[ 7530.160979] [ 1221]     0  1221      169       10       3       0        0             0 watch_process
> <6>[ 7530.160989] [ 1230]     0  1230      211        6       3       0        0             0 httpd
> <6>[ 7530.160999] [ 1247]     0  1247      211       12       3       0        0             0 pure-ftpd
> <6>[ 7530.161009] [ 1267]     0  1267      219        8       3       0        0             0 dropbear
> <6>[ 7530.161019] [ 1269]     0  1269      167        7       3       0        0             0 ipc_multiplexer
> <6>[ 7530.161028] [ 1359]     0  1359      211        7       3       0        0             0 ntpd
> <6>[ 7530.161038] [ 1380]     0  1380     1124      541       6       0        0             0 rRTSPServer
> <6>[ 7530.161049] [ 1396]     0  1396      246       10       3       0        0             0 wd_rtsp.sh
> <6>[ 7530.161059] [ 1438]     0  1438     2011       65       7       0        0             0 onvif_srvd
> <6>[ 7530.161070] [ 1443]     0  1443      518       32       5       0        0             0 wsdd
> <6>[ 7530.161080] [ 1444]     0  1444      605      444       4       0        0             0 framefinder
> <6>[ 7530.161090] [14290]     0 14290      237       26       4       0        0             0 dropbear
> <6>[ 7530.161100] [14408]     0 14408      246       10       4       0        0             0 ash
> <6>[ 7530.161111] [ 1007]     0  1007      245        9       3       0        0             0 cat
> <6>[ 7530.161121] [ 1589]     0  1589      245        8       3       0        0             0 sleep
> <6>[ 7530.161131] [ 1622]     0  1622      214        9       4       0        0             0 httpd
> <6>[ 7530.161142] [ 1623]     0  1623      245        9       3       0        0             0 snapshot.sh
> <6>[ 7530.161152] [ 1648]     0  1648     3247     1751      10       0        0             0 imggrabber
> <6>[ 7530.161161] [ 1649]     0  1649      211        6       3       0        0             0 base64
> <6>[ 7530.161171] [ 1652]     0  1652      245        8       3       0        0             0 sh
> <6>[ 7530.161182] [ 1654]     0  1654      219        6       3       0        0             0 cat
> <6>[ 7530.161192] [ 1655]     0  1655      219        6       3       0        0             0 grep
> <6>[ 7530.161202] [ 1656]     0  1656      219        6       3       0        0             0 awk
> <6>[ 7530.161212] [ 1657]     0  1657      184        9       3       0        0             0 wpa_cli
> <3>[ 7530.161218] Out of memory: Kill process 1012 (rmm) score 492 or sacrifice child
> <3>[ 7530.170837] Killed process 1012 (rmm) total-vm:43416kB, anon-rss:7240kB, file-rss:21972kB, shmem-rss:1768kB
> <6>[ 7530.235560] oom_reaper: reaped process 1012 (rmm), now anon-rss:0kB, file-rss:5676kB, shmem-rss:1764kB
> <2>[ 7532.135855] watchdog: watchdog0: watchdog did not stop!

Info | Value
-- | --
Yi Home 1080p S/N | 9FUSY32
Firmware Version | 0.2.2
Base Version | 8.3.0.0A_201912271707
Model Suffix | y25ga

**Comment by mk386** [comment]
Info | Value
-- | --
Yi Home 1080p S/N | 9FUSY32
Firmware Version | 0.2.2
Base Version | 8.3.0.0A_201912271707
Model Suffix | y25ga

**Comment by roleoroleo** [comment]
Check these issues:
https://github.com/roleoroleo/yi-hack-Allwinner/issues/13
https://github.com/roleoroleo/yi-hack-Allwinner/issues/35

And try to enable swap space.

**Comment by mk386** [comment]
Yes, it's duplicate issue. Sorry about that.

Making swap space or disabling the cloud service, both are working. I'd like to disable cloud rather than using swap on SD card.
Thank you!
