### ISSUE TITLE
No audio when user and password are set

### ISSUE THREAD

**Issue by jjtleon** [roleoroleo/yi-hack-Allwinner#237]
I have a couple 9FUS cameras with 8.2.0.0A_202012041528 original firmware and have been running yi-hack-Allwinner 0.2.2 successfully for a couple months now.  I really appreciate this project and its utility.  Yesterday, I upgraded to 0.2.3 and it stabilized many RTSP dropouts.  I then decided to turn on audio.  In VLC, I verified only one stream being received: video.  I tracked it down to the RTSP user authentication.  When username and password are set, no audio.  I only receive the audio stream in VLC without user authentication.

Out of curiosity, I tried the rRTSPServer by @roleoroleo from #225.  Same results with alaw, ulaw and pcm, but audio was received for aac with username and password.

**Comment by roleoroleo** [comment]
I noticed the same problem but I can't understand.

Audio is correctly detected by vlc:
![immagine](https://user-images.githubusercontent.com/39277388/106395117-cacad480-6400-11eb-8390-5bdc3a11620a.png)
And decoded:
![immagine](https://user-images.githubusercontent.com/39277388/106395142-eafa9380-6400-11eb-8f77-7d272cd70e83.png)

But I don't hear it .

**Comment by roleoroleo** [comment]
Recompiling with the last version of live555, it seems working correctly.

**Comment by jjtleon** [comment]
To be clear, the issue I am reporting is that the audio stream is missing when a username and password are required for alaw, ulaw and pcm.  When no authentication is required, audio stream is present.  Are you saying by recompiling with the latest version of live555, the no audio with user authentication issue is resolved?  Thanks in advance!

**Comment by roleoroleo** [comment]
Yes.
I will send you a binary to check it.

**Comment by mancmanGER** [comment]
I got the same issue, no audio in the stream. Looking forward to get the fix. THX

**Comment by roleoroleo** [comment]
Try this binary:
[rRTSPServer.gz](https://github.com/roleoroleo/yi-hack-Allwinner/files/5906030/rRTSPServer.gz)

**Comment by mancmanGER** [comment]
Ok I changed the file, which does live in _/home/yi-hack/bin_ and set it to 755 via SSH
--> Sound is back

THX

**Comment by jjtleon** [comment]
Confirmed audio stream is present with user authentication when RTSP_AUDIO is set to yes, alaw, ulaw, pcm and aac.  Thank you for the quick fix @roleoroleo!

**Comment by setterlee** [comment]
I'm using my camera with the ispy software... WIth the Yi Home app the audio works well but with the ispy software not work... could be related with this issue?

**Comment by roleoroleo** [comment]
If audio is presente using another client (eg. vlc) the problem could be:
- this issue.
- the codec is not compatible (for example my dvr doesn't recognize ulaw).
- the client doesn't work correctly.

Try with vlc and try to change the codec.

**Comment by setterlee** [comment]
> If audio is presente using another client (eg. vlc) the problem could be:
> 
> * this issue.
> * the codec is not compatible (for example my dvr doesn't recognize ulaw).
> * the client doesn't work correctly.
> 
> Try with vlc and try to change the codec.

I tested with VLC and there is no sound...

**Comment by nickuww** [comment]
I am using a 9FUS camera with firmware 0.2.3 and can verify that when a username and password are set there is no audio. I tested using the RTSP audio only in VLC and it will not even pull up with a username and password set. As soon as I removed them it played fine. Has anyone found a way to fix this issue?

**Comment by roleoroleo** [comment]
This issue is related to the c++ compiler.
When I change the version of the library or the optimization flag the problem appear/disappear.
Try this:
[rRTSPServer.gz](https://github.com/roleoroleo/yi-hack-Allwinner/files/6248120/rRTSPServer.gz)
