### ISSUE TITLE
Camera not starting with SD card after upgrading to 0.2.3 via the interface

### ISSUE THREAD

**Issue by basdejong95** [roleoroleo/yi-hack-Allwinner#239]
Hi, i have updated my Camera to 0.2.3 via the interface, but it won't boot (steady yellow light) until i pull the plug and remove the SD card.

IT also seemed to re-set all my settings to the defaults after the upgrade.

Firmware Version | 0.2.3
-- | --
Base Version | 8.2.0.0A_201912270941
Model Suffix | y20ga
Serial Number | BFUSY31PSIWBWxxxxxxx

**Comment by roleoroleo** [comment]
If your record folder is big (a lot of mp4 files recorded) the update process needs a long time.
Try to delete the folder /tmp/sd/record and try again.

**Comment by basdejong95** [comment]
> If your record folder is big (a lot of mp4 files recorded) the update process needs a long time.
> Try to delete the folder /tmp/sd/record and try again.

Thanks! that worked for me! 

Thanks for all your efforts on this!
