### ISSUE TITLE
MQTT problem in 0.1.5

### ISSUE THREAD

**Issue by roleoroleo** [roleoroleo/yi-hack-Allwinner#25]
There is s problem in 0.1.5.
The cam doesn't send mqtt messages because of an error in mqttv4 daemon.

**Comment by Xandrios** [comment]
Confirm that this is resolved in 0.1.6, thanks!

![image](https://user-images.githubusercontent.com/28824242/81735909-71033280-949e-11ea-9f41-aa3dbe5f202d.png)

**Comment by crdnl** [comment]
Closed due to being fixed in v0.1.6
