### ISSUE TITLE
Is my BFUS cam dead? Plugin in -> Instant steady orange led

### ISSUE THREAD

**Issue by DerpyDoom** [roleoroleo/yi-hack-Allwinner#250]
Hey!

I hacked the Yi cam quite a while ago and stored it aside since I didn't need it. I now found a place to put it but it seems like it's bricked or dead somehow.

If I plugin the cam I instantly get a steady orange led. :(

**Comment by roleoroleo** [comment]
I need more information to help you.

**Comment by DerpyDoom** [comment]
What kind do you need? I'm happy to provide everything you need.

**Comment by roleoroleo** [comment]
I think you don't have the serial adapter connected.

Maybe you are using a wrong power adapter or cable?
If not, try to remove the hack and reset the cam.

**Comment by DerpyDoom** [comment]
I don't have any serial adapter. The thing is I am not even able to reset the cam. It's always an orange led that's lit. When I hold the reset button nothing happens.

Like I said, it was mid 2020 when I got the cam. I put it aside because I wasn't using it.
