### ISSUE TITLE
Delete All button

### ISSUE THREAD

**Issue by risturiz** [roleoroleo/yi-hack-Allwinner#255]
Hi, it´s possible to add "Delete All" button on web? Actually i have to connect ssh to "rm -rf" videos for upgrade.

Thanks.

**Comment by roleoroleo** [comment]
There is a web service:
http://IP:8080/cgi-bin/eventsdirdel.sh?dir=all

**Comment by risturiz** [comment]
> There is a web service if you want:
> http://IP:8080/cgi-bin/eventsdirdel.sh?dir=all

Great feature! I see the info now on wiki... This option should be run before every upgrade... With any videos the upgrade take forever.

Thanks!
