### ISSUE TITLE
Build P2P Client on Android

### ISSUE THREAD

**Issue by ricardojlrufino** [roleoroleo/yi-hack-Allwinner#264]
I wanted to develop my own P2P client, to have an application with time-based access control.
Can you help me, what tools can I be using ?!

something like:
https://www.balena.io/blog/build-a-raspberry-pi-based-network-camera/#softwarerequired

**Comment by roleoroleo** [comment]
This is an embedded system.
You have to use C language...

**Comment by ricardojlrufino** [comment]
I managed to compile and run a basic hello.

The difficulty is to understand P2P, and how to distribute the stream.
Do you have any ideas or material that can help?

Related:
https://github.com/roleoroleo/yi-hack-Allwinner/issues/41

**Comment by roleoroleo** [comment]
Do you wanto to send audio/video stream like the yi original app?

**Comment by ricardojlrufino** [comment]
yes ...

**Comment by roleoroleo** [comment]
I don't know how to help you.
Maybe other users...

**Comment by kikecalpe** [comment]
> I managed to compile and run a basic hello.
> 
> The difficulty is to understand P2P, and how to distribute the stream. Do you have any ideas or material that can help?
> 
> Related: #41

Check #362
