### ISSUE TITLE
[VLC] audio out of sync

### ISSUE THREAD

**Issue by ricardojlrufino** [roleoroleo/yi-hack-Allwinner#266]
I verified that when accessing the stream through the VLC the audio is a few seconds ahead of the video.
![image](https://user-images.githubusercontent.com/515675/112171065-4f9cc800-8bd2-11eb-910a-837e83236147.png)

**Comment by ricardojlrufino** [comment]
After reboot cam back to normal...

**Comment by roleoroleo** [comment]
There is an offset between video and audio that depends on the buffering of the rRTSPServer program.
Unfortunately it is not predictable, sometimes they are aligned, sometimes they are out of sync.

**Comment by ricardojlrufino** [comment]
Thanks for the feedback.
Do you have a ffmpeg command to capture? I am having some problems in capturing the rtsp. Some software like https://antmedia.io/ the video gets corrupted
