### ISSUE TITLE
BFUS no Webinterface after updating from 0.2.2 to 0.2.4

### ISSUE THREAD

**Issue by geniac** [roleoroleo/yi-hack-Allwinner#271]
First of all thanks for all your work and commitment to this AWESOME project.

I am experiencing the following problem since my BFUS model was updated 0.2.2 to 0.2.4:
When trying to access via webinterface it results in a 404 error.
Video recording & RTSP / FTP is still working.
SSH/MQTT is disabled.

**Comment by roleoroleo** [comment]
I already encountered this problem.
Probably something wrong during upgrade.
Please reflash the cam.

**Comment by geniac** [comment]
Reflashing the cam fixed it.
Thanks for the fast response.
