### ISSUE TITLE
MIC Record

### ISSUE THREAD

**Issue by ricardojlrufino** [roleoroleo/yi-hack-Allwinner#282]
Hi, can you figure out how to record audio?

./arecord get this error
> ./arecord: line 1: can't create }dataq: Invalid argument
> ./arecord: line 1: RIFFWAVEfmt: not found

**Comment by ricardojlrufino** [comment]
Related to the GPIO part, using strace on the various binaries does not "appear" to have any ioctl.
When I send the command BY THE ANDOIRD APP, this log appears:

p2p_tnp.c(myDoIOCtrl-5298)[16:49:10.279]:myDoIOCtrl(..): 0, IOTYPE_USER_IPCAM_AUDIOSTOP
p2p_tnp.c(myDoIOCtrl-5292)[16:49:10.768]:myDoIOCtrl(..): 0, IOTYPE_USER_IPCAM_AUDIOSTART

But no call to ioctl ...

ref:
![image](https://user-images.githubusercontent.com/515675/114316506-440a3600-9ada-11eb-9069-b13dff0cd4da.png)

**Comment by roleoroleo** [comment]
Maybe p2p_tnp doesn't execute directly ioctl.
Probably it sends a socket command to another process.

**Comment by ricardojlrufino** [comment]
Yes, I think that's it too
![image](https://user-images.githubusercontent.com/515675/114324583-4338ca80-9b01-11eb-876e-6cce93e636c2.png)
