### ISSUE TITLE
0.2.5

### ISSUE THREAD

**Issue by robs1234** [roleoroleo/yi-hack-Allwinner#286]
Installed but not working.
Get as far as the main web page but only the top banner/headers showing, & rtsp not working in VLC.
I'm afraid I know sweetnothing about troubleshooting/logs how to etc...

...edited to add.. Tried rerolling to 0.2.3 - can access the GUI menus again but shows as 0.2.4 and rtsp not working still. Nor snapshots.

...edited again 10 mins later (must take some time to warm up!), snapshots now working and can view rtsp in contacam...but not in VLC strangely.
So working again I think - nice!

**Comment by sermayoral** [comment]
@robs1234 finally, what version do you have?

**Comment by robs1234** [comment]
loaded 0.2.3 but it shows as 0.2.4...

**Comment by roleoroleo** [comment]
> loaded 0.2.3 but it shows as 0.2.4...

Maybe there was a problemi during the update procedure.
Please, restart from scratch.
Reformat the sd and apply the hack again.

**Comment by robs1234** [comment]
Thanks roleoroleo, tried that again, but same result - still showing as 2.4 on the maintenance page.

No worries, seems to be working fine anyway.

**Comment by roleoroleo** [comment]
Last chance: clean the cache of your browser.

**Comment by robs1234** [comment]
Tried upgrade to 0.2.5 again and now all is working fine - many thanks roleoroleo!

**Comment by Arkady23** [comment]
I did the formatting via the web-interface.
https://github.com/Arkady23/yi-hack-Allwinner-plus
