### ISSUE TITLE
9FUS Y20ga brick

### ISSUE THREAD

**Issue by thetux07** [roleoroleo/yi-hack-Allwinner#287]
hello my camera have a orange led static on boot and nothing is happening
have you a origine firmware or backup or proce for repare my cam ?
thank you

**Comment by roleoroleo** [comment]
This is the unbrick procedure: https://github.com/roleoroleo/yi-hack-Allwinner/wiki/Unbrick-the-cam
But, before to use this procedure, try to unhack the cam with this one: https://github.com/roleoroleo/yi-hack-Allwinner/wiki/Remove-the-hack

**Comment by thetux07** [comment]
ok thank you, yes i have already unhack the camera but it don't work to, for the unbrick camera procedure, i have read it but i don't have backup :(, how made without it ?
thank you

**Comment by roleoroleo** [comment]
Let me know when you finish to download the file:
[mtdblock3.bin.gz](https://github.com/roleoroleo/yi-hack-Allwinner/files/6309906/mtdblock3.bin.gz)

**Comment by thetux07** [comment]
ok thank you, i've dowload it
i test unbrick procedure and i come back to you
thank you

**Comment by LZsolt75** [comment]
I would like to upgrade from 0.2.4 to 0.2.5 through the web gui maintenance menu. After a lot of waiting the camera is unreachble and the orange led is lit continuosly. I couldn't reach the web gui.
What should I do?

**Comment by roleoroleo** [comment]
Try to apply again the hack.

**Comment by LZsolt75** [comment]
> 
> 
> Try to apply again the hack.

Looks like it solve my problem. I thin the main problem is that the SD card was full so the updater have no space to do its job.
