### ISSUE TITLE
Install firmware from web ui without internet

### ISSUE THREAD

**Issue by xijio** [roleoroleo/yi-hack-Allwinner#293]
My yi cameras are all on old firmware and none have internet access.  It would be great if i could upload new firmware from the web ui without having to pull all the cameras down and flash the sd cards.  I only see the option to check for updates online and no option to upload custom firmware.

**Comment by xijio** [comment]
I ended reading through the firmware update script and just running similar commands to update via ssh after putting the firmware on the camera via ftp.  It worked great :)

**Comment by minax007** [comment]
I would also appreciate if the firmware installation (e. g. changing back to a former version) would be possible via the web UI.
