### ISSUE TITLE
Cam stops working after ??hours, after reboot all fine 

### ISSUE THREAD

**Issue by mdgarf** [roleoroleo/yi-hack-Allwinner#304]
Hi, 
Cam should run 24/7, have script to get image (every 20min) and send it out. 
Have 2 cams, both repeatedly stop responding. At different times(10 and more hours), I think. Have to power off, after boot up all is OK. 

yi-hack-Allwinner 0.2.6
y25ga_0.2.6.tgz
9FUSY@8.3.0.0

Any idea how to fix it?

**Comment by mdgarf** [comment]
1. cam 8:32h
2. cam 5:10h 
other cams yi, edimax, hik work fine.

**Comment by roleoroleo** [comment]
Is the swap file enabled?
The cam runs with little free memory and the snapshot is very expensive.

**Comment by mdgarf** [comment]
no
just switched on, will let you know.
thanks for a prompt reply

**Comment by mdgarf** [comment]
cams are working, I believe you solved it.
thanks

**Comment by AJStubbsy** [comment]
I'm experiencing this problem where the camera keeps turning off. Seems to happen at dusk when the camera is constantly adjusting the light settings. Can you tell me where I can find 'swap file' settings please? I haven't seen this on the web page or camera app.

**Comment by catatonico2** [comment]
Around here the same, after a while the camera stops working, firmware 0.27 - BFUS

**Comment by roleoroleo** [comment]
What features stop working?

**Comment by catatonico2** [comment]
Stop being online, both for local and for app yi, restart returns to online. In the Yi home app it indicates that I have a pending update firmware but it does not take place.

**Comment by roleoroleo** [comment]
Maybe a memory leak.
Are you able to connect with ssh when the cam stops working?
If yes, please check the memory and cpu usage.
Run top, df and free commands.

**Comment by catatonico2** [comment]
ok right now it is online, as soon as I lose connection I try.

**Comment by catatonico2** [comment]
I have lost the connection again, it does not ping the ip, the yi app does not respond or ip: 8080.

**Comment by roleoroleo** [comment]
Is swap enabled?

**Comment by catatonico2** [comment]
yes,

**Comment by Staini** [comment]
I can also confirm this.
I could observe when ipc_cmd is run twice at the same time it occurs more.

The camera is then no longer reachable via the network.

**Comment by roleoroleo** [comment]
I don't know how to find the problem...

**Comment by Staini** [comment]
Methode 1:
1. open the ptz page.
2. make movements in front of the camera.
3. send in the same time with ssh multiple ipc_cmd commands (e.g. record and stop).

Methode 2:
1. disable the wifi from your router and enable it again.
2. wait 30 seconds.
3. repeat these steps several times.
