### ISSUE TITLE
RTSP - Set or limit fps?

### ISSUE THREAD

**Issue by aswlee0** [roleoroleo/yi-hack-Allwinner#31]
Hi,

Keep up the great work!

My question (or feature request) is:
Is there a way to set or limit the frames per second of the RTSP streams?

**Comment by roleoroleo** [comment]
No sorry. As explained in other threads, we can't control the encoding phase.
We can't change resolution, fps, compressione, etc...

**Comment by aswlee0** [comment]
Thanks for the quick reply!
