### ISSUE TITLE
FTP Upload re-uploads all events after reboot

### ISSUE THREAD

**Issue by dallas6672** [roleoroleo/yi-hack-Allwinner#310]
Firmware Version | 0.2.6
Base Version | 8.2.0.0A_202007211802
Model Suffix | y20ga

Not sure if this is the expected behavior for the the FTP Upload feature, but every time you reboot the camera, all events that are still on the local SD card get re-uploaded to the remote FTP Server.

**Comment by roleoroleo** [comment]
Yes, it's by design.
I don't want to save the state on flash because I don't want to destroy it.

**Comment by Catfriend1** [comment]
we could maybe do a file move into a subfolder /uploaded/... and ignore that folder in the find command
