### ISSUE TITLE
Set username/password and can no longer access web UI

### ISSUE THREAD

**Issue by RyanWor** [roleoroleo/yi-hack-Allwinner#311]
Hi. Thanks for this firmware. This is amazing. I have one issue with a few cameras I setup (9FUS). I set a username/password as well as a root password. Once they rebooted I cannot login to the web interface with that username and password. I can however login via SSH. Is there a way to reconfigure the standard user's credentials from SSH and is there any limitations to the length and characters allowed in the user account for the web interface? Thanks!

**Comment by roleoroleo** [comment]
I don't remember exactly but another user found a limit in the size.
You can change the password from SSH editing the file /home/yi-hack/etc/system.conf

**Comment by RyanWor** [comment]
Thanks I figured it out eventually. It wasn't actually the length that was a problem for me it was an issue with some symbols. Switched to alphanumeric and it worked fine. Appreciate all your work on this firmware @roleoroleo!

**Comment by roleoroleo** [comment]
If you use only the suggested special chars, it should work.
