### ISSUE TITLE
missing time stamp on saved motion detected video

### ISSUE THREAD

**Issue by mdgarf** [roleoroleo/yi-hack-Allwinner#312]
Just had to go trough motion detected video's (saved on the card in cam) and noticed there is no time/date stamp in the video.
Very glad to have the video, but with the time stamp it would be more of a evidence. 
Is it missing or it can be setup?

**Comment by roleoroleo** [comment]
It's missing.
The original firmware should add timestamp but it doesn't.
And I can't add it after h264 coding because the cam does not have enough hw resources.

**Comment by Mi-Sanchez** [comment]
maybe only adding a picture with timestamp as first frame to each video?
