### ISSUE TITLE
Yi 1080p Home BFUS Cause HomeAssistant crush

### ISSUE THREAD

**Issue by rt400** [roleoroleo/yi-hack-Allwinner#316]
Hello,
I have Yi 1080p Home BFUS with Yi-Hack 0.2.6 firmware.
In HomeAssistant (2021.7 on docker x64) i set the camera with Generic IP Camera (i have 2 more but not the same).
when this camera are set in HA after couple hours (sometimes couple minutes) the HA crash and make restart, and if i remove the camera from HA works fine... any idea ?

if i downgrade to 2021.6 all works fine also with the camera set.

**Comment by roleoroleo** [comment]
I'm using 2021.7.3 and I haven't noticed your problem.
2 hints:
- wait for a ha upgrade
- try my integration: https://github.com/roleoroleo/yi-hack_ha_integration instead of generic cam
