### ISSUE TITLE
Crontab settings not persisted in 0.2.6 

### ISSUE THREAD

**Issue by cyraxnet** [roleoroleo/yi-hack-Allwinner#317]
Upgraded to 0.2.6 and whenever I save settings to crontab, and reboot, it resets the value back to "0".
Export of config reveals that value is not being saved i.e. system.conf has

`CRONTAB=0`

Same on two cameras.  Was fine on 0.2.4.

Anything to dig, once I SSH onto the camera?

**Comment by roleoroleo** [comment]
Probably I already fixed this issue.
See this commit: https://github.com/roleoroleo/yi-hack-Allwinner/commit/48ae06692866f7d055a3db119ac81102f97cf5bf
