### ISSUE TITLE
restting options should not be a one click thing

### ISSUE THREAD

**Issue by pbanj** [roleoroleo/yi-hack-Allwinner#318]
this is the second time i have reset my camera because there is no confirmation before it does it. at the min at least move it away from reboot

**Comment by vin-w** [comment]
I accidentally clicked twice too. So now I always do backup of my config so that I could restore easier.

I hope to have a popup to confirm feature too.

```
<script LANGUAGE="JavaScript">
<!--
function confirmSubmit(text)
{
var agree=confirm("Are you sure to " + text + "?");
if (agree)
 return true ;
else
 return false ;
}
// -->
</script>
 <input class="button-primary" type="button" id="button-reset" value="Reset Camera"  onClick="return confirmSubmit('reset')"/>
```

**Comment by roleoroleo** [comment]
:)
I will add it.

**Comment by pbanj** [comment]
Thank you so much. Also I finally used the built in wifi settings you added. They worked great 👍

**Comment by pbanj** [comment]
@roleoroleo i just updated and the changelog says `Add confirmation to reboot/reset buttons` but reboot doesnt ask. not sure if you made a typo in the change log or if it is supposed to ask. im scared to test the reset option lol

**Comment by pbanj** [comment]
nvm it is "working". it's firefox blocking the popup unless you turn off firefoxes enhanced protection. but with the popup blocked the camera still reboots
