### ISSUE TITLE
Turn on/off the cam with HA automation?

### ISSUE THREAD

**Issue by fredmassa** [roleoroleo/yi-hack-Allwinner#32]
Hi @roleoroleo ,
many thanks for everything! Your work is great!!
I 've a question about using the hacked Yi home 1080p camera with HA. Is it possible to turn on/off the cam with an automation in home assistant?

Thanks ;-)

**Comment by roleoroleo** [comment]
What do you mean with off?
Which services do you want to switch off?

**Comment by fredmassa** [comment]
The camera itself. My idea is to turn on the camera when the alarm is armed and turn off the camera when the alarm is disarmed

**Comment by fredmassa** [comment]
Talking about services... maybe switching on/off these 2 is enough
![image](https://user-images.githubusercontent.com/52414620/81794889-c0337c80-950b-11ea-816e-fadc0c95eba6.png)

**Comment by roleoroleo** [comment]
Actually, the "Switch on/off the camera" swithes only Yi services.
If you use RTSP, this switch doesn't change anything.
Check out the wiki about services.

**Comment by fredmassa** [comment]
ok so I cannot turn on/off the camera using services like I can do from the Yi app (the camera turn off but remains connected to the wifi so you can turn on it when you need). 

I'll use a smart switch to turn on/off the electricity ;-)

**Comment by roleoroleo** [comment]
The switch "Switch on/off the camera" has exactly the same effect as the app switch: it stops the Yi services.
But RTSP is not a Yi service.
You can use camera_settings.sh to switch off the cam and service.sh to start/stop RTSP.

**Comment by fredmassa** [comment]
how can i call the camera_settings.sh and the service.sh?
Because i can use ftp to connect to the camera but i can't find the camera_settings.sh or service.sh files

**Comment by roleoroleo** [comment]
See the wiki about web services.

**Comment by fredmassa** [comment]
Perfect, many thanks!
