### ISSUE TITLE
TTS engine not found

### ISSUE THREAD

**Issue by Giulianini** [roleoroleo/yi-hack-Allwinner#328]
![image](https://user-images.githubusercontent.com/39558398/138505441-3fae3ad4-6ae3-4390-af33-acee2b6a8637.png)

I have version 0.2.7

**Comment by roleoroleo** [comment]
I tested again the web page and it seems working properly.
Both text and audio file.
Did you solve your problem?

**Comment by MrTOffice** [comment]
Could you please tell me how to install engine files (from https://github.com/roleoroleo/yi-hack-utils)  into Yi camera.
Sorry, to ask but I am not good at linux. 
I try to copy file into SD card and ssh
then I don't know which folder should I install
I tried

>tar xzvf curl.tgz

and get error (which I don't know what it means)

curl
libcurl.so
tar: can't create symlink libcurl.so to libcurl.so.4.6.0: Operation not permitted
libcurl.so.4
tar: can't create symlink libcurl.so.4 to libcurl.so.4.6.0: Operation not permitted
libcurl.so.4.6.0

Please help. Thank you in advance.
