### ISSUE TITLE
Yi 1080p Home RFUS

### ISSUE THREAD

**Issue by fernandolcardoso** [roleoroleo/yi-hack-Allwinner#332]
Hello everyone,

I recently bought some cameras from Yi and am looking for an alternative firmware for them.

The problem is I'm not finding a compatible version or I don't know which version to use.

- Camera: Yi 1080p Home RFUS
- Firmware: 9.0.36.02
- Model: YYS.2016

I appreciate if anyone can tell me the correct version.

**Comment by pkkirilov** [comment]
Hi @fernandolcardoso, you need y211ga from [here](https://github.com/roleoroleo/yi-hack-Allwinner-v2)
