### ISSUE TITLE
Snapshot resolution

### ISSUE THREAD

**Issue by treghart** [roleoroleo/yi-hack-Allwinner#333]
Hello,

Is it only me or snapshot (http://*:8080/cgi-bin/snapshot.sh?res=low&watermark=yes) always returns high res snapshot since the last update? (0.2.7) It used to work properly and it also works fine for me on the Allwiner V2 and MStar.

**Comment by pinguinpfleger** [comment]
see here https://github.com/roleoroleo/yi-hack-Allwinner/issues/348
