### ISSUE TITLE
9FUSY32*** works?

### ISSUE THREAD

**Issue by ibanmda** [roleoroleo/yi-hack-Allwinner#337]
Hi, @roleoroleo !

I bougth recently my second cam: 

```
Yi Home Camera 3 (1080)
DID: 9FUSY32C2GNT****
S/N: 9Y25GA
Date: 2020.06
```

I tryed to hack with **8.3.0* (y25ga)** and **8.2.0 (y20ga)** without succesfuly (reboot -> blink orange -> "waiting to connect").

There are the hacks for this camera?

Regards!!!

**Comment by roleoroleo** [comment]
It should be a 8.3.0
