### ISSUE TITLE
RTSP Audio reverting to DIsabled after save - reboot

### ISSUE THREAD

**Issue by amethley** [roleoroleo/yi-hack-Allwinner#345]
Setting RTSP audio to any value, saving and rebooting, results in RTSP audio setting reverting to "Disabled".

yi-hack-Allwinner
Firmware Version	0.2.9
Base Version	8.2.0.0A_202012041528
Model Suffix	y20ga

**Comment by roleoroleo** [comment]
When you save, does the label change to "Saved"?

**Comment by amethley** [comment]
It does.  Other settings save and persist after reboot fine.  I can confirm there is no audio stream from the camera.  Previously working fine before updating to 0.2.9 (from 0.2.3)

**Comment by roleoroleo** [comment]
Maybe they are 2 errors of the same problem.
Post the content of the file /home/yi-hack/etc/system.conf

**Comment by roleoroleo** [comment]
The file is ok.
Did you try to clean the cache of the browser (CTRL-F5)?

**Comment by amethley** [comment]
Thanks, that has updated the UI.  
However, there is no audio stream from the camera, just the H264 video stream.  I also cannot access the audio-only stream URL.   Is there a setting I've overlooked?

**Comment by roleoroleo** [comment]
The conf is ok.
What about "Codec information" in VLC?
Does audio stream appear?
![immagine](https://user-images.githubusercontent.com/39277388/159297813-e6a11f6e-9420-4fd0-9348-82e48b00d5d0.png)

**Comment by amethley** [comment]
No, I see only Stream 0. 

![image](https://user-images.githubusercontent.com/93995089/159302901-3697e4d1-8008-4dad-9e21-efa2beab459d.png)

Note: I have a second camera also updated to latest version today (y21ga on 0.2.1 yi-hack-Allwinner-v2). which is sending Stream 0 and 1.

![image](https://user-images.githubusercontent.com/93995089/159303145-efaa6b70-b9f2-4cf8-966e-024dd9257ef1.png)

**Comment by roleoroleo** [comment]
My y20ga works properly.
Maybe the update procedure doesn't complete properly.
Try to create again the sdcard overwriting all files.

**Comment by amethley** [comment]
Unfortunately, the camera is hidden in a bird nesting box so is not accessible.

Thanks for your help anyway.

**Comment by amethley** [comment]
I have audio!

![image](https://user-images.githubusercontent.com/93995089/159322340-d95e3d2f-2bf4-4c12-9c83-487b33254fee.png)

**Comment by cyraxnet** [comment]
Any chance of new build with this fix, and #347? I can't get to a Linux machine right now to build latest source.

**Comment by roleoroleo** [comment]
Yes, but I need a few days.
