### ISSUE TITLE
Dome X reboots all the time

### ISSUE THREAD

**Issue by Kenny-BC** [roleoroleo/yi-hack-Allwinner#346]
Hi guys,
today i flashed my first Yi Dome X BFUS with Firmware 8.1.0.0 to the 0.2.9 and in the web ui i only see a small icon on the snapshot site.

I flashed to 0.2.6 and makes a online Update to 0.2.9. Now i see the Snapshot, but after 1 or 2 Minutes the cam reboots. 

Can someone tell me how to find the issue?

**Comment by roleoroleo** [comment]
Enable swap space.

**Comment by Kenny-BC** [comment]
Looks great. thanks
