### ISSUE TITLE
Upload no longer works

### ISSUE THREAD

**Issue by Pmachat** [roleoroleo/yi-hack-Allwinner#347]
Hello
The upload no longer works with my iFUS (y25ga) camera. . I don't know if this is due to the upgrade to version 0.29.
Can you tell me if you have the same problem? 
Can you tell me how to downgrade to 0.28
Best regards 

NOTE: I have another model of YI camera for which the upload works

**Comment by roleoroleo** [comment]
Do you mean ftp upload?

**Comment by Pmachat** [comment]
Yes, ftp upload

**Comment by roleoroleo** [comment]
There is a recent commit.
Try if it fix your problem.
https://github.com/roleoroleo/yi-hack-Allwinner/commit/65d208820ed5b132f9902d5f0de601d8a67cac0f

**Comment by Pmachat** [comment]
to test, should I replace the 2 files on the SD card in the directory /home/hi-jack/scripts ?

**Comment by roleoroleo** [comment]
Yes.
Use ftp.

**Comment by Pmachat** [comment]
it works now after replacing the 2 files by FTP
Thank you
