### ISSUE TITLE
Wrong path for model_suffix in cgi-bin/snapshot.sh

### ISSUE THREAD

**Issue by pinguinpfleger** [roleoroleo/yi-hack-Allwinner#348]
MODEL=$(cat /tmp/sd/yi-hack/model_suffix)
must be 
MODEL=$(cat /home/yi-hack/model_suffix)

https://github.com/roleoroleo/yi-hack-Allwinner/blob/8e1d1e8bb2a24d1d1a2f50a90290884ddcf5b9ba/src/www/httpd/cgi-bin/snapshot.sh#L19

**Comment by roleoroleo** [comment]
Thank you very much for your fixes.
Copy & paste errors.
