### ISSUE TITLE
0.2.9 breaks FTP

### ISSUE THREAD

**Issue by divadiow** [roleoroleo/yi-hack-Allwinner#349]
I've got 3 Y20 Yi Home cameras. The two on 0.2.9 no longer upload to FTP. They don't even try to connect.

The one on 0.2.8 does. If I reset/unhack and flash straight to 0.2.9, still doesn't work. If I install 0.2.8 fresh and test, it works, but then breaks again after upgrading.

What logs can I retrieve that may be of help?

**Comment by roleoroleo** [comment]
I already fixed this problem:
https://github.com/roleoroleo/yi-hack-Allwinner/commit/65d208820ed5b132f9902d5f0de601d8a67cac0f

**Comment by divadiow** [comment]
oh i see, thanks.

I looked at the commits since 0.2.9 but couldn't relate the changed to ftp. oh well.

**Comment by isbkch** [comment]
So the fix will be part of the next release?
