### ISSUE TITLE
MQTT Human Detection Issue

### ISSUE THREAD

**Issue by outofsight** [roleoroleo/yi-hack-Allwinner#352]
Hello,

Using Allwinner with Yi Dome X
```
Firmware Version | 0.2.9
Base Version | 8.1.0.0A_202001211401
Model Suffix | y30qa
Serial Number | BFUS
```

Despite having configured MQTT and camera settings for Human Detection, and receiving notification in the Yi Home app, I can't see any human detection topic published under the topic I entered at the MQTT configuration page.

I tried many different times and played with settings both in the hack and in the app but no way.

I also have issue with an AllWinner-2 based camera where I sometimes only receive human_stop but never human_start

Any idea?

Thanks

**Comment by roleoroleo** [comment]
This is a know issue.
Please read this:
https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/75
and the other related issues.
