### ISSUE TITLE
Any support for Y291GA_MB_V3.1

### ISSUE THREAD

**Issue by b000p** [roleoroleo/yi-hack-Allwinner#354]
Just bought a fresh build from china dated 2021/11/22 with Y291GA_MB_V3.1 printed on the circuit board running v 9.0.35.00_202111291330 firmware.
I noticed it has TX RX 3.3 and GND, anyway to manually flash this? Happy to try whatever or be a guinea pig. 
Uploaded a picture and the backup firmware. 
Thanks

![IMG_4047](https://user-images.githubusercontent.com/47506312/163927890-30805494-8170-4efd-bebb-397f4dff9b3f.jpg)
![IMG_4048](https://user-images.githubusercontent.com/47506312/163927892-58a7d4b8-8e53-4783-979a-fa00ed22f795.jpg)
[backup.zip](https://github.com/roleoroleo/yi-hack-Allwinner/files/8510168/backup.zip)

**Comment by roleoroleo** [comment]
Try this to get access to the cam.
[y291ga_0.2.2.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner/files/8511678/y291ga_0.2.2.tar.gz)

Then I need 2-3 copies of the file /dev/shm/fshare_frame_buffer to activate rtsp.
