### ISSUE TITLE
No sound detection - 9FUS - 0.3.1

### ISSUE THREAD

**Issue by Wall-8** [roleoroleo/yi-hack-Allwinner#371]
9FUS model, y25qa, after upgrade from 0.2.9 to 0.3.1
Sound detection doesn't work anymore

**Comment by roleoroleo** [comment]
I need time to check this problem.

**Comment by Rushmed** [comment]
Also having this issue.

**Comment by roleoroleo** [comment]
Only sound? Does motion detection work?

**Comment by roleoroleo** [comment]
Please, try this library.
[ipc_multiplex.so.gz](https://github.com/roleoroleo/yi-hack-Allwinner/files/9722663/ipc_multiplex.so.gz)
Uncompress it to /tmp/sd/yi-hack/lib and reboot the cam.

**Comment by roleoroleo** [comment]
I tested it again and, with the new ipc_multiplex.so, it works for me.

**Comment by Rushmed** [comment]
Just to be sure /home/yi-hack/lib has to look like:
![image](https://user-images.githubusercontent.com/59259796/195903352-3962c9bf-3da0-4518-8b93-343830f38942.png)
and sound detection still has its own topic, right?

**Comment by roleoroleo** [comment]
> Edit: Switched rights of ipc_multiplex.so to 777, now it works. Is that as intended? Thanks.

It depends on how it was before. But 755 is enough.

> Hmm I cant seem to turn sound detection on in camera settings. If I save and refresh it is off again.

Try to refresh the cache of the browser.

**Comment by jcPOLO** [comment]
it works... but detections are not happening always like motion detection does. Sometimes, you do a noise and cam does not send any mqtt packet.

Baby crying never works.


![image](https://user-images.githubusercontent.com/9863994/196543088-6fc1be87-86ce-4f56-bbe4-a22b8b3590fb.png)

After rebooting the camera, first sound detected always works. Next ones seems like it is a random thing.

Any idea why this could be happening?

**Comment by roleoroleo** [comment]
My cam also behaves like this.
I think it's a problem of the yi software because the original app also does not receive notifications.
