### ISSUE TITLE
No more FTP access

### ISSUE THREAD

**Issue by Rushmed** [roleoroleo/yi-hack-Allwinner#372]
V0.3.1

Hi, I can not longer access my cameras per FTP.
Server is reachable but acces id denied an password ist noct accepted.
Also tried changing teh PW.
![image](https://user-images.githubusercontent.com/59259796/194719403-c86b9fbe-ab43-40f6-8365-09a2b7c953da.png)
With legecy option it works for Filezilla but WinSCP which I prefer to use the record folder has no contend.

My [yi-hack-MStar](https://github.com/roleoroleo/yi-hack-MStar) cam is still fine.

**Comment by roleoroleo** [comment]
Version?

**Comment by roleoroleo** [comment]
There are no changes in the last version about ftp.
I added sftp-server but it's not related to ftp.
Are you able to login with ssh?
Does sftp-server work?

**Comment by Rushmed** [comment]
Oh, I had SSH disabled.
After enabling SSH, SFTP is workig.

Did not know that before thanks a lot!

**Comment by roleoroleo** [comment]
I will check ftp server.
There is a problem with the authentication.

**Comment by Rushmed** [comment]
Thank you!
