### ISSUE TITLE
Yi 1080p Home IFUS not working with y25ga firmware

### ISSUE THREAD

**Issue by miquelrosell99** [roleoroleo/yi-hack-Allwinner#378]
I am trying to flash the firmware on a Yi 1080p Home IFUS, but it is not working. The camera boots with a yellow led and then changes to flashing blue and then blue. Firmware on the app still appears to be version 11.something.
Is there something I'm missing? I formatted the sd from the camera and copied all the files from y25ga inside.
After rebooting the camera and waiting, I connected the sd to the pc to see the files, and they were changed to:
![image](https://user-images.githubusercontent.com/38435442/202750578-5f7a0e37-000b-40ec-b041-bf50d642fc36.png)
Any help?
Thanks!

**Comment by roleoroleo** [comment]
> Firmware on the app still appears to be version 11.something.

Where are you reading version 11?

If the file home_y25gam exists, the cam didn't process the update.
So, probably your cam is not a y25ga.
Check the fw version with the app.

**Comment by agustinlare** [comment]
+1,  same scenario

Here's my app fw version if it's helps.

![image](https://user-images.githubusercontent.com/43295081/204404657-372556e8-0225-4c62-b680-14e5c6194d84.png)

**Comment by roleoroleo** [comment]
Your cam is a y211ga, not a y25ga.
Please check the 1st step in the procedure https://github.com/roleoroleo/yi-hack-Allwinner#install-procedure:
1. Check if your cam is supported in the "Supported cameras" section and note the file prefix.
