### ISSUE TITLE
v0.1.6 - http://IP:8080/cgi-bin/snapshot.sh?watermark=no :: reset cam

### ISSUE THREAD

**Issue by wadalino** [roleoroleo/yi-hack-Allwinner#38]
When try to get snapshot without trademark the device is being reset.
Usualy (with trademark) works fine.

![imagen](https://user-images.githubusercontent.com/15080402/82117546-f9205b00-9770-11ea-86bb-c05500869370.png)

**Comment by roleoroleo** [comment]
https://github.com/roleoroleo/yi-hack-Allwinner/issues/5
