### ISSUE TITLE
Image rotate

### ISSUE THREAD

**Issue by WMP** [roleoroleo/yi-hack-Allwinner#386]
In the settings there is an option to rotate the image by 180°, could you add an option to rotate the image by 90° and -90° ? I tried to do it in Synology Surveillance Station, but I guess ONVIR doesn't return the information that the image can be rotated, because I have inactive image rotation options, and in the documentation https://kb.synology.com/en-nz/SurveillanceStation/help/SurveillanceStation/optimization_advanced?version=9 it says that: 

> Depending on the specifications, the actual settings applicable to each individual camera may vary by brand or by model. Certain features may not be available if they are not supported by the camera in question.

**Comment by roleoroleo** [comment]
Sorry but it's not possible.
Rotate option comes from the yi fw and only 180° is available.
