### ISSUE TITLE
Upgrade firmware.

### ISSUE THREAD

**Issue by MrPatate87** [roleoroleo/yi-hack-Allwinner#397]
since the last joyr update (0.3.3) my damera seems to switch between day mode and night mode regularly (little audible click in a regular way about every two or three minutes).
however, it remains quite accessible via the web interface and its recordings via the rtsp stream are cut off and very short (a few seconds at best).
How can I remedy this?

**Comment by roleoroleo** [comment]
Maybe the cam is in reboot loop?
Run a ping and check if the cam remains connected.

**Comment by MrPatate87** [comment]
Yes that's exactly it, my recordings are only a few seconds long and the camera restarts at regular intervals (a few minutes)

**Comment by roleoroleo** [comment]
If you are using snapshot features, please enable swap space.

**Comment by MrPatate87** [comment]
I do not use this feature...

**Comment by roleoroleo** [comment]
Make sure you disable it:
![immagine](https://user-images.githubusercontent.com/39277388/229113426-3d850b9b-461d-4d0b-a865-bc0653449c34.png)

**Comment by MrPatate87** [comment]
Snapshot was already disable.
But i also disable Snapshot for recordes vidao and si ce this my cam have now 9 min of upload time, à record si ce my last update 😊
Thanks for your help and this help full project !
![Screenshot_20230331-141720](https://user-images.githubusercontent.com/64218540/229118425-1f44a837-125e-4e8c-af12-59d0c57435c6.png)

**Comment by MrPatate87** [comment]
Seems this help but it's not perfect, cpu usage still high and camera revoit from time to time
![Screenshot_20230401-072851](https://user-images.githubusercontent.com/64218540/229267439-9563c06a-422e-4e00-8225-d2e2f9ee244d.png)

**Comment by roleoroleo** [comment]
I think it's a memory problem.
Try to disable all unused features.

**Comment by roleoroleo** [comment]
I don't know how good your knowledge is about electronic, but if you want and if you are able, you could try to connect a serial cable.
[I don't know how high your knowledge is](https://github.com/roleoroleo/yi-hack-Allwinner/wiki/Dump-your-backup-firmware-(serial-cable))

**Comment by MrPatate87** [comment]
I do not have enough knowledge for this, but i do not have this rando reboot with other update before.....
