### ISSUE TITLE
Adjust bitrate

### ISSUE THREAD

**Issue by zZjessahZz** [roleoroleo/yi-hack-Allwinner#40]
Hi roleoroleo,
Thank you for bringing yi-hack to the allwinner chipset!

Do you think there is a possibility to adjust the bitrate of video stored in the sdcard?
I wasn't able to find a config file on the camera related to that.

Thank you for your insight!

**Comment by roleoroleo** [comment]
No, sorry. It's not possible.
We don't have control about the encoding phase.

**Comment by zZjessahZz** [comment]
Oh that's too bad. Is this because this part is hidden in a code blob? (I mean like the little part of the SOC firmware on the raspberry pi thats not open source.)

**Comment by roleoroleo** [comment]
Yes, it's inside the rmm application, that is closed source.

**Comment by zZjessahZz** [comment]
Okay I understand, thank you for your explaination roleoroleo.
Have a nice day !
