### ISSUE TITLE
[Feature request] OSD Positioning (default offset)

### ISSUE THREAD

**Issue by iointerrupt** [roleoroleo/yi-hack-Allwinner#401]
Just upgraded all my 9FUS from 0.3.3 to 0.3.4.  Almost instantly I am seeing better connectivity and less RTSP stuttering.

Really liking the OSD for the time.  Would it be possible to change the location of the OSD using an X, Y offset from top left perhaps?

**Comment by roleoroleo** [comment]
No sorry. It's not possible.
This setting is not available in the Yi configuration.

**Comment by iointerrupt** [comment]
Understood.  Thank you.

**Comment by iointerrupt** [comment]
Closing.
