### ISSUE TITLE
Hardware donation

### ISSUE THREAD

**Issue by roleoroleo** [roleoroleo/yi-hack-Allwinner#403]
I'm having trouble maintaining support for all cams because I have very few models available. Especially older ones that are no longer available for purchase.
If you have cameras that you don't use anymore (maybe broken) and you want to get rid of them, please send to me.

**Comment by essys** [comment]
Can you provide a list of cams you need to continue to support such models?
Or vice versa, a list of the cams that you have.
The destination country would be Spain?

**Comment by roleoroleo** [comment]
About allwinner I have just a y20ga.

**Comment by roleoroleo** [comment]
Good idea.
I will do it.

**Comment by essys** [comment]
Please do so, even though I already donated a few euros last year, I would like to support you in the further development of this great mod and ideally extend the device support.
