### ISSUE TITLE
Topics Prefix for remote configuration not working

### ISSUE THREAD

**Issue by snakuzzo** [roleoroleo/yi-hack-Allwinner#404]
Hi, I've two YI Camera 1080p (y20ga) with latest firmware and latest hack (v.0.3.4).
I'm trying to set "Topics Prefix for remote configuration", but when I set and save my topic, I always see default settings...

![image](https://github.com/roleoroleo/yi-hack-Allwinner/assets/7205371/9454dad3-f020-4c15-9419-b1969bd70a6f)

Tried to reboot...same result...on both cameras

**Comment by roleoroleo** [comment]
Maybe a js problem.
Try to clean the cache of the browser.

**Comment by snakuzzo** [comment]
Cleaned cache...tried using Chrome, Firefox, Edge...same result

**Comment by roleoroleo** [comment]
Sorry, I temporarily removed this feature in this commit: https://github.com/roleoroleo/yi-hack-Allwinner-v2/commit/b6fad82867cead2ea10834fa2a9cb5b548b5b4e8
In this moment it's not working.
I will restore it in the next release.

**Comment by snakuzzo** [comment]
Ok. Thak you!

**Comment by snakuzzo** [comment]
Hi @roleoroleo.
Any news about this feature ?

**Comment by roleoroleo** [comment]
Fixed here: https://github.com/roleoroleo/yi-hack-Allwinner-v2/commit/c5ad71bd08de718e41b7e73ceaa04a00eb7499e2
