### ISSUE TITLE
Camera unresponsive after firmware update from 0.3.4 to 0.3.6

### ISSUE THREAD

**Issue by othyro** [roleoroleo/yi-hack-Allwinner#408]
After updating the camera firmware from 0.3.4 to 0.3.6, it's unresponsive over the network. Using the [configure wifi](https://github.com/roleoroleo/yi-hack-Allwinner-v2/wiki/Change-WiFi-credentials-(deprecated)) script doesn't seem to work either. The orange LED remains lit.

If I remove the SD card and hold the reset button, it goes through reset mode and I hear, 'Waiting to connect...'. If I reboot it, I can hear the shutter clicking twice before it awaits a connexion. Reinserting the SD card before replugging in the USB cable, leaves the orange LED lit, I hear no shutter, and the camera doesn't connect to the WiFi.

Not sure how to proceed. I'm not using the app nor want to do so. Here's what the status page looked like after I did the initial flash some weeks ago:
![signal-2023-07-05-204427_002-crop](https://github.com/roleoroleo/yi-hack-Allwinner/assets/12114422/aeb6c6b5-dd0b-48a2-9e74-fa6a25ec2c40)
I want to upgrade the firmware on the other cameras too, since I have two more of this model. However, I don't want the same to happen again. What logs would you like to see?

**Comment by roleoroleo** [comment]
Please, follow the unbrick procedure.
https://github.com/roleoroleo/yi-hack-Allwinner-v2/tree/master/unbrick
using the "hacked" option.
And apply again the hack.

**Comment by othyro** [comment]
Thanks. It seems to have been my fault for not having cleared all the motion events before updating it. The camera's working properly now.

**Comment by othyro** [comment]
![image](https://github.com/roleoroleo/yi-hack-Allwinner/assets/12114422/a5926a0e-206f-4cc4-bfbc-ae469d9dfd30)
On one of my other cameras with this firmware, I'm not seeing the upgrade version although several are available. Is there any way to force the update via the CLI?

**Comment by roleoroleo** [comment]
Yes, you can download the file manually and copy it to the root folder of your sd card.
Then, rename it suffix_x.x.x.tgz, for example y20ga_x.x.x.tgz
Finally reboot the cam.

**Comment by othyro** [comment]
The _/_ partition is mounted read-only. I tried with the file in _/home/yi-hack_, _/tmp_, _/tmp/sd_, and _/tmp/sd/yi-hack_. The device didn't update in any of those cases. What's the correct path if I'm connected via SSH?

**Comment by roleoroleo** [comment]
The correct path is /tmp/sd where the cam should mount your sd card.
If the sd card is mounted read only, remove it and try a file system check with a PC.
Then try again.

**Comment by othyro** [comment]
I reuploaded the file to _/tmp/sd_, rebooted, and  it's running 0.3.4 still. Any advice on how to proceed?

**Comment by roleoroleo** [comment]
After uploaded the file and rename, you have to click "Upgrade firmware" in the web gui.
