### ISSUE TITLE
Disabling "Black and White" mode

### ISSUE THREAD

**Issue by iointerrupt** [roleoroleo/yi-hack-Allwinner#411]
Is there a way to prevent the camera from switching to black and white mode when the image is too dark? The issue is I have a couple of external motion sensors that turn the light on when motion is detected so I do not need the black and white mode on the camera.  I've disabled the infrared sensor from setting but that itself doesn't prevent the camera from switching bw mode.

**Comment by roleoroleo** [comment]
No sorry, it's not possible.

**Comment by iointerrupt** [comment]
No Worries.  Figured that was something deeply baked into Yi/Kamis firmware.  Thank you.
