### ISSUE TITLE
Unbrick Cam

### ISSUE THREAD

**Issue by neddyuk** [roleoroleo/yi-hack-Allwinner#414]
I am looking for the solder points to solder a usb connection onto the pads of the Yi Dome X cam. I saw someone had sucess on [this page](https://github.com/roleoroleo/yi-hack-MStar/issues/262) bbut they seem to have changed the mainboard and chip now so the pads arent labelled . Anyone have any ideas on the location UART pads? images below 

![IMG_20230908_152723_1](https://github.com/roleoroleo/yi-hack-Allwinner/assets/73346581/faf792f6-e345-4701-8666-2734632db279)

![IMG_20230908_153040](https://github.com/roleoroleo/yi-hack-Allwinner/assets/73346581/cedfc789-5500-480d-a139-310ed27e5357)

**Comment by roleoroleo** [comment]
You could try to follow UART pins.
https://www.senslab.com/uploads/20220406/da212226e7ec445d6b7127a27101d262.pdf

**Comment by neddyuk** [comment]
> You could try to follow UART pins. https://www.senslab.com/uploads/20220406/da212226e7ec445d6b7127a27101d262.pdf

Not sure which ones those would be to start with. Otherwise yea i could use the continuity mode on the multimeter. Seems the board is from 2019 so has been out a while has it not be stumbled across before?
