### ISSUE TITLE
allwinner v2 rtsp stream

### ISSUE THREAD

**Issue by sander816** [roleoroleo/yi-hack-Allwinner#416]
i installed v2 on a yihome cam. On vlc the stream url works fine. Searchuing in my nvr for the camera is fine too, but it can not connect to the stream. I have set no password or so.
It wants to connect to port 80 with onvif, but no image. Is there some default otger password?

**Comment by roleoroleo** [comment]
Unfortunately the onvif protocol is not so "standard".
Please try the official tool Onvif Device Manager and test if the cam works.
If it works, it depends on your nvr.
