### ISSUE TITLE
v0.37 audio fail

### ISSUE THREAD

**Issue by ibratos** [roleoroleo/yi-hack-Allwinner#419]
Firmware Version | 0.3.7
Base Version | 12.2.0.2_202212191129
Model Suffix | y20ga
Serial Number | 00009FUS

After upgrade to v.37 audio doesn't work.
Whith kami app it works.
Rtsp: alternative server On
Rtsp stream low
Rtsp audil  aac

From VLC
rtsp://IP/ch0_1.h264   Login Ok. Video Ok, Audio No Ok
rtsp://IP/ch0_2.h264   Login Ok, Not responde.

**Comment by ibratos** [comment]
Update info
Without rtsp alternative (live555) works fine video and sound.

**Comment by roleoroleo** [comment]
I will check the code.

**Comment by roleoroleo** [comment]
What format are you using with the alternative server?
aac? ulaw? ...

**Comment by ibratos** [comment]
AAC

**Comment by roleoroleo** [comment]
Please try this binary:
[rtsp_server_yi.gz](https://github.com/roleoroleo/yi-hack-Allwinner/files/13308435/rtsp_server_yi.gz)

**Comment by ibratos** [comment]
Hi, it doesn't change.
This binary with AAC doesn't give audio, in both urls ( ch0_1.h264 and ch0_2.h264)
regards

**Comment by roleoroleo** [comment]
Tested now with the same model (y20ga fw12) and it works.
Which client are you using?
Please try to use ffmpeg and send me the log:
`ffmpeg -i rtsp://IP_CAM/ch0_0.h264 test.mp4`

**Comment by roleoroleo** [comment]
Maybe I found.
Try this:
[y20ga_0.3.7.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner/files/13319727/y20ga_0.3.7.tar.gz)

**Comment by ibratos** [comment]
Hi, with this new release it works

**Comment by drakodga** [comment]
Hi. Can you upload new 0.38 version with audio fix? Thank you!

**Comment by roleoroleo** [comment]
I'm far from a new release.
Which model do you have?

**Comment by drakodga** [comment]
Sorry for the delay. The information you have requested from me is this:
![image](https://github.com/roleoroleo/yi-hack-Allwinner/assets/7260729/3750bc64-f4df-4053-892b-eac5e8c72fbe)

**Comment by roleoroleo** [comment]
You can user the version posted above.

**Comment by drakodga** [comment]
I tried it, but with same result. Finally, i'am in previous version that it's fine.
