### ISSUE TITLE
Yi1080 BFUSY31 - restarting after 10 sec of activity - loop

### ISSUE THREAD

**Issue by lukemikeluke** [roleoroleo/yi-hack-Allwinner#420]
Hi everyone. 
My camera is stuck in a loop where it powers on, works for 10 seconds and then restarts. I's a result of running unhack on it. 
As I can log in to www interface for 10 seconds I tired everyghing (disabling snapshot etc.).
Running unbrick also did not work (maybe I have a wrong backup files or build it in a wrong way). Could anyone help me please. Highly appreciated. Thank you.

**Comment by divadiow** [comment]
oh. I have this right now. unhacked. i've soldered it up and have ssh in. how did you fix?

**Comment by roleoroleo** [comment]
What's your model suffix?
