### ISSUE TITLE
9FUS with 0.3.7 - No audio.  Tried on Zoneminder, IP Cam Viewer and VLC.

### ISSUE THREAD

**Issue by edgararroyo** [roleoroleo/yi-hack-Allwinner#422]
Not sure what all you need to troubleshoot, but I upgraded to 0.3.7 and lost audio.  Zoneminder is still not recording any audio. Before I could connect to audio stream on VLC and I could also connect with IP Cam Viewer and listen to audio.  Any advise?

**Comment by ibratos** [comment]
Hi, Check this:  https://github.com/roleoroleo/yi-hack-Allwinner/issues/419
