### ISSUE TITLE
YI X dome (y30qa_0.3.7) - two identical cameras - one not responding

### ISSUE THREAD

**Issue by Petengy** [roleoroleo/yi-hack-Allwinner#426]
Hi everyone
I'll start by congratulating you roleoroleo for the splendid work.
I tested your firmware and I must say that everything went ok on the first camera, even on the second (same network but connected with repeater in mesh network) apparently... but on this one (correctly integrated like the first in HA) none of the functions has an effect (for example switch on/off camera or switch on/off cruise, etc.), only video streaming works.

The log file does not present any anomalies (it seems to me).

Some idea ?

D.

**Comment by roleoroleo** [comment]
Did you configure properly mqtt?

**Comment by Petengy** [comment]
..you know when you don't see the elephant in the room?

![elefante_nella_stanza2](https://github.com/roleoroleo/yi-hack-Allwinner/assets/65110049/81a8a7da-0390-47a3-9df0-a2649997e028)
