### ISSUE TITLE
Online FW upgrade not working?

### ISSUE THREAD

**Issue by roleoroleo** [roleoroleo/yi-hack-Allwinner#427]
Online FW update no longer works.
busybox needs to be updated.
In the meantime, use the manual firmware update procedure:
https://github.com/roleoroleo/yi-hack-Allwinner/wiki/Manual-firmware-upgrade

**Comment by snakuzzo** [comment]
It doesn't work.
I'm on 0.3.6 and in Maintenance page there is I click on FIRMWARE UPGRADE I've got `Unable to download firmware file`

![image](https://github.com/roleoroleo/yi-hack-Allwinner/assets/7205371/6f123aa2-87f6-48c2-9c48-6347c73bfc37)

![image](https://github.com/roleoroleo/yi-hack-Allwinner/assets/7205371/4327e09c-356e-47d5-ae94-723df5c06349)

**Comment by tsedgwick1** [comment]
Did you find a solution ? I have the same error message with v0.3.7 version and camera Yi 1080p Home BFUS

**Comment by essys** [comment]
In the linked [manual upgrade process](https://github.com/roleoroleo/yi-hack-Allwinner/wiki/Manual-firmware-upgrade) it says:
_Rename the file replacing the version numbers with the 'x' char (y20ga_0.3.7.tgz -> y20ga_x.x.x.tgz)_

It looks as if your file still contains version designations.

**Comment by snakuzzo** [comment]
Sorry, I've read wrong :D

**Comment by Madaraxa** [comment]
Still no online Update possible?
I cant remember if it bricks the cam by trying or just nothing happens :)
I am on 0.3.8 and want to get the todays new 0.3.9.

**Comment by Madaraxa** [comment]
I just tried it and both my cams updated from 0.3.8 to 0.3.9 without any problems.
So @roleoroleo close this as fixed?

**Comment by oopiicaa** [comment]
It worked for me too.

**Comment by frosty-geek** [comment]
update from 0.3.7 is still broken, will do a manual update now
