### ISSUE TITLE
Incorrect time for Motion Events

### ISSUE THREAD

**Issue by Svartskog** [roleoroleo/yi-hack-Allwinner#429]
The correct time/date is displayed under "Status". However, as soon as a video record is triggered, the video always has an incorrect time stamp, always 2 hours earlier.

The correct time zone is set in the menu item Configurations --> Timezone
As soon as a video is recorded, e.g. at 12 o'clock, it is displayed under Motion Event at 10 o'clock and so on.

Have I forgotten a setting?

**Comment by LZsolt75** [comment]
The same situation here. model: y20ga BFUSY31AYZDYA5200308. The two-hour difference came after the switch to summer time, until then it was one hour difference.

**Comment by roleoroleo** [comment]
> the video always has an incorrect time stamp, always 2 hours earlier.

Where? Webgui? Yi app? Other?

> it is displayed under Motion Event at 10 o'clock and so on.

Which column is wrong? "Date & Time" or "Directory name"?
Are you using the option "Enable time OSD"?

**Comment by Svartskog** [comment]
Yi App: Time ok
Webgui Status Page: Time ok
Webgui Motions Events Page: Date is ok, Time -2 hours //  Directory name: Date is ok, Time-2 hours
![2024-04-06 20_48_33](https://github.com/roleoroleo/yi-hack-Allwinner/assets/95505049/ad844df4-a146-4123-b51c-6cc9f6900475)


Enable time OSD is off

**Comment by roleoroleo** [comment]
I thought I had already solved this problem.
Try this version, please:
[y25ga_0.3.8.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner/files/14896536/y25ga_0.3.8.tar.gz)

**Comment by Svartskog** [comment]
a fix in the same version? since I already had the .3.8 on it
and a new Option? 
![Event](https://github.com/roleoroleo/yi-hack-Allwinner/assets/95505049/0493260b-17df-4c13-8a52-b8e667d6c4ad)
But many thanks! now everything fits :)
![time](https://github.com/roleoroleo/yi-hack-Allwinner/assets/95505049/1b914a50-edef-4cc4-bacc-4d8edd9cbe87)

**Comment by roleoroleo** [comment]
It's a beta version, the version number is not important.

**Comment by dallas6672** [comment]
Just updated to version y20ga_0.3.9. Noticing that NTP will not sync when the cloud is Disabled. System time never updates from the Default (Fri Apr 17 20:25:35 GMT 2020)

If I enable the Cloud and then block all Ports at the firewall except NTP, time is still able to sync. But, the time is off on the Web Index page and checking "date" from command line.

Says: Wed Jun 26 06:48 EDT 2024
Actual: Wed Jun 26 11:39 EDT 2024
