### ISSUE TITLE
Cannot save onvif settings using web ui

### ISSUE THREAD

**Issue by MB-Finski** [roleoroleo/yi-hack-Allwinner#433]
Pressing "Save configuration" in the onvif settings page is not working. I.e. nothing happens and the settings changes are not saved. 

Tested on 9FUSY and BFUSY. Yi-hack 0.3.9.

**Comment by roleoroleo** [comment]
Please, try to clean the cache of the browser.
The last release contains a change in the js part.

**Comment by MB-Finski** [comment]
Yeah that was it. Thanks!
