### ISSUE TITLE
Service Camera Snapshot not working Home Assistant

### ISSUE THREAD

**Issue by ManiSulClude** [roleoroleo/yi-hack-Allwinner#434]
Recalling service: Camera.Snapshot not work.
The image file is created but the size is always 0B

**Comment by roleoroleo** [comment]
Does it work if you call it from the web gui?
I tested it now with ha and it works.
Have you tested it with a correct external dir?
Do you have the permissions to write to this folder?

**Comment by ManiSulClude** [comment]
in attachment the screenshot of service recal from HA dev tool
<img width="905" alt="3" src="https://github.com/user-attachments/assets/4da5014e-f07b-4cd6-9cc9-0e61bde95cb7">

What do you mean with "Does it work if you call it from the web gui?"

**Comment by roleoroleo** [comment]
Maybe a "/" is missing before tmp?
Open this url:
`http://IP-CAM/?page=snapshot`
using the IP of your cam.

**Comment by ManiSulClude** [comment]
Hi,

I verified in the web UI and the snapshot feature was disabled.
I enabled it and now it works.
I only noticed that the snapshot in hi res take so much time (about 3 seconds) and to avoid timeout in HA automation I must keep active the "Force low res snapshot feature".

We can close the issue

Best regards
Cristian

**Comment by roleoroleo** [comment]
Yes, I know. The snapshot is very expensive in terms of cpu and memory.
So, it requires time.
