### ISSUE TITLE
Can't Save onvif settings

### ISSUE THREAD

**Issue by basdejong95** [roleoroleo/yi-hack-Allwinner#441]
Hi,

using the latest firmware, i am unable to save any onvif settings. When i press the save button, just nothing happens! 

Other than that, thanks for the Yi Hack firmware, using it since 2021 already! 

Kind regards,
Bas

**Comment by roleoroleo** [comment]
Please, try to clean the cache of your browser.
I changed the js script.

**Comment by basdejong95** [comment]
Ahh that did the trick. Thanks!
