### ISSUE TITLE
Any change in status of rtsp for Hi3518e chipset

### ISSUE THREAD

**Issue by tunerooster** [roleoroleo/yi-hack-Allwinner#445]
Is there any change in the status of the open source RTSP server used in v5 for the Hi3518e chipset?
I see back in 2020 it was pretty much ruled out, but wanted to check if anything has changes since then.
I have 3 old Yi Outdoor 1080p cameras (based on the Hi3518e chipset) which are currently unused and pretty much useless to me without RTSP.

Any suggestions are also welcome.

Thanks!

**Comment by roleoroleo** [comment]
Check Yi hack v5: https://github.com/alienatedsec/yi-hack-v5

**Comment by tunerooster** [comment]
That look promising!  Thanks roleoroleo!
