### ISSUE TITLE
Wifi often lost; SD card full

### ISSUE THREAD

**Issue by Xandrios** [roleoroleo/yi-hack-Allwinner#45]
I've noticed two weird things.

Over the last few days I've left my play-around-with camera unplugged. When I plugged it back in yesterday it had lost the Wifi settings and required to be re-paired with the app. Considered it a fluke until the exact same thing happened again today. 

Now, every time that I temporarily unplug it (with the SD card inserted) it loses the Wifi settings. It does seem to be related to the SD card, though I'm not sure in what way. After resetting the Wifi I'm able to unplug it, even with the SD card in there, without problems.

Do we know what causes the Wifi settings to be lost? When not connected I cannot check the state of the /tmp/wpa_supplicant.conf file. Who is responsible for putting that file there? (assuming /tmp/ is empty at boot and the file needs to be put there at startup). Is there some master version of that file somewhere that can also be reset using the pinhole button?

Secondly I noticed the SD card to be almost full, while I had set it to always keep 10% free. Looking at the system.sh script this does not work for me...at all. Does it work for others?

For me cron does not even exist: 
> /usr/sbin/crond -c /var/spool/cron/crontabs/
> -ash: /usr/sbin/crond: not found

And also the cleanup script itself does not seem to work, as it relies on 'df -h'...while the df command that is installed does not seem to know that -h option. Its a little odd that I am running into this issue but others seemingly not?

> /home/yi-hack/script/clean_records.sh 10
> 90
> df: unrecognized option: h

**Comment by roleoroleo** [comment]
> 
> 
> Who is responsible for putting that file there? (assuming /tmp/ is empty at boot and the file needs to be put there at startup).

It's not clear but probably it's a binary from the original yi firmware.

> Is there some master version of that file somewhere that can also be reset using the pinhole button?

No.

> Secondly I noticed the SD card to be almost full, while I had set it to always keep 10% free. Looking at the system.sh script this does not work for me...at all. Does it work for others?

There is a problem. Probably I accidentally overwrote this file with the MStar versione.
I will correct it in the next release.
If you want to correct it now, change the crond path with "/home/yi-hack/usr/bin" and remove -h from df command

**Comment by Xandrios** [comment]
Thanks. No problems, I have created a cleanup script specifically for my environment since I have additional directories to cleanup (record, record_motion, record_snapshots, etc).
