### ISSUE TITLE
Can you write the example for Streaming URL's....

### ISSUE THREAD

**Issue by hocker96** [roleoroleo/yi-hack-Allwinner#50]
... into the webinterface for a better using. I searching ever on git for URL's

So long...

**Comment by roleoroleo** [comment]
The readme describes the url.
Both rtsp url and snapshot url.
About we interface, do you mean url like rtsp://IP_CAM/ch0_0.h264  or directly the stream inside a page?

**Comment by hocker96** [comment]
Yes, thats enough, for every protokoll an example.
For perfect is to integrate the local ip and hostname. But it"s good to copy the text string into the webgui.

**Comment by roleoroleo** [comment]
I will add the url to the next release.
