### ISSUE TITLE
cedarx.conf

### ISSUE THREAD

**Issue by murigny** [roleoroleo/yi-hack-Allwinner#51]
hello.
i'm looking for parameters on my yi cam hacked and i saw a strange thing:

cedarx.conf have a parameters with syntax error:
[paramter] --> parameter ?
max_start_play_chache_size = 153600 --> chache or cache ? 
partition is read only, so i can't try to fix
what do you think about ?

**Comment by roleoroleo** [comment]
Probably it is not used.
There are a lot of unnecessary files.
For example ts.conf.

**Comment by murigny** [comment]
Thanks for info.

Other question:
Can we use onvif without rtsp enable ? I's seem that it doesn't work for me
