### ISSUE TITLE
wiki update

### ISSUE THREAD

**Issue by pbanj** [roleoroleo/yi-hack-Allwinner#54]
compiling works on windows 10 with the ubuntu wsl. you just need to make a couple changes
this
`apt-get install git unzip build-essential bison++ bisonc++ libbison-dev autoconf autotools-dev automake libssl-dev zlibc zlib1g-dev libzzip-dev flex libfl-dev yui-compressor closure-compiler optipng jpegoptim libtidy5deb1 node-less sassc sass-spec libhtml-tidy-perl libxml2-utils`

needs to be changed to 

`sudo apt-get install git unzip build-essential bison++ bisonc++ libbison-dev autoconf autotools-dev automake libssl-dev zlibc zlib1g-dev libzzip-dev flex libfl-dev yui-compressor closure-compiler optipng jpegoptim libtidy5 node-less sassc sass-spec libhtml-tidy-perl libxml2-utils`

before doing it you need to do `sudo apt-ge update`

and then you just have to use sudo for these commands

- `mkdir -p /opt/yi/toolchain-sunxi-musl` so `sudo mkdir -p /opt/yi/toolchain-sunxi-musl`

- `cp -r lindenis-v536-prebuilt/gcc/linux-x86/arm/toolchain-sunxi-musl/toolchain /opt/yi/toolchain-sunxi-musl/` so `sudo cp -r lindenis-v536-prebuilt/gcc/linux-x86/arm/toolchain-sunxi-musl/toolchain /opt/yi/toolchain-sunxi-musl/`

- `./scripts/compile.sh` so `sudo ./scripts/compile.sh`

this one im not sure if it is needed but i did it anyways 
`./scripts/pack_fw.all.sh` so `sudo ./scripts/pack_fw.all.sh`

took about 20min to compile with the orig wsl I'm not on 2004 yet. my cpu is a ryzen 2700x

I flashed the resulting build to one of my cameras and it worked

**Comment by roleoroleo** [comment]
Thank  you for your feedback.
I will change the wiki asap.
