### ISSUE TITLE
Yi iot 1080p outdoor

### ISSUE THREAD

**Issue by fernandodpr** [roleoroleo/yi-hack-Allwinner#56]
Firts of all It's my fisrst time publishing on github so sorry If I'm not in the correct tab. 
A few weeks ago received an Yi IOT camera that I read that haves the Allwinner  chipset. [Link to the product ](https://es.aliexpress.com/item/4000120325499.html?spm=a2g0s.9042311.0.0.274263c0N5u4wV). 

I would like to work to make the camera compatible with the wi-hack firmware. 

Firmware version: 7.1.00.19a_201910181012
I found a github [page](https://github.com/rage2dev/YiOutdoor) made by @rage2dev that explains how to load a custom firmware. 

So, I offer myself to test the installation in my camera. Should I install the firmware renaming the .tgz file? Do you think that more adjusting would be necesary? 

Edit1: Managed to get telnet acces

**Comment by pbanj** [comment]
Prob best to open it up and see what soc it actually has

**Comment by roleoroleo** [comment]
If you have telnet access, try

cat /proc/cpu

**Comment by matteopiccioni** [comment]
I'd like to have Yi1080p outdoor support
Your firmware has mqtt and webservices support that are great features
TheCript0 fw has not mqtt and webservices.
Thanks

**Comment by fernandodpr** [comment]
Finally I managed to continue the investigation.  I've just uploaded some photos of the inside, can't find anything related to the realtek chipset googling. 

The output of _cat /proc/cpu_ is:

```
system type             : RLX Linux for IPCam Platform
machine                 : Unknown
processor               : 0
cpu model               : Taroko V0.2  FPU V0.1
BogoMIPS                : 497.66
tlb_entries             : 64
mips16 implemented      : yes
```





![Upload pixelated](https://user-images.githubusercontent.com/44924063/85702836-14bb4180-b6df-11ea-9fb0-5f2f5dc81e4c.jpg)
![A chip](https://user-images.githubusercontent.com/44924063/85702901-243a8a80-b6df-11ea-9983-8bdbe636d983.jpg)
![Another chip](https://user-images.githubusercontent.com/44924063/85702944-2e5c8900-b6df-11ea-85bf-f5f5cd337c26.jpg)

**Comment by roleoroleo** [comment]
Sorry but this platform is not supported.
This cam needs another hack.
