### ISSUE TITLE
Can.t change password/ Home Assistant FTP not working

### ISSUE THREAD

**Issue by Antoni-Czaplicki** [roleoroleo/yi-hack-Allwinner#60]
When he tries to change the password using ssh he gets this message:
`root@yi-6fe1:~# passwd`
`Changing password for root`
`New password: `
`Retype password: `
`passwd: /etc/passwd: Read-only file system`
`passwd: can't update password file /etc/passwd`

**Comment by murigny** [comment]
you can't change root password, it's on read only partition of yi firmware.

**Comment by Czapla-dev** [comment]
In this case, how do you change the password? I'm trying to follow the instructions at Home Assistant page.
https://www.home-assistant.io/integrations/yi/#changing-the-ftp-password

**Comment by murigny** [comment]
You can enable username/password by using yi-hack web page. It will activate authorisations for ftp,ssh,telnet,rtsp and http ( same for all )

**Comment by roleoroleo** [comment]
The username/password setting works only for http, rtsp and onvif.
ssh and telnet use passwd but rootfs is read only, so you can't change it.

**Comment by roleoroleo** [comment]
Instructions at ha site are for an older version/hack.

**Comment by Czapla-dev** [comment]
I tried without changing the password, but ftp has no video, the image via rtsp but the preview does not work ...

**Comment by roleoroleo** [comment]
Don't use yi integration on ha. It's for an older version.
See the wiki.

**Comment by Catfriend1** [comment]
Meanwhilst, a PR has been merged which allows to set the ssh password from the web ui.
