### ISSUE TITLE
Firmware downgrade in 9FUSY31 from 8.2.0.0A_201912270941 to 8.2.0.0A_201912121707

### ISSUE THREAD

**Issue by spamsool** [roleoroleo/yi-hack-Allwinner#62]
Is it possible to downgrade the firmware from 8.2.0.0A_201912270941 to version 8.2.0.0A_201912121707 in the 9FUSY31 Camera?
I am having problems with video quality and low bitrate and I would like to try the older fw. Could  anyone help me to downgrade this fw? I do not have the older version unfortunately. Thank you in advance.

**Comment by roleoroleo** [comment]
We need a dump of the flash with the older firmware.
I don't have it.
If someone is able to dump...
