### ISSUE TITLE
How to reset camera

### ISSUE THREAD

**Issue by zatarra** [roleoroleo/yi-hack-Allwinner#66]
Can anyone tell me how to reset the camera?

It looks like a weird question given that no one else asked the same thing (therefore I assume the answer should be sitting right in front of me), but I'm having a hard time resetting it.

I've configured the camera, but now I need to move to another place that has a different wireless network. How can I reset it? 

I tried to press the reset button with and without the sd card in it. I tried to enable and disable cloud (and repeat the same procedure) and I also tried to find a factory reset binary.

Do I need to flash it with the original firmware? 

Firmware Version | 0.1.6
Base Version | 8.2.0.0A_201912270941
Model Suffix | y20gam   (9FUS) Yi Home 1080p

**Comment by roleoroleo** [comment]
You don't need the original fw because the original fw is under the hack.
Switch off the button "Disable cloud" and reset the cam as if it were original.
Repeat the pairing with the app and reconfigure it normally.
At the end, switch on again "Disable cloud", if you want.

**Comment by zatarra** [comment]
You are absolutely right. I think the issue here is that I was not pressing long enough. It worked just like you said!
