### ISSUE TITLE
How do I use latest unreleased commits?

### ISSUE THREAD

**Issue by divadiow** [roleoroleo/yi-hack-Allwinner#71]
Sorry for the silly question but how do I use all the changes since the 0.1.6 release?

**Comment by roleoroleo** [comment]
If you want to use the last commits you have to build your own hack.
See the wiki.

**Comment by divadiow** [comment]
ahh. lol. it's all there. thanks

**Comment by divadiow** [comment]
I guess this a general question about releases. How does one decide when to draw a line under enough commits to make a new release?

**Comment by roleoroleo** [comment]
There isn't a rule.
At the moment, I'm testing the new RTSP solution (I restored the old method because the new one had problems).
Then I will release a new version.

**Comment by divadiow** [comment]
nice.

appreciate your efforts!
