### ISSUE TITLE
camhash?  No RTSP tab 

### ISSUE THREAD

**Issue by Merlynda** [roleoroleo/yi-hack-Allwinner#73]
Yi home 1080p BFUSY311P4ZF3X200306. Yi hack allwinner worked. I can get to web interface configuration. But there is no RTSP tab. I have RTSP server radio button enabled. 
How do I get camhash so I can donate and stream RTSP? Thank you

**Comment by roleoroleo** [comment]
You don't need to donate.
rtsp implementation is open source.
Simply try and use it.

But if you want to donate follow the link at the bottom of the main page. :)

**Comment by Merlynda** [comment]
Hummm I typed 

rtsp://MyCamIP/ch0_0.h264 

Into my browser and it worked. 

Plus I used http://MyCamIP/8080/cgi-bin/service.sh?name=RTSP&action=START&param1=HIGH

As you can tell I don’t have a clue what I am doing. 

Now I am going to try to get it to work with

https://channelstore.roku.com/details/143683/ip-camera-viewer-pro

**Comment by roleoroleo** [comment]
> Plus I used http://MyCamIP/8080/cgi-bin/service.sh?name=RTSP&action=START&param1=HIGH

This step is not needed.

> As you can tell I don’t have a clue what I am doing. 
> 
> Now I am going to try to get it to work with
> 
> https://channelstore.roku.com/details/143683/ip-camera-viewer-pro

Does this sw support onvif?

**Comment by Merlynda** [comment]
Yes the roku app does


“Developed by:
Ioan Ghip   

IP Camera Viewer Pro allows you to view live video from most IP cameras on your TV.

It fully supports Motion-JPEG streams, RTSP (jpg encoded), ONVIF, Motion Detection, PTZ for major brands cameras and Basic/Digest Authentication. 

You can also see multiple cameras - 2, 3 or 4 - in a Split Screen View.

IP Camera Viewer Pro also provides a screen saver that will display the stream from your favorite cameras in a rectangle that moves around on your TV screen on a black background.”

**Comment by Merlynda** [comment]
![7708CBBB-D998-48C7-A0F9-84EE698D1645](https://user-images.githubusercontent.com/67579946/86281852-2b184000-bbac-11ea-9929-961f8c794638.jpeg)
![680A474A-AC8A-4DD6-9C72-5971012E04B9](https://user-images.githubusercontent.com/67579946/86281854-2c496d00-bbac-11ea-935e-bb7530f4e062.jpeg)

**Comment by Merlynda** [comment]
![B0CEDF74-B5D6-4865-89DA-EB9A85649A01](https://user-images.githubusercontent.com/67579946/86281909-4420f100-bbac-11ea-9672-94b1ca7fa643.jpeg)

**Comment by roleoroleo** [comment]
I think you should try "Scan" and enter the IP address of the cam.
Don't use snapshot as a stream.

**Comment by Merlynda** [comment]
I did and it filled in snapshot URL

P.S. not working in Roku yet...

**Comment by roleoroleo** [comment]
Probably Roku supports only rtsp with jpeg encoding.
This is not common, normally rtsp uses h264 or h265 encoding.
Yi cam uses h264 and it doesn't depends on my hack. I can't change this behavior.

**Comment by Merlynda** [comment]
I think you are correct regarding roku only supporting rtsp with jpeg. 

I sent developer the question
