### ISSUE TITLE
Roku IP Cam viewer 

### ISSUE THREAD

**Issue by Merlynda** [roleoroleo/yi-hack-Allwinner#74]
Can you add support for hack to this app

https://channelstore.roku.com/details/143683/ip-camera-viewer-pro

**Comment by roleoroleo** [comment]
If you install the hack, you can use the cam with a standard protocol.
Try ONVIF or rtsp protocol.
If this app doesn't support these standard protocols, I can't help you. You have to ask to the maintainer.
