### ISSUE TITLE
MQTT isn't working

### ISSUE THREAD

**Issue by Dragon0501** [roleoroleo/yi-hack-Allwinner#76]
After installation the first setup was made. in the broker are two objects, but there is no motion detection. The states don't change...
Are there some special configs I have to do to get the mqtt working?
Recognized a smaller Problem I think:

{
"start":"1970-01-01T01:00:00+0100",
"end":"2020-07-03T05:44:17+0200",
"files":[ "2020Y07M03D05H/44M00S60.mp4", "2020Y07M03D05H/43M00S60.mp4", "2020Y07M03D05H/42M00S60.mp4", "2020Y07M03D05H/41M09S51.mp4" ]
}

This is the files datapoint. I think he refreshes the objects. Just the motion start/stop event doesn't work. Am I right? Thats just the information about the videofiles.

**Comment by roleoroleo** [comment]
Check the client id. It must be unique in your mqtt network.
Check the topic suffix for motion detection.

**Comment by Dragon0501** [comment]
The client ID is unique. I have just one cam in my whole network. I don't know what you mean by check the topic suffix. What do I have to check?

**Comment by Dragon0501** [comment]
![Cam](https://user-images.githubusercontent.com/59663011/86445724-2e7a0b80-bd13-11ea-8496-3724f5deb149.jpg)

**Comment by Dragon0501** [comment]
Thats the view of the broker. But it doesn't refresh...

**Comment by Dragon0501** [comment]
![Broker1](https://user-images.githubusercontent.com/59663011/86445925-80229600-bd13-11ea-9dd6-edcf4d9e4f4b.jpg)
![Broker2](https://user-images.githubusercontent.com/59663011/86445928-81ec5980-bd13-11ea-8e58-e13d7f31d1fe.jpg)
Config of the broker... The User and password must be correct, because the connects to the broker.

**Comment by roleoroleo** [comment]
I mean this:
![immagine](https://user-images.githubusercontent.com/39277388/86451423-30e06380-bd1b-11ea-91be-362edd4308dc.png)

**Comment by Dragon0501** [comment]
I changed it. 
Topic Suffix is motion
The other ones are just start and stop. If it is necessary to keep the original ones I can change it again, but it doesn't works with the original ones too.

**Comment by Dragon0501** [comment]
Is ist important to keep the original Topics?

**Comment by Dragon0501** [comment]
![Screenshot_2020-07-03-12-59-22-791_com android chrome](https://user-images.githubusercontent.com/59663011/86463064-14e5bd80-bd2d-11ea-88d9-5465c7ade374.jpg)
Reset to former values
Doesn't help, still not working.

**Comment by roleoroleo** [comment]
It's not necessary to restore defaults.
You can change it as you want.

Try to read this issue:
https://github.com/roleoroleo/yi-hack-MStar/issues/189

**Comment by Dragon0501** [comment]
I read it. Do you want to tell me to reset the camera or what do you want to tell me? How do I flash an older version if you want me to do that. I don't understand what you want to tell me... I am sorry. I think the problem is the same I have...

**Comment by Dragon0501** [comment]
Thank you very much! That solved the problem! First flash the 0.1.5 after that update through the software and worked at first try!!!! Amazing! Thank you for your assistance!
