### ISSUE TITLE
model 9FUS totally bricked

### ISSUE THREAD

**Issue by gjunger** [roleoroleo/yi-hack-Allwinner#78]
after hacking the 9FUS, firmware 8.2.0 with 0.1.6 (the cam rebooted once and solid blue light) the cam is totally dead. Can´t restart anymore. Also tried to unhack. Nothing happens. 
Is there a chance to get the cam back to life again?
Thank you for any idea I can try

**Comment by roleoroleo** [comment]
If the led is solid blue, the cam should work.
Open the yi app and try to use it.

**Comment by gjunger** [comment]
the led was solid blue during the hacking process. but never seen again after rebooting the cam. cam is not usable and not recognised by the yi app. so I think I can trash it :-(

**Comment by roleoroleo** [comment]
Try to login with telnet.

**Comment by gjunger** [comment]
Sorry if I´m boring you, but the cam is not connected to the network, I can´t find any IP adress i could use for telnet. The cam does not react to anything!

**Comment by roleoroleo** [comment]
You could try to recover it following the unbrick guide.
See the wiki.

**Comment by gjunger** [comment]
Thank you very much for your support. But it´s not worth to waste our time for this 18€ camera. I´ll throw it out of the window! But I have two more cameras and I am afraid to use your great hack again. The only reason for me is to get ftp access. Thx and greets from Austria

**Comment by roleoroleo** [comment]
If you have to change idea let me know.
