### ISSUE TITLE
Update impossible

### ISSUE THREAD

**Issue by Dragon0501** [roleoroleo/yi-hack-Allwinner#80]
I installed the yihack as yesterday on two other cams today. If I try to update it by the update button it tells unable to download. It is impossible to update to 0.1.7

**Comment by pbanj** [comment]
ya i cant get it to download using the built in updater either.

**Comment by roleoroleo** [comment]
Try now.

**Comment by Dragon0501** [comment]
Works! Thank you! Only problem is there is no link on the first page. There are just the words. You can't select the "links"
![IMG_20200704_224809](https://user-images.githubusercontent.com/59663011/86520805-c9c0cd00-be48-11ea-83e4-be47d0f2f40a.jpg)

**Comment by pbanj** [comment]
clear your browser cache. ctrl+f5 on windows

**Comment by Dragon0501** [comment]
Perfect!

**Comment by Dragon0501** [comment]
Solved

**Comment by pbanj** [comment]
You should close the issue
