### ISSUE TITLE
Yi-Hack V0.1.7 no rtsp

### ISSUE THREAD

**Issue by murigny** [roleoroleo/yi-hack-Allwinner#81]
Hello
v0.1.7 success installed on 2 cams
rtsp (high) work after install but, if you reboot, no more stream.

config rtsp high: nok
config rtsp both: high=nok low=ok
config rtsp low: ok

**Comment by Catfriend1** [comment]
I have this problem too after upgrading from v0.1.6 to v0.1.7

**Comment by Catfriend1** [comment]
Could it be commit https://github.com/roleoroleo/yi-hack-Allwinner/commit/9ebd1173a24aa51e4d7a0a20e5ddac3ca4ae1e23 to blame here?

**Comment by roleoroleo** [comment]
@Catfriend1 
Did you solve?

**Comment by Catfriend1** [comment]
No, didn't compile it.

**Comment by murigny** [comment]
Trying all configuration combination and nothing on high res.
Try with motion, ispy and vlc
When i use vlc, there is something on stream (timeline work) and codec info is H264 but no picture.
Sometime it work for a few minutes and then down

**Comment by roleoroleo** [comment]
The commit you mentioned was overwritten.
The RTSP server is the same between version 0.1.6 and 0.1.7.

**Comment by murigny** [comment]
I'm trying to recompile, same result

**Comment by roleoroleo** [comment]
Yes, thank you.

**Comment by murigny** [comment]
Hello
I'm looking about logs but there is nothing strange in it.
Is there any way to add dmesg command in futur release ?

**Comment by roleoroleo** [comment]
With 0.1.6, does it work?

**Comment by murigny** [comment]
Yes, work with 0.1.6. some artefacts but work

**Comment by Catfriend1** [comment]
0.1.6 was the last version it worked for me, too.

**Comment by AymericM78** [comment]
Hello folks!

Same issue here, and it's weird because I have 2 cams, 2 Yi 1080p Home bought the same day.
The first one has the following configuration : 
- Firmware Version | 0.1.7
- Base Version | 8.2.0.0A_201912270941
- Model Suffix | y20ga
- Serial Number | 9FUSY31N9ZHVJ7200104

And RTSP is working like a charm.

The second one has the following configuration : 
- Firmware Version | 0.1.6
- Base Version | 8.2.0.0A_201912270941
- Model Suffix | y20gam
- Serial Number | 9FUSY31MVL3J2C200104

And RTSP is responding on VLC without video, audio only.
I was on 0.1.6 and it was working.
I have upgraded to 0.1.7 and the RTSP was KO.
Then I have removed hack (with https://github.com/roleoroleo/yi-hack-Allwinner/wiki/Remove-the-hack) and then reinstall 0.1.6.
But the issue still there.

I hope it will help to troubleshoot and found the cause and resolution.

Thanks!

**Comment by murigny** [comment]
try compiling without "Move rmm start position" commit: same issue

**Comment by murigny** [comment]
> Then I have removed hack (with https://github.com/roleoroleo/yi-hack-Allwinner/wiki/Remove-the-hack) and then reinstall 0.1.6.
> But the issue still there.
> 
> I hope it will help to troubleshoot and found the cause and resolution.
> 
> Thanks!

same here.
try removed hack + reset cam + flash 0.1.6 = issue still here.
something is broken. :(

**Comment by roleoroleo** [comment]
If you restore an older version you have to remove the comment sign '#' before rmm inside init.sh.

**Comment by roleoroleo** [comment]
I will investigate it.

**Comment by murigny** [comment]
thanks, i use low res 👍 
it's a strange issue

**Comment by roleoroleo** [comment]
Could you try with and without audio?

**Comment by roleoroleo** [comment]
I don't understand.

- I removed the hack.
- I checked that the hack was correctly removed.
- I reinstalled 0.1.7.
- All is working properly: low and high res.

**Comment by roleoroleo** [comment]
Or better...
Dump your flash and share it with me.
See the wiki.
mtdblock2 and mtdblock3 are enough.

**Comment by murigny** [comment]
here is backup of 0.1.7 with rtsp high broken
[backup.zip](https://github.com/roleoroleo/yi-hack-Allwinner/files/4917928/backup.zip)

**Comment by roleoroleo** [comment]
Ok, thanks.

**Comment by roleoroleo** [comment]
Very strange, in your backup you miss init.sh file.
How does it work?

**Comment by roleoroleo** [comment]
Used your file system and your config.
All is working properly.
What about a network issue?

**Comment by murigny** [comment]
cams are on two different AP (for proximity) on wifi (N)
first at 6meters
second at 4 meters

**Comment by murigny** [comment]
This is VLC media info when streaming rtsp high (no picture but timeline work)

![Sans titre 1](https://user-images.githubusercontent.com/66214639/87423354-7124c900-c5da-11ea-866d-9553ff962ed5.jpg)

**Comment by roleoroleo** [comment]
Ok, are you able to do some tests?
If yes, try this please.

Restore the rmm start in file /home/app/init.sh
From:
```
...
#sleep 2
#./rmm &
#sleep 2
#./mp4record &
#./cloud &
#./p2p_tnp &
#./oss &
#./watch_process &
/usr/sbin/telnetd &
/home/yi-hack/script/system.sh
```
To:
```
...
sleep 2
./rmm &
#sleep 2
#./mp4record &
#./cloud &
#./p2p_tnp &
#./oss &
#./watch_process &
/usr/sbin/telnetd &
/home/yi-hack/script/system.sh
```

Change the middle part of /home/yi-hack/script/system.sh replacing all if [[ $(get_config DISABLE_CLOUD)
To:
```
if [[ $(get_config DISABLE_CLOUD) == "no" ]] ; then
    (
        cd /home/app
        if [[ $(get_config RTSP_AUDIO) != "none" ]] ; then
            killall rmm
            sleep 2
            OLD_LD_LIBRARY_PATH=$LD_LIBRARY_PATH
            export LD_LIBRARY_PATH="/home/yi-hack/lib:/lib:/usr/lib:/home/lib:/home/qigan/lib:/home/app/locallib"
            ./rmm &
            export LD_LIBRARY_PATH=$OLD_LD_LIBRARY_PATH
            sleep 4
            dd if=/tmp/audio_fifo of=/dev/null bs=1 count=8192
        fi
		sleep 2
        ./mp4record &
        ./cloud &
        ./p2p_tnp &
        ./oss &
        if [ -f ./oss_fast ]; then
            ./oss_fast &
        fi
        if [ -f ./oss_lapse ]; then
            ./oss_lapse &
        fi
        ./watch_process &
    )
else
    (
        cd /home/app
        if [[ $(get_config RTSP_AUDIO) != "none" ]] ; then
            killall rmm
            sleep 2
            OLD_LD_LIBRARY_PATH=$LD_LIBRARY_PATH
            export LD_LIBRARY_PATH="/home/yi-hack/lib:/lib:/usr/lib:/home/lib:/home/qigan/lib:/home/app/locallib"
            ./rmm &
            export LD_LIBRARY_PATH=$OLD_LD_LIBRARY_PATH
            sleep 4
            dd if=/tmp/audio_fifo of=/dev/null bs=1 count=8192
        fi
		sleep 2
        # Trick to start circular buffer filling
        start_buffer
        if [[ $(get_config REC_WITHOUT_CLOUD) == "yes" ]] ; then
            ./mp4record &
        fi
    )
fi
```

Try with and without audio.

**Comment by murigny** [comment]
try your tips:
nothing change, with or without audio.
And what about "ARCHIVE=live.2020.05.15.tar.gz" perhaps this update is buggy ?

**Comment by roleoroleo** [comment]
Ok, another step.
Try to stop manually rRTSPServer and run h264grabber with debug option.
Just to see if there is something bad.

**Comment by murigny** [comment]
nothing strange:
- many "frame detected - frame_res: 1080 - frame_len: 2849 - frame_counter: 2417" len change and counter progress
- "SPS detected - frame_res: 1080 - frame_len: 20 - frame_counter: 2408" regularly
- "frames lost: 2" sometime

**Comment by roleoroleo** [comment]
?!?
Clean the SD and try again to load 0.1.6.

**Comment by murigny** [comment]
nothing. orange led, no reboot, no "clic".
sorry, cam is dead

**Comment by AymericM78** [comment]
@murigny I had this yesterday.

Retry the "Remove hack" procedure: https://github.com/roleoroleo/yi-hack-Allwinner/wiki/Remove-the-hack
then reset and pray

**Comment by murigny** [comment]
@AymericM78 : i've tried this method with no success.

cam is going to litter

**Comment by roleoroleo** [comment]
Connect the serial cable and access to uboot.
We will restore the cam.

**Comment by murigny** [comment]
Sorry roleoroleo, i give up.
Thanks for your involvement ;)

**Comment by roleoroleo** [comment]
I'm sorry.
If you want to try in the future, I will publish a wiki to unbrick the cam.

**Comment by roleoroleo** [comment]
Does anyone want to continue analyzing the problem?

**Comment by AymericM78** [comment]
@roleoroleo  Me ! :)

**Comment by roleoroleo** [comment]
Ok thanks.
Is this your current situation?
https://github.com/roleoroleo/yi-hack-Allwinner/issues/81#issuecomment-657665419

**Comment by AymericM78** [comment]
yes, RTSP is KO and only work in low-res.
The issue appeared after 0.1.7 upgrade and even after unhack+downgrade to 0.1.6 the issue still there.
I have upgraded to 0.1.7.

For your information, high res snapshot is OK 

Let me know if you need to try something.

Thanks

**Comment by roleoroleo** [comment]
I can't understand why it doesn't work with 0.1.6 after unhack.

Send me please a backup of your cam (only mtdblock3 that doesn't contain personal info).
And your configuration files (remove personal info).

**Comment by roleoroleo** [comment]
And if you have time to spend, I would like to have the mtdblock3 after unhack + 0.1.6.

I tried yesterday with my cam and all is working properly.

**Comment by murigny** [comment]
Hello.
I think i found the issue: Luminosity level
My 2nd cam is outdoor and have the issue with 0.1.7 but rtsp high only work when luminosity is less than 1000lx !

I made a test at 12h00 outdoor (no rtsp high): 
I'm covering the cam with a dark cover and wait a minute: rtsp high work
then, i remove cover: lot of artefacts and after a minute: no more picture.

@AymericM78 where is your cam ?
@roleoroleo  when you test, is your cam indoor? if yes, try to test outdoor.

**Comment by roleoroleo** [comment]
Very well done, this explains many problems.
I will check it.
And yes, my cam is indoor.

**Comment by AymericM78** [comment]
Sorry guys, I'm a little bit busy actually.
But I check your point @murigny, you're right my cam is outdoor and I confirm : luminosity is causing this issue!
Now it works!

So is there a way to fix this?
Because actually my cam is recording the wall and that not my goal! 🤣

**Comment by roleoroleo** [comment]
I need some time to figure out if I can fix the problem.

**Comment by roleoroleo** [comment]
I moved my cam outdoor and I have no problem.
Could you please run rRTSPServer in debug mode?
Kill rRTSPServer and kill wd_rtsp.sh.
Then run `rRTSPServer -r both -d`
I would like to know if the size of i-framws exceeds the buffer.

**Comment by SirTerrific** [comment]
Hi, I had the problem with the upgrade from 1.6 to 1.7 . I tried several things (I had my cam continuously reboot but the last one which restore the high stream for me was that: 

- Unhack Procedure
- Install 1.6
- Disable RTSP server and restart
- Enable RTSP server and restart

After that still on 1.6, I have my High Resolution. It's pretty weird because I have 2 cam bought at the same time, installed and upgraded at the same time and only one have the but with the 1.7 . So I let it at 1.6 till a "new" version.

**Comment by roleoroleo** [comment]
The continuous reboot is not related to rtsp issue.
Probably a configuration problem.

**Comment by Muyayo22** [comment]
Good Morning,
I have the same problem too. I have two cameras outside, one of them gets plenty of light during the day, and I can't see it in high resolution while this is happening.
Thanks for the job!

**Comment by murigny** [comment]
hello
howto output rRTSPServer debug into a log.txt ?
trying: "rRTSPServer -o both -d > log.txt" but log.txt is empty

**Comment by roleoroleo** [comment]
The log is on stderr.
`rRTSPServer -o both -d 2>log.txt`

**Comment by SirTerrific** [comment]
> The continuous reboot is not related to rtsp issue.
> Probably a configuration problem.
> 

I had this issue when i tried to downgrade to 1.6 the first time.

**Comment by murigny** [comment]
> > The continuous reboot is not related to rtsp issue.
> > Probably a configuration problem.
> 
> I had this issue when i tried to downgrade to 1.6 the first time.

Yes, you have this issue if you downgrade without unhack before

**Comment by roleoroleo** [comment]
See this issue: https://github.com/roleoroleo/yi-hack-Allwinner/issues/94

**Comment by murigny** [comment]
Hello
You're right roleoroleo, framesize exceed buffer:

[log.txt](https://github.com/roleoroleo/yi-hack-Allwinner/files/4948658/log.txt)

**Comment by roleoroleo** [comment]
Tonight I will send you a new version with a bigger buffer.

**Comment by murigny** [comment]
Thanks, you're the best ;)

**Comment by AymericM78** [comment]
Thanks @roleoroleo !

**Comment by murigny** [comment]
Yes !!! 👍 
 it work with bigger buffer (147456) ! 🥇

**Comment by roleoroleo** [comment]
Here it is:
[rRTSPServer.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner/files/4949797/rRTSPServer.tar.gz)

**Comment by koevoetsfjm** [comment]
I'm following this thread. I'm having the same issue.

Dark conditions: Both SD + HD work fine.
Normal / Light conditions : Only SD stream works. In VLC, the timeline is progressing, but the image is black.

I noticed the timestamp on the stream is jumping all over the place from 13:28:33 to 145:28:33 and back.

in night conditions the HD stream works fine, but after some minutes it starts artifacting and crashes.

I run 2 of these camera's, both have the same issue.

![image](https://user-images.githubusercontent.com/12787382/87981944-540a6180-cad6-11ea-85bf-ed424231e43f.png)

and this is after a reboot:
![image](https://user-images.githubusercontent.com/12787382/87982121-92a01c00-cad6-11ea-995f-6306ecdfbd03.png)

**Comment by roleoroleo** [comment]
Try the binary above.

**Comment by koevoetsfjm** [comment]
You are a legend.

Seems to work.... replaced the file with an FTP client in ```/home/yi-hack/bin``` and did a chmod to 755.
then rebooted the server.

VLC does not like it, but MotionEYE is displaying both the SD and HD streams now.... 

I'll update this tomorrow, when the sun shines again and IR night mode is off.

(my camera is mounted at 3ms high in the shadow).

**Comment by Muyayoo** [comment]
Forgive my ignorance.  Is necessary replace a file located in / home / yi-hack-v4 / bin inside the camera with the one published above?  
PD: It is true that the connection with the camera to me now is also quite fast

**Comment by koevoetsfjm** [comment]
> Forgive my ignorance. Is necessary replace a file located in / home / yi-hack-v4 / bin inside the camera with the one published above?
> PD: It is true that the connection with the camera to me now is also quite fast

Yes, that's what I did.
first I opened a ftp session and renamed /home/yi-hack-v4/bin/rRTSPServer to /home/yi-hack-v4/bin/rRTSPServer.v017
then I copied the file from the .tar.gz into this folder
and changed the filemode to 755.
just drop in the file you extracted from the .tar.gz.

**Comment by roleoroleo** [comment]
> > Forgive my ignorance. Is necessary replace a file located in / home / yi-hack-v4 / bin inside the camera with the one published above?

Yes, and you have to extract it.
It's a compressed archive.

**Comment by Muyayoo** [comment]
The username and password is the same as the http access? I can't get in with the same credentials

**Comment by AymericM78** [comment]
Well done @roleoroleo  ! High res RTSP stream is now back ! :)

@Muyayoo I'm not using credentials, by default you need to connect with root login and without password.

**Comment by murigny** [comment]
Nice roleoroleo ;) what size of buffer did you use ?

**Comment by roleoroleo** [comment]
> Nice roleoroleo ;) what size of buffer did you use ?

At the moment 192K.
The choice does not impact performance but only memory use.

**Comment by Muyayoo** [comment]
Thank you @AymericM78!  
I have also succeeded, but it is true that VLC does not reproduce it, I am also interested in this option, so I hope it can be solved in a future update.  
Thanks again

**Comment by koevoetsfjm** [comment]
Ok, promised to report back when the camera is in daytime conditions with the latest binary RTSPServer:

- Overall the HD stream is responsive and not buffering for a long time before it displays.
- There's quite a bunch of artificating going on, but the stream is able to recover every time.
- If the light intensity increases (sunlight), the stream starts artifacting and quality drops fast.
- The HD stream is unplayable in VLC.
- The HD stream plays in Home Assistant for 10 seconds, then stalls.
- The HD stream plays well in MotionEye.

keep up the good work,
regards,
Frans.

**Comment by roleoroleo** [comment]
>     * If the light intensity increases (sunlight), the stream starts artifacting and quality drops fast.
Please, check if there is still buffer problem, running rRTSPServer in debug mode.

>     * The HD stream is unplayable in VLC.
Try to play again and again, probably it starts.

**Comment by koevoetsfjm** [comment]
> > ```
> > * If the light intensity increases (sunlight), the stream starts artifacting and quality drops fast.
> > ```
> 
> Please, check if there is still buffer problem, running rRTSPServer in debug mode.
> 
> > ```
> > * The HD stream is unplayable in VLC.
> > ```
> 
> Try to play again and again, probably it starts.

Ok, managed to generate some debug output. What should I be looking for ?
the amount of info in this log is huge.
I killed both the rtspserver and watchdog, then ran ```rRTSPServer -r both -d 2>log.txt```

(!) Today is a cloudy day, the outdoor cam is behaving very well, almost no errors.
Will try again when the sun is shining.

**Comment by roleoroleo** [comment]
Check if there are errors.

**Comment by roleoroleo** [comment]
Very old issue.
Reopen it if necessary or open a new one.
