### ISSUE TITLE
Status LED option - not matching the Status Light setting from YI App

### ISSUE THREAD

**Issue by spamsool** [roleoroleo/yi-hack-Allwinner#82]
Hello,

In both 0.16 and 0.17 sw - the status LED option in Camera Options does not reflect the current Status Light in YI App.

Thanks for the amazing software!

**Comment by roleoroleo** [comment]
Yes, it's correct.
If you save the option inside the app, the web page doesn't reflect the change.
Because I can't read the internal configuration in binary format.
But if you change the web setting, the app will reflect it.
