### ISSUE TITLE
Record to SD card ?

### ISSUE THREAD

**Issue by Merlynda** [roleoroleo/yi-hack-Allwinner#83]
Camera is not recording to SD card with firmware Y20ga_0.1.7

In Config: I have cloud disabled and record with SD disabled

In Camera settings: I have camera on and save video when motion detected

In Yi app: I have motion detection on (human detection)

What am I missing? Thx

**Comment by roleoroleo** [comment]
In config you have to switch on "Recording without Cloud".

**Comment by Merlynda** [comment]
Did that already. No joy. 

I unhacked one of the cameras and it recorded.

**Comment by roleoroleo** [comment]
Try to re-enable cloud and check if it works.
