### ISSUE TITLE
Anyway to remove the Yi watermark?

### ISSUE THREAD

**Issue by mfizz1** [roleoroleo/yi-hack-Allwinner#85]
Is there a way to remove it? In the old yi-hack-v4 it was already removed and in the the even older versions, you could follow this:

http://diy.2pmc.net/solved-xiaomi-xiao-yi-ant-home-camera-can-used-china/

But there are some changes here

**Comment by roleoroleo** [comment]
See this:
https://github.com/roleoroleo/yi-hack-Allwinner/issues/34#issuecomment-628187012

**Comment by mfizz1** [comment]
Thank you I missed that.
