### ISSUE TITLE
Question: how to upload videos on Google Drive

### ISSUE THREAD

**Issue by marcotorti** [roleoroleo/yi-hack-Allwinner#87]
Hi all, I have been trying to use a script I found to automatically upload videos on gDrive. Unfortunately all my attempts to trigger the script via telnet failed.
Is there an alternative way to do so? Any recommendations?

**Comment by mfizz1** [comment]
what error are you getting?

**Comment by marcotorti** [comment]
I cannot run the script from porunov:
https://github.com/porunov/xiaomi_gdrive

I know it is for a different Yi Cam version, I was just hoping it could be a starting point.

I saw there has been quite a lot of work on this in the MSTAR version of the camera (https://github.com/sorokin-e/xiaomi_gdrive), but not sure it is compatible with the Allwinner version..

I apologise for my limited knowledge, I just started with Yi cameras, but I'm reading everything I can find.

**Comment by mfizz1** [comment]
You need to be a little more specific to what the error is.. what message are you getting when you run the script

**Comment by roleoroleo** [comment]
> I saw there has been quite a lot of work on this in the MSTAR version of the camera (https://github.com/sorokin-e/xiaomi_gdrive), but not sure it is compatible with the Allwinner version..

This is a good start point. Probably there are some busybox commands to change.
And you need this archive:
[gdrive_utils.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner/files/4899398/gdrive_utils.tar.gz)

**Comment by marcotorti** [comment]
Thank you both, I'll give it a try and keep you informed

**Comment by Mick2011** [comment]
Did anyone get this working?

**Comment by Mick2011** [comment]
:(

**Comment by mfizz1** [comment]
Have you tried it yet? It appears there is no reason why it shouldn't work.. there is a compiled curl and busy box and the script from mstar version has been consolidated to work with the limited number of  binaries available..

**Comment by Mick2011** [comment]
I didn't, I'll give it a try tomorrow if I can figure it out and report back.
