### ISSUE TITLE
Update brick the camera

### ISSUE THREAD

**Issue by MrPatate87** [roleoroleo/yi-hack-Allwinner#93]
Just see today you made some update to this great hack.
Loving this work and whant to find the new features on this hack I decide to made the update via the manadgement tool of the web interface. 
My previous FW was 0.1.6 version, i clic to the update link of the interface telling me downloading new verqion and rebooting the camera.
But the damera never reboot, ear a clic, and the led always on on yellow, but nothing more.
When I trying to reconnect to the web interface, no result, th rtsp I have se on this cam was not connected.
What can I do to made this cam came back to life?

**Comment by MrPatate87** [comment]
Really sorry, the update was made after a long time so long I really think the camera was brick (More than 15 minutes) but seems run well

**Comment by roleoroleo** [comment]
This is a know issue.
If the SD card is full (eg a lot of mp4 files) the upgrade requires more time.
