### ISSUE TITLE
Problem downgrading from 0.1.7

### ISSUE THREAD

**Issue by roleoroleo** [roleoroleo/yi-hack-Allwinner#94]
There is a problem downgrading from version 0.1.7.
When the hack runs, it add a comment sign to several lines in /home/app/init,sh
In 0.1.6 and previous versions was:
```
### Disable Yi junk in init.sh
echo "### Disabling Yi Junk"
sed -i 's/^.\/mp4record/#.\/mp4record/g' /home/app/init.sh
sed -i 's/^.\/cloud/#.\/cloud/g' /home/app/init.sh
sed -i 's/^.\/p2p_tnp/#.\/p2p_tnp/g' /home/app/init.sh
sed -i 's/^.\/oss/#.\/oss/g' /home/app/init.sh
sed -i 's/^.\/watch_process/#.\/watch_process/g' /home/app/init.sh
```

In 0.1.7 is:
```
### Disable Yi junk in init.sh
echo "### Disabling Yi Junk"
sed -i 's/^.\/mp4record/#.\/mp4record/g' /home/app/init.sh
sed -i 's/^.\/cloud/#.\/cloud/g' /home/app/init.sh
sed -i 's/^.\/p2p_tnp/#.\/p2p_tnp/g' /home/app/init.sh
sed -i 's/^.\/oss/#.\/oss/g' /home/app/init.sh
sed -i 's/^.\/watch_process/#.\/watch_process/g' /home/app/init.sh
sed -i 's/^.\/rmm/#.\/rmm/g' /home/app/init.sh
sed -i 's/^sleep 2/#sleep 2/g' /home/app/init.sh
```

I added 2 commented lines.
This is not a problem when you upgrade to 0.1.7 but when you downgrade to 0.1.6 or below there isn't a procedure to restore the original lines.
This means that rmm process doesn't start and cam doesn't work.

To solve the problem you have to remove the hack (original fw features are restored) and apply hack 0.1.6 or previous.

The unhack procedure restores init.sh completely. You don't need to follow the unbrick procedure, but only unhack.
In theory the final result of unhack and unbrick is the same. Except that the 1st does it using SD while the 2nd using serial and uboot.

**Comment by murigny** [comment]
Hello.
To do this, we must have a dump of clean partition (before 0.1.7).
Is somebody have this ?
