### ISSUE TITLE
How to be sure to get the good camera ? (serious issue ! :p)

### ISSUE THREAD

**Issue by skrew** [roleoroleo/yi-hack-Allwinner#98]
Hi,

Sorry, i know it's not a dev question, but I've already bought 2 Yi dome 1080p and got two 2016 version (i wanted 2019/2020 version for MStar firmware)

As this repository is active, i want to test with supported Yi home 1080p with this firmware.

It's safe to buy a Yi home from Amazon(.de) ?

Thanks !

**Comment by roleoroleo** [comment]
I think it's not possible.

**Comment by jjansen85** [comment]
I bought it from amazon.nl. Got a 9FUSY310OZ
It is running perfectly with this firmware.

**Comment by Catfriend1** [comment]
Amazon germany also delivered a compatible model to me of the 1080p home a month ago.

**Comment by skrew** [comment]
@Catfriend1 Can you confirm it's this one ? 

https://www.amazon.de/YI-%C3%9Cberwachungskamera-Nachtsicht-Bewegungsmelder-Smartphone/dp/B01MR82NFZ/ref=sr_1_1_sspa?dchild=1&keywords=yi+home&qid=1595161756&sr=8-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUExN1lETklPNTk5SEZVJmVuY3J5cHRlZElkPUEwNTEyNjk4TUpEMThUREpHVDVWJmVuY3J5cHRlZEFkSWQ9QTAwMTk4OTkyQUFRNkdGVkxYMllQJndpZGdldE5hbWU9c3BfYXRmJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ==

Thanks !

**Comment by Catfriend1** [comment]
We've bought the "family pack" , Link https://www.amazon.de/gp/aw/d/B06XHVNNNV/ref=psdcmw_119915031_t1_B01MR82NFZ

**Comment by Schm1tz1** [comment]
@skrew I have bought 2 of these family packs. Both contained 9FUSY3* cameras that work perfectly with the Allwinner-Firmware.

**Comment by Catfriend1** [comment]
Interesting, mine is a BFUSY model

**Comment by Schm1tz1** [comment]
Checked again, same link, same article, all are 9FUSY. I bought one 2 weeks ago and one yesterday.

**Comment by Catfriend1** [comment]
Yes, I believe you :). Wonder why there is such a model variety out there...

**Comment by skrew** [comment]
Thanks all, i've ordered on amazon.de, i will tell you

**Comment by skrew** [comment]
Received (9FUSY31)
First attempt, i got a blink yellow, and after a reset, a solid yellow.
Second try was the good one !

Image look "too much detailed", like after applied sharpening filter in photoshop too many time (i don't know if it come from the hack or if it's the normal quality) but it works and now i have my timelapse camera, finally ! :)

Thanks !

**Comment by roleoroleo** [comment]
It depends on the camera, not on the hack.
